language: node_js
node_js:
  - "0.12"
before_install:
  - cd peptides
  - npm install -g npm
  - npm config set loglevel warn
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli
  - npm install grunt-karma --save-dev
