language: node_js
node_js:
  - "0.12.0"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd peptides
  - npm install -g npm
  - npm config set loglevel warn
before_script:
  - npm install
