var biovizWorkerNamespace = {};
(function(ns) {
importScripts('library/polyfill.js', 'library/cif.js');
var z,ba=[];function ca(e){return function(){return ba[e].apply(this,arguments)}}var ha="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"===typeof Symbol&&e.constructor===Symbol?"symbol":typeof e},ka=function ia(){if(this.constructor===ia)throw Error("Can't instanciate abstract class BiovizMap");};z=ka.prototype;z.set=function(){throw Error("Trying to call an abstract method");};
z.get=function(){throw Error("Trying to call an abstract method");};z.remove=function(){throw Error("Trying to call an abstract method");};z.Zc=function(){throw Error("Trying to call an abstract method");};z.keys=function(){throw Error("Trying to call an abstract method");};z.values=function(){throw Error("Trying to call an abstract method");};z.clear=function(){throw Error("Trying to call an abstract method");};z.yd=ca(2);function Ca(){ka.call(this);this.ka=new Map;this.qd=new Map}Ca.prototype=Object.create(ka.prototype);
z=Ca.prototype;z.constructor=Ca;z.set=function(e,f){var g=Fa(e);this.ka.set(g,f);this.qd.set(g,e)};z.get=function(e){e=Fa(e);return this.Zc(e)?this.ka.get(e):null};z.remove=function(e){e=Fa(e);if(this.Zc(e)){var f=this.ka.get(e);this.ka["delete"](e);this.qd["delete"](e);return f}return null};z.Zc=function(e){e=Fa(e);return this.ka.has(e)};
z.keys=function(){var e=[],f=!0,g=!1,h=void 0;try{for(var k=this.ka.keys()[Symbol.iterator](),m;!(f=(m=k.next()).done);f=!0)e.push(m.value)}catch(l){g=!0,h=l}finally{try{!f&&k["return"]&&k["return"]()}finally{if(g)throw h;}}return e};z.values=function(){var e=[],f=!0,g=!1,h=void 0;try{for(var k=this.ka.values()[Symbol.iterator](),m;!(f=(m=k.next()).done);f=!0)e.push(m.value)}catch(l){g=!0,h=l}finally{try{!f&&k["return"]&&k["return"]()}finally{if(g)throw h;}}return e};
z.clear=function(){this.ka.clear();this.qd.clear()};z.yd=ca(1);function Fa(e){if(e instanceof Array){e=[];for(var f=e.length,g=0;g<f;g++)e.push(e[g].Bb());return e.join("")}return e instanceof Object?e.Bb():e}function Ja(){ka.call(this);this.ka=[]}function Oa(e,f){this.key=e;this.value=f}Ja.prototype=Object.create(ka.prototype);z=Ja.prototype;z.constructor=Ja;
z.set=function(e,f){if(void 0===e)throw"ERROR: key cannot be undefined";var g;a:if(void 0!==e.uf)g=this.ka[e.uf];else{for(g in this.ka)if(this.ka[g].key===e){g=this.ka[g];break a}g=void 0}void 0===g?"object"===("undefined"===typeof e?"undefined":ha(e))&&(e.uf=this.ka.push(new Oa(e,f))-1):g.value=f};z.get=function(e){if(void 0!==e.uf)return this.ka[e.uf].value;for(var f in this.ka)if(this.ka[f].key===e)return this.ka[f].value};z.keys=function(){var e=[],f;for(f in this.ka)e.push(this.ka[f].key);return e};
z.Zc=function(e){return-1!==this.keys().indexOf(e)};z.values=function(){var e=[],f;for(f in this.ka)e.push(this.ka[f].value);return e};z.remove=function(e){var f=-1,g;for(g in this.ka)if(this.ka[g].key===e){f=g;break}return 0<=f?this.ka.splice(f,1)[0].value:null};z.clear=function(){this.ka=[]};z.yd=ca(0);

function Va(e){e.ka=new Map(JSON.parse(e.ka));e.qd=new Map(JSON.parse(e.qd))}function Wa(){this.pos=new THREE.Vector3;this.ca=this.Ja=this.bc=this.u=this.v=this.qc=this.ea=this.symbol=this.wa=this.ja=this.td=this.name=this.id=this.type=null}z=Wa.prototype;z.ta=function(){return this.id};z.ib=function(){return this.Ja};function ab(e,f){e.u!==f&&(e.u=f,null!==e.Ja&&e.Ja.lc(f))}z.Wa=function(){return this.pos};
z.tc=function(){if(null===this.ca){var e=parseFloat(bb(this.symbol)[7]),f=new THREE.Vector3(-e,-e,-e),e=new THREE.Vector3(e,e,e);this.ca=new kb(f,e)}return this.ca};z.radius=function(){return parseFloat(bb(this.symbol)[7])};z.xb=function(){return this.bc};function wb(e,f){if(e.bc!==f&&(e.bc=f,null!=e.Ja)){var g=e.Ja,h=e.bc;if(g.bc!=h){g.bc=h;for(var k=g.u.length,m=0;m<k;m++)wb(g.u[m],h)}}}z.Lc=function(){return this.qc};z.Ve=function(e){this.qc!=e&&(this.qc=e,null!==this.Ja&&this.Ja.Ve(e))};
z.Wf=function(){return this.v};z.je=function(e){this.v!==e&&(this.v=e,null!==this.Ja&&this.Ja.je(e))};z.toString=function(){return this.symbol+":"+this.id};z.Mc=function(){return this.Ja.Mc()+":"+this.toString()};z.Bb=function(){return this.symbol+":"+this.id+":"+this.v};z.distanceTo=function(e){return e instanceof Wa?this.pos.distanceTo(e.pos):this.pos.distanceTo(e)};z.distanceToSquared=function(e){return e instanceof Wa?this.pos.distanceToSquared(e.pos):this.pos.distanceToSquared(e)};
z.sub=function(e){return e instanceof Wa?new THREE.Vector3(this.pos.x-e.pos.x,this.pos.y-e.pos.y,this.pos.z-e.pos.z):new THREE.Vector3(this.pos.x-e.x,this.pos.y-e.y,this.pos.z-e.z)};z.add=function(e){return e instanceof Wa?new THREE.Vector3(this.pos.x+e.pos.x,this.pos.y+e.pos.y,this.pos.z+e.pos.z):new THREE.Vector3(this.pos.x+e.x,this.pos.y+e.y,this.pos.z+e.z)};z.clone=function(){return new THREE.Vector3(this.pos.x,this.pos.y,this.pos.z)};
function xb(){this.ja=null;this.u=new yb;this.ca=[];this.wa=this.v=this.ea=null}z=xb.prototype;z.uc=function(){return this.ja};z.We=function(e){this.ja=e;e=this.ca.length;for(var f=0;f<e;f++)f.We(this.ja)};z.add=function(e){if(e instanceof Wa)return e=this.u.Mf(e),zb(this),e;e instanceof Nb?((null!==e.Ib&&e.Ib!==this||e.Ib===this)&&console.warn("ERROR: ",e,"already belongs to",e.Ib),null===e.Ib&&(this.ca.push(e),e.We(this.ja),e.Ib=this,zb(this))):console.warn("ERROR : a is not an atom or a molecule")};
z.remove=function(e){e instanceof Wa?(e=this.u.findNode(atom),-1<e&&(delete this.u[e],zb(this))):e instanceof Nb&&(null===molecule&&console.warn("molecule null in function remove in model"),molecule.Ib===this&&(this.ca.splice(this.ca.Qa(molecule),1),molecule.We(null),molecule.Ib=null,zb(this)))};z.Aa=function(){return this.u.values()};
z.Qb=function(){if(!this.wa){this.u.ak();this.v=this.tc();for(var e=new Sb(this.v.Ke(),this.v.Je(),32),f=this.Aa(),g=0,h=f.length;g<h;g++)e.add(new gc(f[g]));e.optimize();h=f.length;for(g=0;g<h;g++)for(var k=f[g],m=k.symbol,m=m.charAt(0).toUpperCase()+m.slice(1).toLowerCase(),l=parseFloat(bb(m)[6]),q=e.lh(k.pos,5),r=q.length,t=0;t<r;t++){var x=q[t].getPoint();if(x!==k){var m=x.symbol,m=m.charAt(0).toUpperCase()+m.slice(1).toLowerCase(),w=parseFloat(bb(m)[6]),m=l+w-.4,w=l+w+.4,B=k.distanceTo(x);B>=
m&&B<=w&&(m=k,w=this.u.findNode(m),B=this.u.findNode(x),void 0!==w&&void 0!==B||console.warn("Couldn't find atoms ",m," and/or ",x," in model ",this),w.jj(B)||this.u.Rg(w,B).setAttribute("BondType","SIMPLE"))}}this.wa=!0}return this.u};function zb(e){e.ea=null;e.v=null;e.wa=!1}z.Wa=function(){if(null===this.ea){this.ea=new THREE.Vector3;for(var e=this.Aa(),f=0,g=0,h=0,k=e.length,m=0;m<k;m++)var l=e[m].pos,f=f+parseInt(l.x),g=g+parseInt(l.y),h=h+parseInt(l.z);this.ea.set(f/k,g/k,h/k)}return this.ea};
z.tc=function(){if(null===this.v){for(var e=new THREE.Vector3(Infinity,Infinity,Infinity),f=new THREE.Vector3(-Infinity,-Infinity,-Infinity),g=this.Aa(),h=0,k=g.length;h<k;h++){var m=g[h].pos;e.x=Math.min(e.x,m.x);e.y=Math.min(e.y,m.y);e.z=Math.min(e.z,m.z);f.x=Math.max(f.x,m.x);f.y=Math.max(f.y,m.y);f.z=Math.max(f.z,m.z)}this.v=new kb(e,f)}return this.v};function Nb(e){this.id=e;this.Ib=this.ea=this.type=null;this.ga=[];this.v=this.ca=this.u=null;this.Lf=!1}z=Nb.prototype;z.ta=function(){return this.id};
z.Qb=function(){return this.Ib.Qb()};z.lc=function(e){if(this.id!==e){this.id=e;for(var f=0;f<this.ga.length;f++)this.ga[f].je(e)}};z.uc=function(){return this.ea};z.We=function(e){this.ea=e};z.add=function(e){null==e&&console.warn("residue is null in Molecule");null!==e.Fa&&e.Fa!==this&&console.warn(e," already belongs to ",e.Fa);null===e.Fa&&(this.ga.push(e),hc(e,this),ic(this))};
z.remove=function(e){null===e&&console.warn("residue is null in Molecule");e.Fa===this&&(this.ga.remove(e),hc(e,null),ic(this))};z.ib=function(e){for(var f=0;f<this.ga.length;f++){var g=this.ga[f];if(g.ta()==e)return g}return null};z.Aa=function(){for(var e=[],f=this.ga.length,g=0;g<f;g++)e=e.concat(this.ga[g].Aa());return e};z.size=function(){return this.ga.length};z.isEmpty=function(){return 0===this.size};function ic(e){e.u=null;e.ca=null;null!==e.Ib&&zb(e.Ib)}
z.Wa=function(){if(null===this.u){this.u=new THREE.Vector3;for(var e=this.Aa(),f=e.length,g=0;g<f;g++){var h=e[g].pos;this.u.x+=h.x;this.u.y+=h.y;this.u.z+=h.z}this.u.x/=f;this.u.y/=f;this.u.z/=f}return this.u};
z.tc=function(){if(null===this.ca){for(var e=new THREE.Vector3(Infinity,Infinity,Infinity),f=new THREE.Vector3(-Infinity,-Infinity,-Infinity),g=this.Aa(),h=g.length,k=0;k<h;k++){var m=g[k].pos;e.x=Math.min(e.x,m.x);e.y=Math.min(e.y,m.y);e.z=Math.min(e.z,m.z);f.x=Math.max(f.x,m.x);f.y=Math.max(f.y,m.y);f.z=Math.max(f.z,m.z)}this.ca=new kb(e,f)}return this.ca};z.toString=function(){return this.type+":"+this.id};z.Bb=function(){return this.toString()};z.Mc=function(){return this.ea.Mc()+":"+this.toString()};
z.Pi=function(){if(null!==this.type&&"Protein"===this.type&&!this.Lf){if(null===this.v){var e=this.ga,f=e.length;this.v=new yb;for(var g=1;g<f;g++){var h=e[g-1],k=e[g],m=this.v.findNode(k);null==m&&(m=this.v.Tg(k.toString(),k));var l=k.jc("CA"),q=k.jc("N"),r=k.jc("H");if(h.ta()+h.xb().charCodeAt(0)===k.ta()+k.xb().charCodeAt(0)-1&&"PRO"!==h.ca){r=h.jc("C");h=h.jc("O");if(null==r||null==h)continue;r=r.sub(h);r=r.normalize();h=q.add(r);r=new Wa;r.name="H";r.symbol="H";r.pos.x=h.x;r.pos.y=h.y;r.pos.z=
h.z}if(null!=r)for(h=0;h<f;h++)if(h!=g&&h!=g-1){var t=e[h],k=this.v.findNode(t);null==k&&(k=this.v.Tg(t.toString(),t));var x=t.jc("CA"),w=t.jc("C"),B=t.jc("O");if(null!=x&&null!=w&&null!=B&&!(9<x.distanceTo(l))){var x=r.distanceTo(B),t=r.distanceTo(w),B=q.distanceTo(B),D=q.distanceTo(w),w=-9.9;.5>x||.5>t||.5>B||.5>D||(w=27.888/B,w+=27.888/t,w-=27.888/x,w-=27.888/D,-9.9>w&&(w=-9.9));if(-.5>w){var x=m.Ck(k),E;null!=x?E=x.getAttribute("eH"):E=0;w<E&&(this.v.Rg(m,k,!0).setAttribute("eH",w),null!=x&&this.v.wl(x))}}}}}e=
this.ga.length;for(f=0;f<e;f++)this.ga[f].mb=null;f=1;for(l=4;f+l<e;f++)if(pc(this,this.ga[f-1],this.ga[f-1+l])&&pc(this,this.ga[f],this.ga[f+l]))for(g=f;g<f+l;g++)this.ga[g].mb=F.u;for(f=1;f+1<e;f++)for(g=f+3;g+1<e;g++)if(m=this.ga[f],l=this.ga[g],null===m.mb&&null===l.mb)if(pc(this,this.ga[f-1],l)&&pc(this,l,this.ga[f+1])||pc(this,this.ga[g-1],m)&&pc(this,m,this.ga[g+1]))m.mb=F.v,l.mb=F.v;else if(pc(this,m,l)&&pc(this,l,m)||pc(this,this.ga[f-1],this.ga[g+1])&&pc(this,this.ga[g-1],this.ga[f+1]))m.mb=
F.ea,l.mb=F.ea;f=1;for(l=3;f+l<e;f++)if(pc(this,this.ga[f-1],this.ga[f-1+l])&&pc(this,this.ga[f],this.ga[f+l])){m=!0;for(g=f;g<f+l;g++)if(null!=this.ga[g]){m=!1;break}for(g=f;g<f+l;g++)this.ga[g].mb=m?F.u:F.ja}f=1;for(l=5;f+l<e;f++)if(pc(this,this.ga[f-1],this.ga[f-1+l])&&pc(this,this.ga[f],this.ga[f+l])){m=!0;for(g=f;g<f+l;g++)if(null!=this.ga[g]){m=!1;break}for(g=f;g<f+l;g++)this.ga[g].mb=m?F.u:F.ja}for(l=3;5>=l;l++)for(f=0;f+l<e;f++)if(pc(this,this.ga[f],this.ga[f+l]))for(g=f+1;g<f+l;g++)m=this.ga[g].mb,
null==m&&(this.ga[g].mb=F.ja);for(f=0;f<e;f++)m=this.ga[f].mb,null==m&&(this.ga[f].mb=F.ca);this.Lf=!0}};z.Ll=function(e){if(e.length!=this.ga.length)for(var f=0,g=this.ga.length;f<g;f++){var h=tc[e[this.ga[f]._id-1]];this.ga[f].mb=null!=h?h:F.ca}else for(f=0,g=this.ga.length;f<g;f++)h=tc[e[f]],this.ga[f].mb=null!=h?h:F.ca;this.Lf=!0};function pc(e,f,g){f=e.v.findNode(f);return null==f?!1:f.Kk(e.v.findNode(g))}
z.be=function(e){void 0===e&&(e=!0);for(var f="",g=this.ga,h=0,k="\x00",m=this.Bd()?"X":this.Me()?"N":"-",l=g.length,q=0;q<l;q++){var r=g[q];if(e&&0!=q)for(h=r.ta()-h+r.xb().charCodeAt(0)-k.charCodeAt(0);1<h--;)f+=m;f+=r.ij();h=r.ta();k=r.xb()}return f};z.Me=function(){return"DNA"==this.type||"RNA"==this.type};z.Bd=function(){return"Protein"==this.type||"Peptide"==this.type||"Small Peptide"==this.type};z.tj=function(){return this.Me()||this.Bd()};z.sj=function(){return"Ligand"===this.type};
z.Oj=function(e){var f=new uc,g=[];g.push(new vc(this.toString(),this.be(!1)));g.push(new vc("ExternalSequence",e));f=f.align(g);e=f.be("ExternalSequence");f=f.be(this.toString());console.log(e,f);this.sk=f;console.log(f.ja())};
function Ac(e){for(var f=[],g=0,h=e.ga,k=0,m=0;m<h.length;m++){var l=h[m];if(null===l.type)k++;else{var q=f[l.type];void 0===q&&(q=0,f[l.type]=q,g++);f[l.type]++}}if(0!==g){var g=Infinity,r;for(q in f)h=f[q],0!==h&&h<g?(g=h,r=q):h===g&&q<r&&(r=q);g>=k&&("Protein"==r?(f=e.size(),e.type=20>f?"Small Peptide":60>f?"Peptide":"Protein"):e.type=r)}else e.type="Unknown"}
function Gc(){this._id=this.ea=this.qc=this.Fa=this.mb=this.type=this.ca=null;this.bc="\x00";this.u=[];this.wa=new Ca;this.Ha=this.ja=this.v=null}function Hc(e,f){e.ea=f.Vb;e._id=f.vb;e.bc=f.Xb}z=Gc.prototype;z.Qb=function(){return this.Fa.Qb()};function hc(e,f){e.Fa=f;null!==f&&void 0!==f&&e.je(f.ta())}z.ta=function(){return this._id};z.lc=function(e){if(this._id!=e){this._id=e;for(var f=0;f<this.u.length;f++)ab(this.u[f],e)}};z.xb=function(){return this.bc};z.Lc=function(){return this.qc};
z.Ve=function(e){if(this.qc!=e){this.qc=e;for(var f=this.u.length,g=0;g<f;g++)g.Ve(e)}};z.Wf=function(){return this.ea};z.je=function(e){if(this.ea!=e){this.ea=e;null!==this.Fa&&this.Fa.lc(e);for(var f=this.u.length,g=0;g<f;g++)g.je(e)}};
z.add=function(e){null===e&&console.warn("atom = null in Residue");null!==e.ib()&&e.ib()!==this&&console.warn(e," already belongs to ",e.ib());if(null===e.ib()){this.u.push(e);var f=new Ic(e.name,e.td);this.wa.Zc(f)||this.wa.set(f,e);e.Ja=this;null!==this&&(ab(e,e.Ja.ta()),wb(e,e.Ja.xb()),e.Ve(e.Ja.Lc()),e.je(e.Ja.Wf()))}};z.remove=function(e){null===e&&console.warn("atom = null in Residue");e.ib()===this&&(this.u.remove(e),e=new this.Fb(e.name,e.td),this.wa.remove(e))};z.Aa=function(){return this.u};
z.gj=function(e){for(var f=0;f<this.u.length;f++){var g=this.u[f];if(g.ta()==e)return g}return null};z.jc=function(e){var f=void 0;void 0===f&&(f="\x00");e=this.wa.get((new Ic(e,f)).toString());if(null!==e)return e};z.Wa=function(){if(null==this.v){this.v=new THREE.Vector3;for(var e=this.u.length,f=0;f<e;f++){var g=this.u[f].pos;this.v.x+=g.x;this.v.y+=g.y;this.v.z+=g.z}this.v.x/=e;this.v.y/=e;this.v.z/=e}return this.v};
z.nh=function(){if(null==this.ja)for(var e=this.u.length,f=0;f<e;f++){var g=this.u[f];if("CA"===g.name){this.ja=g.pos.clone();break}}if(null==this.ja){for(var h=this.Wa(),k=this.u[0],m=h.distanceTo(k.pos),e=this.u.length,f=0;f<e;f++){var g=this.u[f],l=h.distanceTo(g.pos);l<m&&(k=g,m=l)}this.ja=k.clone()}return this.ja};
z.tc=function(){if(null===this.Ha){for(var e=new THREE.Vector3(Infinity,Infinity,Infinity),f=new THREE.Vector3(-Infinity,-Infinity,-Infinity),g=this.u.length,h=0;h<g;h++){var k=this.u[h];e.x=Math.min(e.x,k.pos.x);e.y=Math.min(e.y,k.pos.y);e.z=Math.min(e.z,k.pos.z);f.x=Math.max(f.x,k.pos.x);f.y=Math.max(f.y,k.pos.y);f.z=Math.max(f.z,k.pos.z)}this.Ha=new kb(e,f)}return this.Ha};z.Me=function(){return"DNA"==this.type||"RNA"==this.type};
z.Bd=function(){return"Protein"==this.type||"Peptide"==this.type||"Small Peptide"==this.type};
z.ij=function(){switch(null!==this.ca?this.ca:this.qc){case "GLY":return"G";case "ALA":return"A";case "VAL":return"V";case "LEU":return"L";case "ILE":return"I";case "PRO":return"P";case "PHE":return"F";case "MET":return"M";case "TRP":return"W";case "SER":return"S";case "THR":return"T";case "ASN":return"N";case "GLN":return"Q";case "ASP":return"D";case "GLU":return"E";case "CYS":return"C";case "TYR":return"Y";case "HIS":return"H";case "LYS":return"K";case "ARG":return"R";case "ASX":return"B";case "GLX":return"Z";
case "A":case "DA":case "+A":return"A";case "C":case "DC":case "+C":return"C";case "G":case "DG":case "+G":return"G";case "T":case "DT":case "+T":return"T";case "U":case "DU":case "+U":return"U";case "I":case "DI":case "+I":return"I"}return null!=this.Fa.type&&"Protein"===this.Fa.type?"X":null==this.Fa.type||"RNA"!==this.Fa.type&&"DNA"!==this.Fa.type?"?":"N"};z.toString=function(){return this.qc+":"+this._id};z.Bb=function(){return this.qc+":"+this._id+":"+this.ea};
z.Mc=function(){return this.Fa.Mc()+":"+this.toString()};function Ic(e,f){this.name=e;this.td=f}Ic.prototype.toString=function(){return this.name+":"+this.td};Ic.prototype.Bb=function(){return this.name+":"+this.td};
function Jc(e,f){null===e.ca&&console.warn("Error : stdResName must be set before guessing residue type");if(-1!==Kc.indexOf(e.ca))e.type="DNA";else if(-1!==Qc.indexOf(e.ca))e.type="RNA";else if(-1!==Rc.indexOf(e.ca))e.type="Protein";else if(-1!==Vc.indexOf(e.Lc()))e.type="Solvent";else if(-1!==Wc.indexOf(e.Lc()))e.type=null;else{var g=f.get(e.ta());null!=g&&g.name.endsWith(" ION")&&(e.type="Ion");e.type="Ligand"}}
var Rc="GLY ALA VAL LEU ILE PRO PHE MET TRP SER THR ASN GLN ASP GLU CYS TYR HIS LYS ARG".split(" "),Qc=["A","C","G","U","I"],Kc="DA DC DG DT DI DU +A +C +G +T +I +U T".split(" "),Wc="UNK ASX GLX N DN UNL UNX".split(" "),Vc=["HOH","DOD","GOL","EDO"];
function cd(e,f,g){null===e&&console.warn("chainId null in Residue.Id");this.Vb=e;this.vb=f;this.Xb=g;this.toString=function(){return"\x00"!==this.Xb.charCodeAt(0)?this.Vb+":"+this.vb+":"+this.Xb:this.Vb+":"+this.vb};this.Bb=function(){return"\x00"!==this.Xb.charCodeAt(0)?this.Vb+":"+this.vb+":"+this.Xb:this.Vb+":"+this.vb}}function F(e,f){this.name=e;this.code=f}F.ca=new F("Coil"," ");F.ja=new F("Turn","T");F.u=new F("Helix","H");F.v=new F("Strand","x");F.ea=new F("Strand","X");
var tc={G:F.u,H:F.u,I:F.u,B:F.v,E:F.v,T:F.ja,S:F.ca,C:F.ca,X:F.ca};F.prototype.toString=function(){return name};function dd(){this.el=!0;this._id=this.Og=null;this.Hi=NaN;this.Gi=null;this.ca=[];this.Ai=[];this.Vd=new Ca;this.Td=new Ca;this.Ec=new Ca;this.wi=[];this.v=[];this.ea=new Ca;this.u=null}z=dd.prototype;
z.Wa=function(){if(null===this.u){this.u=new THREE.Vector3;for(var e=this.v[0].ca,f=0;f<e.length;f++){var g=e[f].Wa();this.u.x+=g.x;this.u.y+=g.y;this.u.z+=g.z}this.u.x/=e.length;this.u.y/=e.length;this.u.z/=e.length}return this.u};z.Qb=function(){return this.v[0].Qb()};z.ta=function(){return this._id};z.lc=function(e){null==this._id&&(this.Og=e);this._id=e};z.Ml=function(e){this.Hi=e};z.Yh=function(){};z.setDate=function(){};z.$h=function(e){this.Gi=e};z.Kl=function(){};
z.Ji=function(e,f){null==(null==e?this.ca:this.ca[e])&&(this.ca[e]=f)};z.Il=function(e){this.Ai=e};z.add=function(e){null===e&&console.warn("Error on adding model to structure : model = NULL");null!=e.uc()&&e.uc()!=this&&console.warn(e," already belongs to ",e.uc());null==e.uc()&&(this.v.push(e),e.We(this))};z.remove=function(e){null===e&&console.warn("Error on removing structure");e.uc()==this&&(this.v.remove(e),e.We(null))};z.Yf=function(){return this.v[0]};z.toString=function(){return this._id};
z.Bb=function(){return this.toString()};z.Mc=function(){return this.toString()};
z.kk=function(e){this.Vd.__proto__=Ca.prototype;Va(this.Vd);this.Ec.__proto__=Ca.prototype;Va(this.Ec);this.Td.__proto__=Ca.prototype;Va(this.Td);for(var f=e.length,g=0;g<f;g++){var h=new xb;this.add(h);for(var k=e[g],m=k.length,l=0;l<m;l++){var q=new Wa;q.type=k[l][0];q.id=k[l][1];q.name=k[l][2];q.td=k[l][3];q.Ve(k[l][4]);q.je(k[l][5]);ab(q,k[l][6]);wb(q,k[l][7]);q.pos.x=k[l][8];q.pos.y=k[l][9];q.pos.z=k[l][10];q.ja=k[l][11];q.wa=k[l][12];q.symbol=k[l][13];q.ea=k[l][14];h.add(q)}}ed(this)};
function ed(e){var f=e.Vd,g=e.Td,h=e.Ec,k=e.v,m=!1,l,q=k.length,r=new Ca;for(l=0;l<q;l++){for(var t=k[l],x=[],w=t.Aa(),B=w.length,D=0;D<B;D++){var E=w[D],I=void 0,H=new cd(E.Wf(),E.u,E.xb()),I=r.get(H);if(null==I){I=new Gc;Hc(I,H);I.Ve(E.Lc());var K=f.get(H);I.ca=K?K.vg:I.Lc();Jc(I,g);K=h.get(H);null!=K?(m||(m=!0),I.mb=K):I.mb=F.ca;x.push([I,H]);r.set(H,I)}I.add(E)}E=void 0;for(I=0;I<x.length;I++){w=x[I][0];B=x[I][1];I=w;for(D=[];void 0!==I&&null!==I&&-1===D.indexOf(B)&&!I.Bd()&&!I.Me();)if(D.push(B),
E=e.ea.get(B),null!=E){for(var E=E.Qa.Vb===B.Vb&&E.Qa.vb===B.vb&&E.Qa.Xb===B.Xb?E.vc:E.Qa,G,I=0;I<x.length;I++)H=x[I],E.Vb===H.Vb&&E.vb===H.vb&&E.Xb===H.Xb&&(G=I);I=x[G][0]}void 0!==I&&I.type!==w.type&&(w.type=I.type)}w=new Map;for(I=0;I<x.length;I++)B=x[I][0],D=B.Wf(),E=B.type+" "+D,H=w.get(E),void 0===H&&(H=new Nb(D),t.add(H),w.set(E,H)),H.add(B),H.Lf=m;t=function(e,f){return e.Kg<f.Kg?-1:e.Kg>f.Kg?1:e._id<f._id?-1:e._id>f._id?1:e.bc<f.bc?-1:e.bc>f.bc?1:0};x=!0;I=!1;B=void 0;try{for(var L=w.values()[Symbol.iterator](),
P;!(x=(P=L.next()).done);x=!0){var Q=P.value;Q.ga.sort(t);Ac(Q)}}catch(V){I=!0,B=V}finally{try{!x&&L["return"]&&L["return"]()}finally{if(I)throw B;}}}};

function Oj(e){if(Array.isArray(e)){for(var f=0,g=Array(e.length);f<e.length;f++)g[f]=e[f];return g}return Array.from(e)}function Pj(e){e.ka=JSON.stringify([].concat(Oj(e.ka)));e.qd=JSON.stringify([].concat(Oj(e.qd)))}function Ik(){this.Zi=this.ih=this.Yi=this.hh=this.gh=this.fh=this.Qf=this.vh=this.Xh=this.uh=this.Wh=this.lf=null}
function Jk(e){this.ia=this.file=null;this.xc=[];this.source=this.Yg=this.Ah=this.title=null;this.ready=!1;this.de=[];this.de[Kk.id]=Kk;this.Le=[];this.resolution=null;null==e&&(e=!1);this.Ff=e;this.zi=null}var Lk=1;
Jk.prototype.parse=function(e,f){this.zi=f;this.ia=new dd;a:{var g=e.split("\n"),h,k=null,m;for(m in g){var l=g[m];if(l===this.tm||l===this.nm)break a;if(l===this.om){this.xc.push([]);break a}var q=l.substring(0,6).trim(),r=null,t="";switch(q){case "ATOM":case "HETATM":var r=l.substring(76,78).trim(),x=l.substring(12,16).trim();""===r&&(r=x[0]);var w=this.xc[this.xc.length-1];void 0===w&&(w=[],this.xc.push(w));if(this.Ff&&"CA"!==x)break;if(!(null!==r&"H"===r)||this.zh){var B=[],t=l.charAt(21);B.push(q);
B.push(l.substring(6,11).trim());B.push(x);B.push(" "!=l.charAt(16)?l.charAt(16):"\x00");B.push(l.substring(17,20).trim());B.push(t);B.push(parseFloat(l.substring(22,26).trim()));B.push(" "!=l.charAt(26)?l.charAt(26):"\x00");B.push(parseFloat(l.substring(30,38).trim()));B.push(parseFloat(l.substring(38,46).trim()));B.push(parseFloat(l.substring(46,54).trim()));B.push(l.substring(54,60).trim());B.push(l.substring(60,66).trim());B.push(r);79<=l.length&&B.push(toString(l.charAt(79))+toString(l.charAt(78)));
w.push(B)}break;case "HEADER":59<l.length?(this.ia.Yh(l.substring(10,50).trim()),this.ia.lc(l.substring(62,66).trim())):(this.ia.Yh(l.substring(10).trim()),this.ia.lc(file.getName().replaceAll("\\..*$","").toUpperCase()));this.ia.setDate(l.substring(50,59));break;case "TITLE":this.title=null===this.title?l.substring(10):this.title+(" "+l.substring(10));this.ia.$h(this.title);break;case "SOURCE":this.source+=l.substring(10);break;case "KEYWDS":this.Ah+=l.substring(10);break;case "AUTHOR":this.Yg+=
l.substring(10);break;case "REMARK":l.substring(7,10).trim();if(~l.indexOf("RESOLUTION."))try{l.substring(l.indexOf("RESOLUTION.")+12).trim()}catch(D){console.warn("Error : ",D)}break;case "DBREF":k=new Ik;k.lf=l.charAt(12);k.Wh=l.substring(14,18).trim();k.uh=" "!==l.charAt(18)?l.charAt(18):"\x00";k.Xh=l.substring(20,24).trim();k.vh=" "!=l.charAt(24)?l.charAt(24):"\x00";k.Qf=l.substring(26,32).trim();k.fh=l.substring(33,41).trim();k.gh=l.substring(42,54).trim();k.hh=l.substring(55,60).trim();k.Yi=
" "!=l.charAt(60)?l.charAt(60):"\x00";k.ih=l.substring(62,67<=l.length?67:l.length).trim();k.Zi=68<=l.length?l.charAt(67):"\x00";this.ia.Ji(k.lf,k);break;case "DBREF1":k=new Ik;k.lf=l.charAt(12);k.Wh=l.substring(14,18).trim();k.uh=" "!=l.charAt(18)?l.charAt(18):"\x00";k.Xh=l.substring(20,24).trim();k.vh=" "!=l.charAt(24)?l.charAt(24):"\x00";k.Qf=l.substring(26,32).trim();k.gh=l.substring(47,67<=l.length?67:l.length).trim();this.ia.Ji(k.lf,k);break;case "DBREF2":k.fh=l.substring(18,40).trim();k.hh=
l.substring(45,55).trim();k.ih=l.substring(57,67<=l.length?67:l.length).trim();break;case "MODRES":r=new Mk;r.name=l.substring(12,15).trim();t=l.charAt(16);q=l.substring(18,22).trim();x=" "!=l.charAt(22)?l.charAt(22):"\x00";r.vg=l.substring(24,27).trim();r.description=30<=l.length?l.substring(29).trim():null;this.ia.Vd.set(new Nk(t,q,x),r);break;case "HET":t=l.substring(7,10).trim();for(h in this.de)if(h[0]===t){r=h[1];break}null===r&&(r=new Ok,r.id=t,r.description=31<=l.length?l.substring(30):null,
this.de[t]=r);t=l.charAt(12);q=l.substring(13,17).trim();x=" "!=l.charAt(17)?l.charAt(17):"\x00";this.ia.Td.set(new Nk(t,q,x),r);break;case "HETNAM":t=l.substring(11,14).trim();r=this.de[t];r.name=null===r.name?l.substring(15):r.name+l.substring(15);break;case "HETSYN":t=l.substring(11,14).trim();this.Le[t]=void 0===this.Le[t]?l.substring(15):this.Le[t]+l.substring(15);break;case "FORMUL":t=l.substring(12,15).trim();r=this.de[t];r.qf=null===r.qf?l.substring(19):r.qf+l.substring(19);break;case "HELIX":t=
l.charAt(19);r=parseInt(l.substring(21,25));q=l.charAt(25);" "===q&&(q="\x00");h=parseInt(l.substring(33,37));r=parseInt(r);x=parseInt(h);for(h=r;h<=x;h++)this.ia.Ec.set(new Nk(t,h,q),F.u);break;case "SHEET":for(t=l.charAt(21),r=parseInt(l.substring(22,26)),q=l.charAt(26)," "===q&&(q="\x00"),h=parseInt(l.substring(33,37)),l=-1===parseInt(l.substring(38,40))?F.ea:F.v,r=parseInt(r),x=parseInt(h),h=r;h<=x;h++)this.ia.Ec.set(new Nk(t,h,q),l)}}this.finish();this.ready=!0}};
Jk.prototype.finish=function(){this.ia.Il(this.ia.Ai.concat(null));this.Yg=this.Ah=this.source=null;for(var e in this.Le){var f=this.de[e];f.Gj=f.Gj.concat(this.Le[e].split("\\s*;\\s*"))}this.Le=this.de=null;null==this.ia._id&&(this.ia.lc("Unknown_"+Lk),Lk++);this.zi.apply(this,[this.ia,this.xc])};function Mk(){this.description=this.vg=this.name=null}
function Pk(e){this.ia=null;this.xc=[];this.rh=!1;this.kf=null;this.Ka=[];this.zh=!1;this.vj=!0;this.Ij=[];this.le=[];this.rg=new Ca;null==e&&(e=!1);this.Ff=e}Pk.prototype.parse=function(e,f){this.ia=new dd;this.le[Kk.id]=Kk;var g=loadCIF(e,1);this.parseJSON(g);Pj(this.ia.Vd);Pj(this.ia.Ec);Pj(this.ia.Td);f.apply(this,[this.ia,this.xc])};function Qk(e,f,g){if(!e.rh){var h=f.split(".",2);null!==e.kf&&e.kf!==h[0]&&Rk(e);e.kf=h[0]}e.Ka[f]=g}function Rk(e){null!==e.kf&&(Sk(e),e.Ka=[],e.kf=null)}
function Tk(e,f){var g=parseInt(e.Ka[f]);isNaN(g)&&(g=0);return g}Pk.prototype.getFloatValue=function(e){e=parseFloat(this.Ka[e]);isNaN(e)&&(e=0);return e};Pk.prototype.getStringValue=function(e,f){var g=this.Ka[e];null==g&&null!=f&&(g=this.Ka[f]);if("."===g||"?"===g)return"\x00";void 0!==g&&(g=g.replace('"',""));return g};
function Sk(e){if(void 0!==e.Ka["_atom_site.id"]){var f=parseInt(e.Ka["_atom_site.pdbx_PDB_model_num"]);if(!(e.vj&&1<f)){var g=e.xc[f-1];void 0===g&&(g=[],e.xc[f-1]=g);if(!e.Ff||"CA"===e.getStringValue("_atom_site.label_atom_id")){var f=[],h=e.getStringValue("_atom_site.type_symbol");null!==h&"H"===h&&!e.zh||(f.push(e.getStringValue("_atom_site.group_PDB")),f.push(Tk(e,"_atom_site.id")),f.push(e.getStringValue("_atom_site.auth_atom_id","_atom_site.label_atom_id").replace(/"/g,"")),f.push(e.getStringValue("_atom_site.label_alt_id").replace(/"/g,
"")),f.push(e.getStringValue("_atom_site.auth_comp_id","_atom_site.label_comp_id")),f.push(e.getStringValue("_atom_site.auth_asym_id","_atom_site.label_asym_id")),f.push(Tk(e,"_atom_site.auth_seq_id")),f.push(e.getStringValue("_atom_site.pdbx_PDB_ins_code")),f.push(e.getFloatValue("_atom_site.Cartn_x")),f.push(e.getFloatValue("_atom_site.Cartn_y")),f.push(e.getFloatValue("_atom_site.Cartn_z")),f.push(e.getFloatValue("_atom_site.occupancy")),f.push(e.getFloatValue("_atom_site.B_iso_or_equiv")),f.push(e.getStringValue("_atom_site.type_symbol")),
f.push(Tk(e,"_atom_site.pdbx_formal_charge")),g.push(f))}}}else if(void 0!==e.Ka["_struct_keywords.entry_id"])e.ia.Yh(e.getStringValue("_struct_keywords.pdbx_keywords")),null!==e.getStringValue("_struct_keywords.text")&&e.getStringValue("_struct_keywords.text");else if(void 0!==e.Ka["_audit_author.name"])e.ia.wi.push(e.getStringValue("_audit_author.name"));else if(void 0!==e.Ka["_database_PDB_rev.num"])g=e.getStringValue("_database_PDB_rev.date_original"),null!==g&&e.ia.setDate(g);else if(void 0!==
e.Ka["_struct.entry_id"])e.ia.$h(e.getStringValue("_struct.title"));else if(void 0!==e.Ka["_refine.entry_id"])e.ia.Kl(e.getFloatValue("_refine.ls_d_res_high",NaN));else if(void 0!==e.Ka["_entity.id"])"polymer"===e.Ka["_entity.type"]&&(g=Tk(e,"_entity.id"));else if(void 0===e.Ka["_entity_poly.entity_id"]&&void 0===e.Ka["_entity_name_com.entity_id"])if(void 0!==e.Ka["_struct_ref.id"])g=Tk(e,"_struct_ref.id"),f=new Ik,e.Ij[g]=f,f.Qf=e.getStringValue("_struct_ref.db_name"),f.gh=e.getStringValue("_struct_ref.db_code"),
f.fh=e.getStringValue("_struct_ref.pdbx_db_accession");else if(void 0!==e.Ka["_struct_ref_seq.align_id"])g=Tk(e,"_struct_ref_seq.ref_id"),f=e.Ij[g],f.lf=e.getStringValue("_struct_ref_seq.pdbx_strand_id"),f.Wh=Tk(e,"_struct_ref_seq.seq_align_beg"),f.uh=e.getStringValue("_struct_ref_seq.pdbx_seq_align_beg_ins_code"),f.Xh=Tk(e,"_struct_ref_seq.seq_align_end"),f.vh=e.getStringValue("_struct_ref_seq.pdbx_seq_align_end_ins_code"),f.hh=Tk(e,"_struct_ref_seq.db_align_beg"),f.Yi=e.getStringValue("_struct_ref_seq.pdbx_db_align_beg_ins_code"),
f.ih=Tk(e,"_struct_ref_seq.db_align_end"),f.Zi=e.getStringValue("_struct_ref_seq.pdbx_db_align_end_ins_code");else if(void 0!==e.Ka["_pdbx_struct_mod_residue.id"]){f=new Mk;f.name=e.getStringValue("_pdbx_struct_mod_residue.auth_comp_id");f.vg=e.getStringValue("_pdbx_struct_mod_residue.parent_comp_id");f.description=e.getStringValue("_pdbx_struct_mod_residue.details");var g=e.getStringValue("_pdbx_struct_mod_residue.auth_asym_id"),h=Tk(e,"_pdbx_struct_mod_residue.auth_seq_id"),k=e.getStringValue("_pdbx_struct_mod_residue.PDB_ins_code");
e.ia.Vd.set(new Nk(g,h,k),f)}else if(void 0!==e.Ka["_pdbx_nonpoly_scheme.asym_id"])g=e.getStringValue("_pdbx_nonpoly_scheme.mon_id"),f=e.le[g],void 0===f&&(f=new Ok,f.id=g,e.le[g]=f),g=e.getStringValue("_pdbx_nonpoly_scheme.pdb_strand_id"),h=Tk(e,"_pdbx_nonpoly_scheme.pdb_seq_num"),k=e.getStringValue("_pdbx_nonpoly_scheme.pdb_ins_code"),e.ia.Td.set(new Nk(g,h,k),f);else if(void 0!==e.Ka["_chem_comp.id"])g=e.getStringValue("_chem_comp.id"),f=e.le[g],void 0!==f&&(f.name=e.getStringValue("_chem_comp.name"),
null!=e.getStringValue("_chem_comp.pdbx_synonyms")&&e.getStringValue("_chem_comp.pdbx_synonyms"),f.qf=e.getStringValue("_chem_comp.formula"));else if(void 0===e.Ka["_struct_conn.id"])if(void 0!==e.Ka["_struct_conf.id"]){e.getStringValue("_struct_conf.conf_type_id");var g=e.getStringValue("_struct_conf.beg_auth_asym_id"),m=Tk(e,"_struct_conf.beg_auth_seq_id"),f=e.getStringValue("_struct_conf.pdbx_beg_PDB_ins_code");e.getStringValue("_struct_conf.end_auth_asym_id");k=Tk(e,"_struct_conf.end_auth_seq_id");
e.getStringValue("_struct_conf.pdbx_end_PDB_ins_code");for(var l=parseInt(m),k=parseInt(k);l<=k;l++)e.ia.Ec.set(new Nk(g,l,f),F.u)}else if(void 0!==e.Ka["_struct_sheet_range.id"])for(h=F.v,g=e.getStringValue("_struct_sheet_range.beg_auth_asym_id"),m=Tk(e,"_struct_sheet_range.beg_auth_seq_id"),f=e.getStringValue("_struct_sheet_range.pdbx_beg_PDB_ins_code"),e.getStringValue("_struct_sheet_range.end_auth_asym_id"),k=Tk(e,"_struct_sheet_range.end_auth_seq_id"),e.getStringValue("_struct_sheet_range.pdbx_end_PDB_ins_code"),
l=e.getStringValue("_struct_sheet_range.id"),l=e.rg.get(new Nk(g,l,"0")),"anti-parallel"===l&&(h=F.ea),l=parseInt(m),k=parseInt(k);l<=k;l++)e.ia.Ec.set(new Nk(g,l,f),h);else void 0!==e.Ka["_struct_sheet_order.sheet_id"]&&(g=e.getStringValue("_struct_sheet_order.sheet_id"),e.getStringValue("_struct_sheet_order.range_id_1"),f=e.getStringValue("_struct_sheet_order.range_id_2"),l=e.getStringValue("_struct_sheet_order.sense"),e.rg.set(new Nk(g,f,"\x00"),l))}
Pk.prototype.parseJSON=function(e){for(var f in e){var g=e[f];this.ia.lc(g.entry.id[0]);var h=g,k=h.struct_keywords;Y(k.pdbx_keywords[0]);for(var m=0,l=k.text.length;m<l;m++)k=Y(k.text[m]).split("\\s*,\\s*");k=h.audit_author;m=0;for(l=k.name.length;m<l;m++)this.ia.wi.push(Y(k.name[m]));k=h.database_PDB_rev;m=0;for(l=k.num.length;m<l;m++){var q=Y(k.date_original[m]);null!==q&&this.ia.setDate(q)}this.ia.$h(Y(h.struct.title[0]));h=h.entity;m=k=0;for(l=h.formula_weight.length;m<l;m++)k+=Uk(h.formula_weight[m]);
this.ia.Ml(k);m=g.atom_site;l=0;for(h=m.id.length;l<h;l++){q=parseInt(m.pdbx_PDB_model_num[l]);if(this.vj&&1<q)break;k=this.xc[q-1];void 0===k&&(k=[],this.xc[q-1]=k);if(this.Ff&&"CA"!==m.label_atom_id[l])break;var q=[],r=m.type_symbol[l];null!==r&"H"===r&&!this.zh||(q.push(Y(m.group_PDB[l])),q.push(Vk(m.id[l])),q.push(Y(m.auth_atom_id[l],m.label_atom_id[l]).replace(/"/g,"")),q.push(Y(m.label_alt_id[l].replace(/"/g,""))),q.push(Y(m.auth_comp_id[l],m.label_comp_id[l])),q.push(Y(m.auth_asym_id[l],m.label_asym_id[l])),
q.push(Vk(m.auth_seq_id[l])),q.push(Y(m.pdbx_PDB_ins_code[l])),q.push(Uk(m.Cartn_x[l])),q.push(Uk(m.Cartn_y[l])),q.push(Uk(m.Cartn_z[l])),q.push(Uk(m.occupancy[l])),q.push(Uk(m.B_iso_or_equiv[l])),q.push(Y(m.type_symbol[l])),q.push(Vk(m.pdbx_formal_charge[l])),k.push(q))}m=g.pdbx_struct_mod_residue;if(null!=m)for(l=0,h=m.id.length;l<h;l++){k=new Mk;k.name=Y(m.auth_comp_id[l]);k.vg=Y(m.parent_comp_id[l]);k.description=Y(m.details[l]);var q=Y(m.auth_asym_id[l]),r=Vk(m.auth_seq_id[l]),t=Y(m.PDB_ins_code[l]);
this.ia.Vd.set(new Nk(q,r,t),k)}m=g.pdbx_nonpoly_scheme;if(null!=m)for(l=0,h=m.asym_id.length;l<h;l++)q=Y(m.mon_id[l]),k=this.le[q],void 0===k&&(k=new Ok,k.id=q,this.le[q]=k),q=Y(m.pdb_strand_id[l]),r=Vk(m.pdb_seq_num[l]),t=Y(m.pdb_ins_code[l]),this.ia.Td.set(new Nk(q,r,t),k);m=g.chem_comp;if(null!=m)for(l=0,h=m.id.length;l<h;l++)k=Y(m.id[l]),k=this.le[k],void 0!==k&&(k.name=Y(m.name[l]),null!=Y(m.pdbx_synonyms[l])&&Y(m.pdbx_synonyms[l]),k.qf=Y(m.formula[l]));m=g.struct_conf;if(null!=m)for(l=0,h=
m.id.length;l<h;l++)for(Y(m.conf_type_id[l]),k=Y(m.beg_auth_asym_id[l]),r=Vk(m.beg_auth_seq_id[l]),q=Y(m.pdbx_beg_PDB_ins_code[l]),Y(m.end_auth_asym_id[l]),t=Vk(m.end_auth_seq_id[l]),Y(m.pdbx_end_PDB_ins_code[l]),t=parseInt(t),r=parseInt(r);r<=t;r++)this.ia.Ec.set(new Nk(k,r,q),F.u);m=g.struct_sheet_order;if(null!=m)for(l=0,h=m.sheet_id.length;l<h;l++)k=Y(m.sheet_id[l]),Y(m.range_id_1[l]),q=Y(m.range_id_2[l]),r=Y(m.sense[l]),this.rg.set(new Nk(k,q,"\x00"),r);g=g.struct_sheet_range;if(null!=g)for(m=
0,l=g.id.length;m<l;m++){h=F.v;k=Y(g.beg_auth_asym_id[m]);r=Vk(g.beg_auth_seq_id[m]);q=Y(g.pdbx_beg_PDB_ins_code[m]);Y(g.end_auth_asym_id[m]);t=Vk(g.end_auth_seq_id[m]);Y(g.pdbx_end_PDB_ins_code[m]);var x=Y(g.id[m]);"anti-parallel"===this.rg.get(new Nk(k,x,"0"))&&(h=F.ea);t=parseInt(t);for(r=parseInt(r);r<=t;r++)this.ia.Ec.set(new Nk(k,r,q),h)}}};function Vk(e){e=parseInt(e);isNaN(e)&&(e=0);return e}function Uk(e){e=parseFloat(e);isNaN(e)&&(e=0);return e}
function Y(e,f){var g=e;null==g&&null!=defaultTag&&(g=f);if("."===g||"?"===g)return"\x00";void 0!==g&&(g=g.replace('"',""));return g}function Nk(e,f,g){null===e&&console.warn("chainId null in Residue.Id");this.Vb=e;this.vb=f;this.Xb=g;this.toString=function(){return"\x00"!==this.Xb.charCodeAt(0)?this.Vb+":"+this.vb+":"+this.Xb:this.Vb+":"+this.vb};this.Bb=function(){return"\x00"!==this.Xb.charCodeAt(0)?this.Vb+":"+this.vb+":"+this.Xb:this.Vb+":"+this.vb}}
onmessage=function(e){function f(e,f){postMessage(JSON.stringify(e));postMessage(JSON.stringify(f))}var g=e.data[0],h=e.data[2],k;k=e.data[1]?new Pk:new Jk;if(h)k.parse(g,f);else{var m=new XMLHttpRequest;m.open("GET",g,!0);m.onreadystatechange=function(){var e=m.status;if(4==m.readyState)if(200==e)postMessage(new Blob([m.responseText],{type:"text/plain"})),k.parse(m.responseText,f);else{var h={type:"error",msg:""};switch(e){case 404:h.msg="File not found, "+g;break;case 500:h.msg="Server error";break;
case 0:h.msg="Request aborted";break;default:h.msg="Unknown error "+e}postMessage(JSON.stringify(h))}};m.send(null)}};function Ok(){this.name=this.id=null;this.Gj=[];this.description=this.qf=null}var Kk=new Ok;Kk.id="HOH";Kk.name="WATER";F=function(e,f){this.name=e;this.code=f};F.ca=new F("Coil"," ");F.ja=new F("Turn","T");F.u=new F("Helix","H");F.v=new F("Strand","x");F.ea=new F("Strand","X");tc={G:F.u,H:F.u,I:F.u,B:F.v,E:F.v,T:F.ja,S:F.ca,C:F.ca,X:F.ca};F.prototype.toString=function(){return name};
(function(){function e(f,g,h,k){this.message=f;this.location=k;this.name="SyntaxError";"function"===typeof Error.captureStackTrace&&Error.captureStackTrace(this,e)}(function(e,g){function h(){this.constructor=e}h.prototype=g.prototype;e.prototype=new h})(e,Error);return{SyntaxError:e,parse:function(f,g){function h(e){var g=vb[e],h,k;if(g)return g;for(h=e-1;!vb[h];)h--;g=vb[h];for(g={line:g.line,rb:g.rb,ec:g.ec};h<e;)k=f.charAt(h),"\n"===k?(g.ec||g.line++,g.rb=1,g.ec=!1):"\r"===k||"\u2028"===k||"\u2029"===
k?(g.line++,g.rb=1,g.ec=!0):(g.rb++,g.ec=!1),h++;return vb[e]=g}function k(e,f){var g=h(e),k=h(f);return{start:{offset:e,line:g.line,rb:g.rb},end:{offset:f,line:k.line,rb:k.rb}}}function m(e){A<ja||(A>ja&&(ja=A,Zb=[]),Zb.push(e))}function l(){var e,g,h,k,m,l,n;e=Q();if(e===y&&(e=P(),e===y))if(e=A,g=q(),g!==y){h=A;k=[];m=A;l=P();l!==y?(n=q(),n!==y?m=l=[l,n]:(A=m,m=y)):(A=m,m=y);for(;m!==y;)k.push(m),m=A,l=P(),l!==y?(n=q(),n!==y?m=l=[l,n]:(A=m,m=y)):(A=m,m=y);h=k!==y?f.substring(h,A):k;if(h!==y){k=
[];for(m=P();m!==y;)k.push(m),m=P();k!==y?e=g=[g,h,k]:(A=e,e=y)}else A=e,e=y}else A=e,e=y;return e}function q(){var e,g,h,k,l,n;k=h=g=e=A;var q,w,x,B,E;n=l=A;Mc.test(f.charAt(A))?(q=f.charAt(A),A++):(q=y,0===J&&m(kc));q===y&&(Db.test(f.charAt(A))?(q=f.charAt(A),A++):(q=y,0===J&&m(lc)));q!==y?(La.test(f.charAt(A))?(w=f.charAt(A),A++):(w=y,0===J&&m(Xa)),w===y&&(gb.test(f.charAt(A))?(w=f.charAt(A),A++):(w=y,0===J&&m(fa))),w!==y?(pa.test(f.charAt(A))?(x=f.charAt(A),A++):(x=y,0===J&&m(la)),x===y&&(Da.test(f.charAt(A))?
(x=f.charAt(A),A++):(x=y,0===J&&m(Eb))),x!==y?(La.test(f.charAt(A))?(B=f.charAt(A),A++):(B=y,0===J&&m(Xa)),B===y&&(gb.test(f.charAt(A))?(B=f.charAt(A),A++):(B=y,0===J&&m(fa))),B!==y?(qb.test(f.charAt(A))?(E=f.charAt(A),A++):(E=y,0===J&&m(ra)),E!==y?n=q=[q,w,x,B,E]:(A=n,n=y)):(A=n,n=y)):(A=n,n=y)):(A=n,n=y)):(A=n,n=y);l=n!==y?f.substring(l,A):n;k=l!==y?f.substring(k,A):l;if(k!==y){l=A;k=[];n=D();if(n!==y)for(;n!==y;)k.push(n),n=D();else k=y;l=k!==y?f.substring(l,A):k;l!==y?(Z.pe.ia.lc(l),h=void 0):
(A=h,h=y)}else A=h,h=y;g=h!==y?f.substring(g,A):h;if(g!==y){h=[];k=A;l=P();l!==y?(n=t(),n===y&&(n=r()),n!==y?k=l=[l,n]:(A=k,k=y)):(A=k,k=y);for(;k!==y;)h.push(k),k=A,l=P(),l!==y?(n=t(),n===y&&(n=r()),n!==y?k=l=[l,n]:(A=k,k=y)):(A=k,k=y);h!==y?e=g=[g,h]:(A=e,e=y)}else A=e,e=y;return e}function r(){var e,g,h,k,m,l;g=e=A;h=Tb();h!==y?(k=A,m=D(),k=m!==y?f.substring(k,A):m,k!==y?g=h=[h,k]:(A=g,g=y)):(A=g,g=y);if(g!==y){h=[];k=A;m=P();m!==y?(l=t(),l!==y?k=m=[m,l]:(A=k,k=y)):(A=k,k=y);if(k!==y)for(;k!==
y;)h.push(k),k=A,m=P(),m!==y?(l=t(),l!==y?k=m=[m,l]:(A=k,k=y)):(A=k,k=y);else h=y;h!==y?(k=P(),k!==y?(m=Tb(),m!==y?e=g=[g,h,k,m]:(A=e,e=y)):(A=e,e=y)):(A=e,e=y)}else A=e,e=y;return e}function t(){var e,g,h,k;e=A;g=Hb();g!==y&&(g=Z.pe,Rk(g),g.rh=!0,Z.Fh=[],Z.i=0,g=void 0);if(g!==y){h=[];g=x();if(g!==y)for(;g!==y;)h.push(g),g=x();else h=y;if(h!==y){g=[];for(h=w();h!==y;)g.push(h),h=w();g!==y?(e=Z.pe,e.rh=!1,e.Ka=[],e=void 0):(A=e,e=y)}else A=e,e=y}else A=e,e=y;e===y&&(g=e=A,h=aa(),g=h!==y?f.substring(g,
A):h,g!==y?(h=P(),h!==y?(h=A,k=oa(),h=k!==y?f.substring(h,A):k,h!==y?(Qk(Z.pe,g,h),e=void 0):(A=e,e=y)):(A=e,e=y)):(A=e,e=y));return e}function x(){var e,f;e=A;f=P();f!==y?(f=aa(),f!==y?(Z.Fh.push(f),e=void 0):(A=e,e=y)):(A=e,e=y);return e}function w(){var e,f,g;e=A;f=P();f!==y?(g=A,J++,f=Hb(),J--,f===y?g=void 0:(A=g,g=y),g!==y?(f=oa(),f!==y?(e=Z.Fh.length,Qk(Z.pe,Z.Fh[Z.i%e],f),Z.i++,0===Z.i%e&&Sk(Z.pe),e=void 0):(A=e,e=y)):(A=e,e=y)):(A=e,e=y);return e}function B(){var e;Ab.test(f.charAt(A))?(e=
f.charAt(A),A++):(e=y,0===J&&m(wc));return e}function D(){var e;e=B();e===y&&(e=I(),e===y&&(cb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&m(ta)),e===y&&(e=H(),e===y&&(Bb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&m(hd)),e===y&&(91===f.charCodeAt(A)?(e=Ub,A++):(e=y,0===J&&m(db)),e===y&&(93===f.charCodeAt(A)?(e=pb,A++):(e=y,0===J&&m(eb))))))));return e}function E(){var e;e=B();e===y&&(e=I(),e===y&&(cb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&m(ta)),e===y&&(e=H(),e===y&&(qb.test(f.charAt(A))?
(e=f.charAt(A),A++):(e=y,0===J&&m(ra)),e===y&&(e=ga(),e===y&&(e=da(),e===y&&(91===f.charCodeAt(A)?(e=Ub,A++):(e=y,0===J&&m(db)),e===y&&(93===f.charCodeAt(A)?(e=pb,A++):(e=y,0===J&&m(eb))))))))));return e}function I(){var e;34===f.charCodeAt(A)?(e=fb,A++):(e=y,0===J&&m(Pa));return e}function H(){var e;39===f.charCodeAt(A)?(e=rb,A++):(e=y,0===J&&m(Cb));return e}function K(){var e;e=B();e===y&&(cb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&m(ta)),e===y&&(95===f.charCodeAt(A)?(e=Qa,A++):(e=y,0===
J&&m(qa)),e===y&&(e=ga(),e===y&&(e=da(),e===y&&(91===f.charCodeAt(A)?(e=Ub,A++):(e=y,0===J&&m(db)),e===y&&(59===f.charCodeAt(A)?(e=O,A++):(e=y,0===J&&m(S)),e===y&&(93===f.charCodeAt(A)?(e=pb,A++):(e=y,0===J&&m(eb)),e===y&&(e=H(),e===y&&(e=I())))))))));return e}function G(){var e;e=B();e===y&&(cb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&m(ta)),e===y&&(95===f.charCodeAt(A)?(e=Qa,A++):(e=y,0===J&&m(qa)),e===y&&(e=ga(),e===y&&(e=da(),e===y&&(91===f.charCodeAt(A)?(e=Ub,A++):(e=y,0===J&&m(db)),
e===y&&(59===f.charCodeAt(A)?(e=O,A++):(e=y,0===J&&m(S)),e===y&&(93===f.charCodeAt(A)?(e=pb,A++):(e=y,0===J&&m(eb)),e===y&&(e=I()))))))));return e}function L(){var e;e=B();e===y&&(cb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&m(ta)),e===y&&(95===f.charCodeAt(A)?(e=Qa,A++):(e=y,0===J&&m(qa)),e===y&&(e=ga(),e===y&&(e=da(),e===y&&(91===f.charCodeAt(A)?(e=Ub,A++):(e=y,0===J&&m(db)),e===y&&(59===f.charCodeAt(A)?(e=O,A++):(e=y,0===J&&m(S)),e===y&&(93===f.charCodeAt(A)?(e=pb,A++):(e=y,0===J&&m(eb)),
e===y&&(e=H()))))))));return e}function P(){var e,g,h;e=A;g=[];h=V();h===y&&(h=ga(),h===y&&(h=da(),h===y&&(h=wa())));if(h!==y)for(;h!==y;)g.push(h),h=V(),h===y&&(h=ga(),h===y&&(h=da(),h===y&&(h=wa())));else g=y;return e=g!==y?f.substring(e,A):g}function Q(){var e,g,h,k,l,n;e=A;g=[];h=A;35===f.charCodeAt(A)?(k=sb,A++):(k=y,0===J&&m(Ka));if(k!==y){l=[];for(n=K();n!==y;)l.push(n),n=K();l!==y?(n=wa(),n===y&&(n=Ib()),n!==y?h=k=[k,l,n]:(A=h,h=y)):(A=h,h=y)}else A=h,h=y;if(h!==y)for(;h!==y;)if(g.push(h),
h=A,35===f.charCodeAt(A)?(k=sb,A++):(k=y,0===J&&m(Ka)),k!==y){l=[];for(n=K();n!==y;)l.push(n),n=K();l!==y?(n=wa(),n===y&&(n=Ib()),n!==y?h=k=[k,l,n]:(A=h,h=y)):(A=h,h=y)}else A=h,h=y;else g=y;return e=g!==y?f.substring(e,A):g}function V(){var e,f,g;e=A;f=[];g=ga();g===y&&(g=da(),g===y&&(g=wa()));if(g!==y)for(;g!==y;)f.push(g),g=ga(),g===y&&(g=da(),g===y&&(g=wa()));else f=y;f!==y?(g=Q(),g!==y?e=f=[f,g]:(A=e,e=y)):(A=e,e=y);return e}function aa(){var e,g,h,k,l;g=e=A;95===f.charCodeAt(A)?(h=Qa,A++):(h=
y,0===J&&m(qa));if(h!==y){k=[];l=D();if(l!==y)for(;l!==y;)k.push(l),l=D();else k=y;k!==y?g=h=[h,k]:(A=g,g=y)}else A=g,g=y;return e=g!==y?f.substring(e,A):g}function oa(){var e,g;e=A;var h,k,l,n,q,r,t,w,x;g=A;59===f.charCodeAt(A)?(h=O,A++):(h=y,0===J&&m(S));if(h!==y){k=[];for(l=K();l!==y;)k.push(l),l=K();if(k!==y)if(l=wa(),l!==y){n=[];r=q=A;t=E();if(t!==y){w=[];for(x=K();x!==y;)w.push(x),x=K();w!==y?r=t=[t,w]:(A=r,r=y)}else A=r,r=y;r===y&&(r=null);r!==y?(t=wa(),t!==y?q=r=[r,t]:(A=q,q=y)):(A=q,q=y);
for(;q!==y;){n.push(q);r=q=A;t=E();if(t!==y){w=[];for(x=K();x!==y;)w.push(x),x=K();w!==y?r=t=[t,w]:(A=r,r=y)}else A=r,r=y;r===y&&(r=null);r!==y?(t=wa(),t!==y?q=r=[r,t]:(A=q,q=y)):(A=q,q=y)}n!==y?(59===f.charCodeAt(A)?(q=O,A++):(q=y,0===J&&m(S)),q!==y?g=h=[h,k,l,n,q]:(A=g,g=y)):(A=g,g=y)}else A=g,g=y;else A=g,g=y}else A=g,g=y;e=g!==y?f.substring(e,A):g;if(e===y){h=g=e=A;k=I();if(k!==y){l=[];for(n=L();n!==y;)l.push(n),n=L();l!==y?(n=I(),n!==y?h=k=[k,l,n]:(A=h,h=y)):(A=h,h=y)}else A=h,h=y;g=h!==y?f.substring(g,
A):h;if(g===y){g=A;h=H();if(h!==y){k=[];l=G();l===y&&(l=A,n=H(),n!==y?(q=A,J++,r=P(),J--,r===y?q=void 0:(A=q,q=y),q!==y?l=n=[n,q]:(A=l,l=y)):(A=l,l=y));for(;l!==y;)k.push(l),l=G(),l===y&&(l=A,n=H(),n!==y?(q=A,J++,r=P(),J--,r===y?q=void 0:(A=q,q=y),q!==y?l=n=[n,q]:(A=l,l=y)):(A=l,l=y));k!==y?(l=H(),l!==y?g=h=[h,k,l]:(A=g,g=y)):(A=g,g=y)}else A=g,g=y;if(g===y)if(g=A,h=B(),h!==y){k=A;l=[];for(n=D();n!==y;)l.push(n),n=D();k=l!==y?f.substring(k,A):l;k!==y?g=h=[h,k]:(A=g,g=y)}else A=g,g=y}e=g!==y?f.substring(e,
A):g;e===y&&(e=A,Vb.test(f.charAt(A))?(g=f.charAt(A),A++):(g=y,0===J&&m(Lc)),e=g!==y?f.substring(e,A):g,e===y&&(e=A,jc.test(f.charAt(A))?(g=f.charAt(A),A++):(g=y,0===J&&m(Wb)),e=g!==y?f.substring(e,A):g))}return e}function Hb(){var e,g,h,k,l,n,q;g=e=A;tb.test(f.charAt(A))?(h=f.charAt(A),A++):(h=y,0===J&&m(ub));h===y&&(Ma.test(f.charAt(A))?(h=f.charAt(A),A++):(h=y,0===J&&m(Fb)));h!==y?(sa.test(f.charAt(A))?(k=f.charAt(A),A++):(k=y,0===J&&m(Ra)),k===y&&(ma.test(f.charAt(A))?(k=f.charAt(A),A++):(k=y,
0===J&&m(Ya))),k!==y?(sa.test(f.charAt(A))?(l=f.charAt(A),A++):(l=y,0===J&&m(Ra)),l===y&&(ma.test(f.charAt(A))?(l=f.charAt(A),A++):(l=y,0===J&&m(Ya))),l!==y?(ua.test(f.charAt(A))?(n=f.charAt(A),A++):(n=y,0===J&&m(hb)),n===y&&(xc.test(f.charAt(A))?(n=f.charAt(A),A++):(n=y,0===J&&m(yc))),n!==y?(qb.test(f.charAt(A))?(q=f.charAt(A),A++):(q=y,0===J&&m(ra)),q!==y?g=h=[h,k,l,n,q]:(A=g,g=y)):(A=g,g=y)):(A=g,g=y)):(A=g,g=y)):(A=g,g=y);return e=g!==y?f.substring(e,A):g}function Tb(){var e,g,h,k,l,n,q;g=e=A;
Xb.test(f.charAt(A))?(h=f.charAt(A),A++):(h=y,0===J&&m(xa));h===y&&(na.test(f.charAt(A))?(h=f.charAt(A),A++):(h=y,0===J&&m(ya)));h!==y?(La.test(f.charAt(A))?(k=f.charAt(A),A++):(k=y,0===J&&m(Xa)),k===y&&(gb.test(f.charAt(A))?(k=f.charAt(A),A++):(k=y,0===J&&m(fa))),k!==y?(Nc.test(f.charAt(A))?(l=f.charAt(A),A++):(l=y,0===J&&m(Ea)),l===y&&(Kb.test(f.charAt(A))?(l=f.charAt(A),A++):(l=y,0===J&&m(Oc))),l!==y?(Pc.test(f.charAt(A))?(n=f.charAt(A),A++):(n=y,0===J&&m(Yb)),n===y&&(Sa.test(f.charAt(A))?(n=f.charAt(A),
A++):(n=y,0===J&&m(Na))),n!==y?(qb.test(f.charAt(A))?(q=f.charAt(A),A++):(q=y,0===J&&m(ra)),q!==y?g=h=[h,k,l,n,q]:(A=g,g=y)):(A=g,g=y)):(A=g,g=y)):(A=g,g=y)):(A=g,g=y);return e=g!==y?f.substring(e,A):g}function ga(){var e;32===f.charCodeAt(A)?(e=mc,A++):(e=y,0===J&&m(zc));return e}function da(){var e;9===f.charCodeAt(A)?(e=nc,A++):(e=y,0===J&&m(ib));return e}function wa(){var e;10===f.charCodeAt(A)?(e=Lb,A++):(e=y,0===J&&m(Za));e===y&&(13===f.charCodeAt(A)?(e=Mb,A++):(e=y,0===J&&m(oc)),e===y&&(f.substr(A,
2)===Gb?(e=Gb,A+=2):(e=y,0===J&&m(va))));return e}function Ib(){var e,g;e=A;J++;f.length>A?(g=f.charAt(A),A++):(g=y,0===J&&m(Ta));J--;g===y?e=void 0:(A=e,e=y);return e}this.pe=g;var Z=this,n=1<arguments.length?arguments[1]:{},y={},Jb={start:l},ea=l,Ab=/^[a-zA-Z0-9!%&*()+,-.\/:<=>?@\^`{|}~\\]/,wc={type:"class",value:"[a-zA-Z0-9!%&*()+,-\\./:<=>?@\\^`{|}~\\\\]",description:"[a-zA-Z0-9!%&*()+,-\\./:<=>?@\\^`{|}~\\\\]"},cb=/^[#$]/,ta={type:"class",value:"[#$]",description:"[#$]"},Bb=/^[_;']/,hd={type:"class",
value:"[_;']",description:"[_;']"},Ub="[",db={type:"literal",value:"[",description:'"["'},pb="]",eb={type:"literal",value:"]",description:'"]"'},qb=/^[_]/,ra={type:"class",value:"[_]",description:"[_]"},fb='"',Pa={type:"literal",value:'"',description:'"\\""'},rb="'",Cb={type:"literal",value:"'",description:'"\'"'},Qa="_",qa={type:"literal",value:"_",description:'"_"'},O=";",S={type:"literal",value:";",description:'";"'},sb="#",Ka={type:"literal",value:"#",description:'"#"'},Vb=/^[.]/,Lc={type:"class",
value:"[.]",description:"[.]"},jc=/^[?]/,Wb={type:"class",value:"[?]",description:"[?]"},Mc=/^[D]/,kc={type:"class",value:"[D]",description:"[D]"},Db=/^[d]/,lc={type:"class",value:"[d]",description:"[d]"},La=/^[A]/,Xa={type:"class",value:"[A]",description:"[A]"},gb=/^[a]/,fa={type:"class",value:"[a]",description:"[a]"},pa=/^[T]/,la={type:"class",value:"[T]",description:"[T]"},Da=/^[t]/,Eb={type:"class",value:"[t]",description:"[t]"},tb=/^[L]/,ub={type:"class",value:"[L]",description:"[L]"},Ma=/^[l]/,
Fb={type:"class",value:"[l]",description:"[l]"},sa=/^[O]/,Ra={type:"class",value:"[O]",description:"[O]"},ma=/^[o]/,Ya={type:"class",value:"[o]",description:"[o]"},ua=/^[P]/,hb={type:"class",value:"[P]",description:"[P]"},xc=/^[p]/,yc={type:"class",value:"[p]",description:"[p]"},Xb=/^[S]/,xa={type:"class",value:"[S]",description:"[S]"},na=/^[s]/,ya={type:"class",value:"[s]",description:"[s]"},Nc=/^[V]/,Ea={type:"class",value:"[V]",description:"[V]"},Kb=/^[v]/,Oc={type:"class",value:"[v]",description:"[v]"},
Pc=/^[E]/,Yb={type:"class",value:"[E]",description:"[E]"},Sa=/^[e]/,Na={type:"class",value:"[e]",description:"[e]"},mc=" ",zc={type:"literal",value:" ",description:'" "'},nc="\t",ib={type:"literal",value:"\t",description:'"\\t"'},Lb="\n",Za={type:"literal",value:"\n",description:'"\\n"'},Mb="\r",oc={type:"literal",value:"\r",description:'"\\r"'},Gb="\r\n",va={type:"literal",value:"\r\n",description:'"\\r\\n"'},Ta={type:"any",description:"any character"},A=0,vb=[{line:1,rb:1,ec:!1}],ja=0,Zb=[],J=0,
za;if("startRule"in n){if(!(n.wf in Jb))throw Error("Can't start parsing from rule \""+n.wf+'".');ea=Jb[n.wf]}za=ea();if(za!==y&&A===f.length)return za;za!==y&&A<f.length&&m({type:"end",description:"end of input"});throw function(f,g,h,k){function l(e){var f=1;for(e.sort(function(e,f){return e.description<f.description?-1:e.description>f.description?1:0});f<e.length;)e[f-1]===e[f]?e.splice(f,1):f++}function m(e,f){function g(e){function f(e){return e.charCodeAt(0).toString(16).toUpperCase()}return e.replace(/\\/g,
"\\\\").replace(/"/g,'\\"').replace(/\x08/g,"\\b").replace(/\t/g,"\\t").replace(/\n/g,"\\n").replace(/\f/g,"\\f").replace(/\r/g,"\\r").replace(/[\x00-\x07\x0B\x0E\x0F]/g,function(e){return"\\x0"+f(e)}).replace(/[\x10-\x1F\x80-\xFF]/g,function(e){return"\\x"+f(e)}).replace(/[\u0100-\u0FFF]/g,function(e){return"\\u0"+f(e)}).replace(/[\u1000-\uFFFF]/g,function(e){return"\\u"+f(e)})}var h=Array(e.length),k;for(k=0;k<e.length;k++)h[k]=e[k].description;h=1<e.length?h.slice(0,-1).join(", ")+" or "+h[e.length-
1]:h[0];k=f?'"'+g(f)+'"':"end of input";return"Expected "+h+" but "+k+" found."}null!==g&&l(g);return new e(null!==f?f:m(g,h),0,0,k)}(null,Zb,ja<f.length?f.charAt(ja):null,ja<f.length?k(ja,ja+1):k(ja,ja));}}})();
}(biovizWorkerNamespace));