var biovizWorkerNamespace = {};
(function(ns) {
importScripts('library/polyfill.js', 'library/cif.js');
var z,ba=[];function ha(e){return function(){return ba[e].apply(this,arguments)}}var ia="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"===typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e},Ca=function la(){if(this.constructor===la)throw Error("Can't instanciate abstract class BiovizMap");};z=Ca.prototype;z.set=function(){throw Error("Trying to call an abstract method");};
z.get=function(){throw Error("Trying to call an abstract method");};z.remove=function(){throw Error("Trying to call an abstract method");};z.bd=function(){throw Error("Trying to call an abstract method");};z.keys=function(){throw Error("Trying to call an abstract method");};z.values=function(){throw Error("Trying to call an abstract method");};z.clear=function(){throw Error("Trying to call an abstract method");};z.Jd=ha(2);function Fa(){Ca.call(this);this.la=new Map;this.vd=new Map}Fa.prototype=Object.create(Ca.prototype);
z=Fa.prototype;z.constructor=Fa;z.set=function(e,f){var g=Ja(e);this.la.set(g,f);this.vd.set(g,e)};z.get=function(e){e=Ja(e);return this.bd(e)?this.la.get(e):null};z.remove=function(e){e=Ja(e);if(this.bd(e)){var f=this.la.get(e);this.la["delete"](e);this.vd["delete"](e);return f}return null};z.bd=function(e){e=Ja(e);return this.la.has(e)};
z.keys=function(){var e=[],f=!0,g=!1,h=void 0;try{for(var k=this.la.keys()[Symbol.iterator](),m;!(f=(m=k.next()).done);f=!0)e.push(m.value)}catch(l){g=!0,h=l}finally{try{!f&&k["return"]&&k["return"]()}finally{if(g)throw h;}}return e};z.values=function(){var e=[],f=!0,g=!1,h=void 0;try{for(var k=this.la.values()[Symbol.iterator](),m;!(f=(m=k.next()).done);f=!0)e.push(m.value)}catch(l){g=!0,h=l}finally{try{!f&&k["return"]&&k["return"]()}finally{if(g)throw h;}}return e};
z.clear=function(){this.la.clear();this.vd.clear()};z.Jd=ha(1);function Ja(e){if(e instanceof Array){e=[];for(var f=e.length,g=0;g<f;g++)e.push(e[g].Fb());return e.join("")}return e instanceof Object?e.Fb():e}function Ka(){Ca.call(this);this.la=[]}function Pa(e,f){this.key=e;this.value=f}Ka.prototype=Object.create(Ca.prototype);z=Ka.prototype;z.constructor=Ka;
z.set=function(e,f){if(void 0===e)throw"ERROR: key cannot be undefined";var g;a:if(void 0!==e.zf)g=this.la[e.zf];else{for(g in this.la)if(this.la[g].key===e){g=this.la[g];break a}g=void 0}void 0===g?"object"===("undefined"===typeof e?"undefined":ia(e))&&(e.zf=this.la.push(new Pa(e,f))-1):g.value=f};z.get=function(e){if(void 0!==e.zf)return this.la[e.zf].value;for(var f in this.la)if(this.la[f].key===e)return this.la[f].value};z.keys=function(){var e=[],f;for(f in this.la)e.push(this.la[f].key);return e};
z.bd=function(e){return-1!==this.keys().indexOf(e)};z.values=function(){var e=[],f;for(f in this.la)e.push(this.la[f].value);return e};z.remove=function(e){var f=-1,g;for(g in this.la)if(this.la[g].key===e){f=g;break}return 0<=f?this.la.splice(f,1)[0].value:null};z.clear=function(){this.la=[]};z.Jd=ha(0);

function Va(e){e.la=new Map(JSON.parse(e.la));e.vd=new Map(JSON.parse(e.vd))}function $a(){this.pos=new THREE.Vector3;this.ca=this.Oa=this.ec=this.u=this.v=this.vc=this.ea=this.symbol=this.ya=this.ka=this.zd=this.name=this.id=this.type=null}z=$a.prototype;z.ta=function(){return this.id};z.Aa=function(){return this.Oa};function ab(e,f){e.u!==f&&(e.u=f,null!==e.Oa&&e.Oa.qc(f))}z.Ya=function(){return this.pos};
z.zc=function(){if(null===this.ca){var e=parseFloat(jb(this.symbol)[7]),f=new THREE.Vector3(-e,-e,-e),e=new THREE.Vector3(e,e,e);this.ca=new ob(f,e)}return this.ca};z.radius=function(){return parseFloat(jb(this.symbol)[7])};z.Bb=function(){return this.ec};function wb(e,f){if(e.ec!==f&&(e.ec=f,null!=e.Oa)){var g=e.Oa,h=e.ec;if(g.ec!=h){g.ec=h;for(var k=g.u.length,m=0;m<k;m++)wb(g.u[m],h)}}}z.xb=function(){return this.vc};z.af=function(e){this.vc!=e&&(this.vc=e,null!==this.Oa&&this.Oa.af(e))};
z.dg=function(){return this.v};z.me=function(e){this.v!==e&&(this.v=e,null!==this.Oa&&this.Oa.me(e))};z.toString=function(){return this.symbol+":"+this.id};z.$b=function(){return this.Oa.$b()+":"+this.toString()};z.Fb=function(){return this.symbol+":"+this.id+":"+this.v};z.distanceTo=function(e){return e instanceof $a?this.pos.distanceTo(e.pos):this.pos.distanceTo(e)};z.distanceToSquared=function(e){return e instanceof $a?this.pos.distanceToSquared(e.pos):this.pos.distanceToSquared(e)};
z.sub=function(e){return e instanceof $a?new THREE.Vector3(this.pos.x-e.pos.x,this.pos.y-e.pos.y,this.pos.z-e.pos.z):new THREE.Vector3(this.pos.x-e.x,this.pos.y-e.y,this.pos.z-e.z)};z.add=function(e){return e instanceof $a?new THREE.Vector3(this.pos.x+e.pos.x,this.pos.y+e.pos.y,this.pos.z+e.pos.z):new THREE.Vector3(this.pos.x+e.x,this.pos.y+e.y,this.pos.z+e.z)};z.clone=function(){return new THREE.Vector3(this.pos.x,this.pos.y,this.pos.z)};
function xb(){this.ka=null;this.u=new yb;this.ca=[];this.ya=this.v=this.ea=null}z=xb.prototype;z.Bc=function(){return this.ka};z.bf=function(e){this.ka=e;e=this.ca.length;for(var f=0;f<e;f++)f.bf(this.ka)};z.add=function(e){if(e instanceof $a)return e=this.u.Sf(e),Mb(this),e;e instanceof Rb?((null!==e.Kb&&e.Kb!==this||e.Kb===this)&&console.warn("ERROR: ",e,"already belongs to",e.Kb),null===e.Kb&&(this.ca.push(e),e.bf(this.ka),e.Kb=this,Mb(this))):console.warn("ERROR : a is not an atom or a molecule")};
z.remove=function(e){e instanceof $a?(e=this.u.findNode(atom),-1<e&&(delete this.u[e],Mb(this))):e instanceof Rb&&(null===molecule&&console.warn("molecule null in function remove in model"),molecule.Kb===this&&(this.ca.splice(this.ca.Ua(molecule),1),molecule.bf(null),molecule.Kb=null,Mb(this)))};z.Ea=function(){return this.u.values()};
z.Vb=function(){if(!this.ya){this.u.gk();this.v=this.zc();for(var e=new Tb(this.v.Ue(),this.v.Qe(),32),f=this.Ea(),g=0,h=f.length;g<h;g++)e.add(new gc(f[g]));e.optimize();h=f.length;for(g=0;g<h;g++)for(var k=f[g],m=k.symbol,m=m.charAt(0).toUpperCase()+m.slice(1).toLowerCase(),l=parseFloat(jb(m)[6]),q=e.$f(k.pos,5),r=q.length,t=0;t<r;t++){var w=q[t].getPoint();if(w!==k){var m=w.symbol,m=m.charAt(0).toUpperCase()+m.slice(1).toLowerCase(),x=parseFloat(jb(m)[6]),m=l+x-.4,x=l+x+.4,B=k.distanceTo(w);B>=
m&&B<=x&&(m=k,x=this.u.findNode(m),B=this.u.findNode(w),void 0!==x&&void 0!==B||console.warn("Couldn't find atoms ",m," and/or ",w," in model ",this),x.pj(B)||this.u.$g(x,B).setAttribute("BondType","SIMPLE"))}}this.ya=!0}return this.u};function Mb(e){e.ea=null;e.v=null;e.ya=!1}z.Ya=function(){if(null===this.ea){this.ea=new THREE.Vector3;for(var e=this.Ea(),f=0,g=0,h=0,k=e.length,m=0;m<k;m++)var l=e[m].pos,f=f+parseInt(l.x),g=g+parseInt(l.y),h=h+parseInt(l.z);this.ea.set(f/k,g/k,h/k)}return this.ea};
z.zc=function(){if(null===this.v){for(var e=new THREE.Vector3(Infinity,Infinity,Infinity),f=new THREE.Vector3(-Infinity,-Infinity,-Infinity),g=this.Ea(),h=0,k=g.length;h<k;h++){var m=g[h].pos;e.x=Math.min(e.x,m.x);e.y=Math.min(e.y,m.y);e.z=Math.min(e.z,m.z);f.x=Math.max(f.x,m.x);f.y=Math.max(f.y,m.y);f.z=Math.max(f.z,m.z)}this.v=new ob(e,f)}return this.v};function Rb(e){this.id=e;this.Kb=this.ea=this.type=null;this.ga=[];this.v=this.ca=this.u=null;this.Qf=!1}z=Rb.prototype;z.ta=function(){return this.id};
z.Vb=function(){return this.Kb.Vb()};z.qc=function(e){if(this.id!==e){this.id=e;for(var f=0;f<this.ga.length;f++)this.ga[f].me(e)}};z.Bc=function(){return this.ea};z.bf=function(e){this.ea=e};z.add=function(e){null==e&&console.warn("residue is null in Molecule");null!==e.xa&&e.xa!==this&&console.warn(e," already belongs to ",e.xa);null===e.xa&&(this.ga.push(e),hc(e,this),ic(this))};
z.remove=function(e){null===e&&console.warn("residue is null in Molecule");e.xa===this&&(this.ga.remove(e),hc(e,null),ic(this))};z.Aa=function(e){for(var f=0;f<this.ga.length;f++){var g=this.ga[f];if(g.ta()==e)return g}return null};z.Ea=function(){for(var e=[],f=this.ga.length,g=0;g<f;g++)e=e.concat(this.ga[g].Ea());return e};z.size=function(){return this.ga.length};z.isEmpty=function(){return 0===this.size};function ic(e){e.u=null;e.ca=null;null!==e.Kb&&Mb(e.Kb)}
z.Ya=function(){if(null===this.u){this.u=new THREE.Vector3;for(var e=this.Ea(),f=e.length,g=0;g<f;g++){var h=e[g].pos;this.u.x+=h.x;this.u.y+=h.y;this.u.z+=h.z}this.u.x/=f;this.u.y/=f;this.u.z/=f}return this.u};
z.zc=function(){if(null===this.ca){for(var e=new THREE.Vector3(Infinity,Infinity,Infinity),f=new THREE.Vector3(-Infinity,-Infinity,-Infinity),g=this.Ea(),h=g.length,k=0;k<h;k++){var m=g[k].pos;e.x=Math.min(e.x,m.x);e.y=Math.min(e.y,m.y);e.z=Math.min(e.z,m.z);f.x=Math.max(f.x,m.x);f.y=Math.max(f.y,m.y);f.z=Math.max(f.z,m.z)}this.ca=new ob(e,f)}return this.ca};z.toString=function(){return this.type+":"+this.id};z.Fb=function(){return this.toString()};z.$b=function(){return this.ea.$b()+":"+this.toString()};
z.Vi=function(){if(null!==this.type&&"Protein"===this.type&&!this.Qf){if(null===this.v){var e=this.ga,f=e.length;this.v=new yb;for(var g=1;g<f;g++){var h=e[g-1],k=e[g],m=this.v.findNode(k);null==m&&(m=this.v.ah(k.toString(),k));var l=k.nc("CA"),q=k.nc("N"),r=k.nc("H");if(h.ta()+h.Bb().charCodeAt(0)===k.ta()+k.Bb().charCodeAt(0)-1&&"PRO"!==h.ca){r=h.nc("C");h=h.nc("O");if(null==r||null==h)continue;r=r.sub(h);r=r.normalize();h=q.add(r);r=new $a;r.name="H";r.symbol="H";r.pos.x=h.x;r.pos.y=h.y;r.pos.z=
h.z}if(null!=r)for(h=0;h<f;h++)if(h!=g&&h!=g-1){var t=e[h],k=this.v.findNode(t);null==k&&(k=this.v.ah(t.toString(),t));var w=t.nc("CA"),x=t.nc("C"),B=t.nc("O");if(null!=w&&null!=x&&null!=B&&!(9<w.distanceTo(l))){var w=r.distanceTo(B),t=r.distanceTo(x),B=q.distanceTo(B),C=q.distanceTo(x),x=-9.9;.5>w||.5>t||.5>B||.5>C||(x=27.888/B,x+=27.888/t,x-=27.888/w,x-=27.888/C,-9.9>x&&(x=-9.9));if(-.5>x){var w=m.Ik(k),G;null!=w?G=w.getAttribute("eH"):G=0;x<G&&(this.v.$g(m,k,!0).setAttribute("eH",x),null!=w&&this.v.Gl(w))}}}}}e=
this.ga.length;for(f=0;f<e;f++)this.ga[f].nb=null;f=1;for(l=4;f+l<e;f++)if(jc(this,this.ga[f-1],this.ga[f-1+l])&&jc(this,this.ga[f],this.ga[f+l]))for(g=f;g<f+l;g++)this.ga[g].nb=H.u;for(f=1;f+1<e;f++)for(g=f+3;g+1<e;g++)if(m=this.ga[f],l=this.ga[g],null===m.nb&&null===l.nb)if(jc(this,this.ga[f-1],l)&&jc(this,l,this.ga[f+1])||jc(this,this.ga[g-1],m)&&jc(this,m,this.ga[g+1]))m.nb=H.v,l.nb=H.v;else if(jc(this,m,l)&&jc(this,l,m)||jc(this,this.ga[f-1],this.ga[g+1])&&jc(this,this.ga[g-1],this.ga[f+1]))m.nb=
H.ea,l.nb=H.ea;f=1;for(l=3;f+l<e;f++)if(jc(this,this.ga[f-1],this.ga[f-1+l])&&jc(this,this.ga[f],this.ga[f+l])){m=!0;for(g=f;g<f+l;g++)if(null!=this.ga[g]){m=!1;break}for(g=f;g<f+l;g++)this.ga[g].nb=m?H.u:H.ka}f=1;for(l=5;f+l<e;f++)if(jc(this,this.ga[f-1],this.ga[f-1+l])&&jc(this,this.ga[f],this.ga[f+l])){m=!0;for(g=f;g<f+l;g++)if(null!=this.ga[g]){m=!1;break}for(g=f;g<f+l;g++)this.ga[g].nb=m?H.u:H.ka}for(l=3;5>=l;l++)for(f=0;f+l<e;f++)if(jc(this,this.ga[f],this.ga[f+l]))for(g=f+1;g<f+l;g++)m=this.ga[g].nb,
null==m&&(this.ga[g].nb=H.ka);for(f=0;f<e;f++)m=this.ga[f].nb,null==m&&(this.ga[f].nb=H.ca);this.Qf=!0}};z.Sl=function(e){if(e.length!=this.ga.length)for(var f=0,g=this.ga.length;f<g;f++){var h=qc[e[this.ga[f]._id-1]];this.ga[f].nb=null!=h?h:H.ca}else for(f=0,g=this.ga.length;f<g;f++)h=qc[e[f]],this.ga[f].nb=null!=h?h:H.ca;this.Qf=!0};function jc(e,f,g){f=e.v.findNode(f);return null==f?!1:f.Qk(e.v.findNode(g))}
z.ee=function(e){void 0===e&&(e=!0);for(var f="",g=this.ga,h=0,k="\x00",m=this.Od()?"X":this.We()?"N":"-",l=g.length,q=0;q<l;q++){var r=g[q];if(e&&0!=q)for(h=r.ta()-h+r.Bb().charCodeAt(0)-k.charCodeAt(0);1<h--;)f+=m;f+=r.oj();h=r.ta();k=r.Bb()}return f};z.We=function(){return"DNA"==this.type||"RNA"==this.type};z.Od=function(){return"Protein"==this.type||"Peptide"==this.type||"Small Peptide"==this.type};z.zj=function(){return this.We()||this.Od()};z.yj=function(){return"Ligand"===this.type};
z.Uj=function(e){var f=new uc,g=[];g.push(new vc(this.toString(),this.ee(!1)));g.push(new vc("ExternalSequence",e));f=f.align(g);e=f.ee("ExternalSequence");f=f.ee(this.toString());console.log(e,f);this.zk=f;console.log(f.ka())};
function Ac(e){for(var f=[],g=0,h=e.ga,k=0,m=0;m<h.length;m++){var l=h[m];if(null===l.type)k++;else{var q=f[l.type];void 0===q&&(q=0,f[l.type]=q,g++);f[l.type]++}}if(0!==g){var g=Infinity,r;for(q in f)h=f[q],0!==h&&h<g?(g=h,r=q):h===g&&q<r&&(r=q);g>=k&&("Protein"==r?(f=e.size(),e.type=20>f?"Small Peptide":60>f?"Peptide":"Protein"):e.type=r)}else e.type="Unknown"}
function Gc(){this._id=this.ea=this.vc=this.xa=this.nb=this.type=this.ca=null;this.ec="\x00";this.u=[];this.ya=new Fa;this.Ma=this.ka=this.v=null}function Hc(e,f){e.ea=f.Xb;e._id=f.zb;e.ec=f.ac}z=Gc.prototype;z.Vb=function(){return this.xa.Vb()};function hc(e,f){e.xa=f;null!==f&&void 0!==f&&e.me(f.ta())}z.ta=function(){return this._id};z.qc=function(e){if(this._id!=e){this._id=e;for(var f=0;f<this.u.length;f++)ab(this.u[f],e)}};z.Bb=function(){return this.ec};z.xb=function(){return this.vc};
z.af=function(e){if(this.vc!=e){this.vc=e;for(var f=this.u.length,g=0;g<f;g++)g.af(e)}};z.dg=function(){return this.ea};z.me=function(e){if(this.ea!=e){this.ea=e;null!==this.xa&&this.xa.qc(e);for(var f=this.u.length,g=0;g<f;g++)g.me(e)}};
z.add=function(e){null===e&&console.warn("atom = null in Residue");null!==e.Aa()&&e.Aa()!==this&&console.warn(e," already belongs to ",e.Aa());if(null===e.Aa()){this.u.push(e);var f=new Ic(e.name,e.zd);this.ya.bd(f)||this.ya.set(f,e);e.Oa=this;null!==this&&(ab(e,e.Oa.ta()),wb(e,e.Oa.Bb()),e.af(e.Oa.xb()),e.me(e.Oa.dg()))}};z.remove=function(e){null===e&&console.warn("atom = null in Residue");e.Aa()===this&&(this.u.remove(e),e=new this.tb(e.name,e.zd),this.ya.remove(e))};z.Ea=function(){return this.u};
z.mj=function(e){for(var f=0;f<this.u.length;f++){var g=this.u[f];if(g.ta()==e)return g}return null};z.nc=function(e){var f=void 0;void 0===f&&(f="\x00");e=this.ya.get((new Ic(e,f)).toString());if(null!==e)return e};z.Ya=function(){if(null==this.v){this.v=new THREE.Vector3;for(var e=this.u.length,f=0;f<e;f++){var g=this.u[f].pos;this.v.x+=g.x;this.v.y+=g.y;this.v.z+=g.z}this.v.x/=e;this.v.y/=e;this.v.z/=e}return this.v};
z.th=function(){if(null==this.ka)for(var e=this.u.length,f=0;f<e;f++){var g=this.u[f];if("CA"===g.name){this.ka=g.pos.clone();break}}if(null==this.ka){for(var h=this.Ya(),k=this.u[0],m=h.distanceTo(k.pos),e=this.u.length,f=0;f<e;f++){var g=this.u[f],l=h.distanceTo(g.pos);l<m&&(k=g,m=l)}this.ka=k.clone()}return this.ka};
z.zc=function(){if(null===this.Ma){for(var e=new THREE.Vector3(Infinity,Infinity,Infinity),f=new THREE.Vector3(-Infinity,-Infinity,-Infinity),g=this.u.length,h=0;h<g;h++){var k=this.u[h];e.x=Math.min(e.x,k.pos.x);e.y=Math.min(e.y,k.pos.y);e.z=Math.min(e.z,k.pos.z);f.x=Math.max(f.x,k.pos.x);f.y=Math.max(f.y,k.pos.y);f.z=Math.max(f.z,k.pos.z)}this.Ma=new ob(e,f)}return this.Ma};z.We=function(){return"DNA"==this.type||"RNA"==this.type};
z.Od=function(){return"Protein"==this.type||"Peptide"==this.type||"Small Peptide"==this.type};
z.oj=function(){switch(null!==this.ca?this.ca:this.vc){case "GLY":return"G";case "ALA":return"A";case "VAL":return"V";case "LEU":return"L";case "ILE":return"I";case "PRO":return"P";case "PHE":return"F";case "MET":return"M";case "TRP":return"W";case "SER":return"S";case "THR":return"T";case "ASN":return"N";case "GLN":return"Q";case "ASP":return"D";case "GLU":return"E";case "CYS":return"C";case "TYR":return"Y";case "HIS":return"H";case "LYS":return"K";case "ARG":return"R";case "ASX":return"B";case "GLX":return"Z";
case "A":case "DA":case "+A":return"A";case "C":case "DC":case "+C":return"C";case "G":case "DG":case "+G":return"G";case "T":case "DT":case "+T":return"T";case "U":case "DU":case "+U":return"U";case "I":case "DI":case "+I":return"I"}return null!=this.xa.type&&"Protein"===this.xa.type?"X":null==this.xa.type||"RNA"!==this.xa.type&&"DNA"!==this.xa.type?"?":"N"};z.toString=function(){return this.vc+":"+this._id};z.Fb=function(){return this.vc+":"+this._id+":"+this.ea};
z.$b=function(){return this.xa.$b()+":"+this.toString()};function Ic(e,f){this.name=e;this.zd=f}Ic.prototype.toString=function(){return this.name+":"+this.zd};Ic.prototype.Fb=function(){return this.name+":"+this.zd};
function Jc(e,f){null===e.ca&&console.warn("Error : stdResName must be set before guessing residue type");if(-1!==Pc.indexOf(e.ca))e.type="DNA";else if(-1!==Tc.indexOf(e.ca))e.type="RNA";else if(-1!==Uc.indexOf(e.ca))e.type="Protein";else if(-1!==bd.indexOf(e.xb()))e.type="Solvent";else if(-1!==cd.indexOf(e.xb()))e.type=null;else{var g=f.get(e.ta());null!=g&&g.name.endsWith(" ION")&&(e.type="Ion");e.type="Ligand"}}
var Uc="GLY ALA VAL LEU ILE PRO PHE MET TRP SER THR ASN GLN ASP GLU CYS TYR HIS LYS ARG".split(" "),Tc=["A","C","G","U","I"],Pc="DA DC DG DT DI DU +A +C +G +T +I +U T".split(" "),cd="UNK ASX GLX N DN UNL UNX".split(" "),bd=["HOH","DOD","GOL","EDO"];
function dd(e,f,g){null===e&&console.warn("chainId null in Residue.Id");this.Xb=e;this.zb=f;this.ac=g;this.toString=function(){return"\x00"!==this.ac.charCodeAt(0)?this.Xb+":"+this.zb+":"+this.ac:this.Xb+":"+this.zb};this.Fb=function(){return"\x00"!==this.ac.charCodeAt(0)?this.Xb+":"+this.zb+":"+this.ac:this.Xb+":"+this.zb}}function H(e,f){this.name=e;this.code=f}H.ca=new H("Coil"," ");H.ka=new H("Turn","T");H.u=new H("Helix","H");H.v=new H("Strand","x");H.ea=new H("Strand","X");
var qc={G:H.u,H:H.u,I:H.u,B:H.v,E:H.v,T:H.ka,S:H.ca,C:H.ca,X:H.ca};H.prototype.toString=function(){return name};function ed(){this.ml=!0;this._id=this.Xg=null;this.Oi=NaN;this.Mi=null;this.ca=[];this.Gi=[];this.xd=new Fa;this.ud=new Fa;this.wc=new Fa;this.Ci=[];this.v=[];this.ea=new Fa;this.u=null}z=ed.prototype;
z.Ya=function(){if(null===this.u){this.u=new THREE.Vector3;for(var e=this.v[0].ca,f=0;f<e.length;f++){var g=e[f].Ya();this.u.x+=g.x;this.u.y+=g.y;this.u.z+=g.z}this.u.x/=e.length;this.u.y/=e.length;this.u.z/=e.length}return this.u};z.Vb=function(){return this.v[0].Vb()};z.ta=function(){return this._id};z.qc=function(e){null==this._id&&(this.Xg=e);this._id=e};z.Ul=function(e){this.Oi=e};z.ci=function(){};z.setDate=function(){};z.ei=function(e){this.Mi=e};z.Rl=function(){};
z.Pi=function(e,f){null==(null==e?this.ca:this.ca[e])&&(this.ca[e]=f)};z.Pl=function(e){this.Gi=e};z.add=function(e){null===e&&console.warn("Error on adding model to structure : model = NULL");null!=e.Bc()&&e.Bc()!=this&&console.warn(e," already belongs to ",e.Bc());null==e.Bc()&&(this.v.push(e),e.bf(this))};z.remove=function(e){null===e&&console.warn("Error on removing structure");e.Bc()==this&&(this.v.remove(e),e.bf(null))};z.fg=function(){return this.v[0]};z.toString=function(){return this._id};
z.Fb=function(){return this.toString()};z.$b=function(){return this.toString()};
z.qk=function(e){this.xd.__proto__=Fa.prototype;Va(this.xd);this.wc.__proto__=Fa.prototype;Va(this.wc);this.ud.__proto__=Fa.prototype;Va(this.ud);for(var f=e.length,g=0;g<f;g++){var h=new xb;this.add(h);for(var k=e[g],m=k.length,l=0;l<m;l++){var q=new $a;q.type=k[l][0];q.id=k[l][1];q.name=k[l][2];q.zd=k[l][3];q.af(k[l][4]);q.me(k[l][5]);ab(q,k[l][6]);wb(q,k[l][7]);q.pos.x=k[l][8];q.pos.y=k[l][9];q.pos.z=k[l][10];q.ka=k[l][11];q.ya=k[l][12];q.symbol=k[l][13];q.ea=k[l][14];h.add(q)}}fd(this)};
function fd(e){var f=e.xd,g=e.ud,h=e.wc,k=e.v,m=!1,l,q=k.length,r=new Fa;for(l=0;l<q;l++){for(var t=k[l],w=[],x=t.Ea(),B=x.length,C=0;C<B;C++){var G=x[C],I=void 0,D=new dd(G.dg(),G.u,G.Bb()),I=r.get(D);if(null==I){I=new Gc;Hc(I,D);I.af(G.xb());var J=f.get(D);I.ca=J?J.Eg:I.xb();Jc(I,g);J=h.get(D);null!=J?(m||(m=!0),I.nb=J):I.nb=H.ca;w.push([I,D]);r.set(D,I)}I.add(G)}G=void 0;for(I=0;I<w.length;I++){x=w[I][0];B=w[I][1];I=x;for(C=[];void 0!==I&&null!==I&&-1===C.indexOf(B)&&!I.Od()&&!I.We();)if(C.push(B),
G=e.ea.get(B),null!=G){for(var G=G.Ua.Xb===B.Xb&&G.Ua.zb===B.zb&&G.Ua.ac===B.ac?G.hc:G.Ua,F,I=0;I<w.length;I++)D=w[I],G.Xb===D.Xb&&G.zb===D.zb&&G.ac===D.ac&&(F=I);I=w[F][0]}void 0!==I&&I.type!==x.type&&(x.type=I.type)}x=new Map;for(I=0;I<w.length;I++)B=w[I][0],C=B.dg(),G=B.type+" "+C,D=x.get(G),void 0===D&&(D=new Rb(C),t.add(D),x.set(G,D)),D.add(B),D.Qf=m;t=function(e,f){return e.Ug<f.Ug?-1:e.Ug>f.Ug?1:e._id<f._id?-1:e._id>f._id?1:e.ec<f.ec?-1:e.ec>f.ec?1:0};w=!0;I=!1;B=void 0;try{for(var K=x.values()[Symbol.iterator](),
N;!(w=(N=K.next()).done);w=!0){var O=N.value;O.ga.sort(t);Ac(O)}}catch(U){I=!0,B=U}finally{try{!w&&K["return"]&&K["return"]()}finally{if(I)throw B;}}}};

function Sj(e){if(Array.isArray(e)){for(var f=0,g=Array(e.length);f<e.length;f++)g[f]=e[f];return g}return Array.from(e)}function Tj(e){e.la=JSON.stringify([].concat(Sj(e.la)));e.vd=JSON.stringify([].concat(Sj(e.vd)))}function Mk(){this.ej=this.ph=this.dj=this.oh=this.nh=this.mh=this.Xf=this.Ch=this.bi=this.Ah=this.ai=this.sf=null}
function Nk(e){this.ia=this.file=null;this.Dc=[];this.source=this.gh=this.keywords=this.title=null;this.ready=!1;this.ge=[];this.ge[Ok.id]=Ok;this.Ve=[];this.resolution=null;null==e&&(e=!1);this.Lf=e;this.Fi=null}var Pk=1;
Nk.prototype.parse=function(e,f){this.Fi=f;this.ia=new ed;a:{var g=e.split("\n"),h,k=null,m;for(m in g){var l=g[m];if(l===this.Bm||l===this.um)break a;if(l===this.vm){this.Dc.push([]);break a}var q=l.substring(0,6).trim(),r=null,t="";switch(q){case "ATOM":case "HETATM":var r=l.substring(76,78).trim(),w=l.substring(12,16).trim();""===r&&(r=w[0]);var x=this.Dc[this.Dc.length-1];void 0===x&&(x=[],this.Dc.push(x));if(this.Lf&&"CA"!==w)break;if(!(null!==r&"H"===r)||this.Gh){var B=[],t=l.charAt(21);B.push(q);
B.push(l.substring(6,11).trim());B.push(w);B.push(" "!=l.charAt(16)?l.charAt(16):"\x00");B.push(l.substring(17,20).trim());B.push(t);B.push(parseFloat(l.substring(22,26).trim()));B.push(" "!=l.charAt(26)?l.charAt(26):"\x00");B.push(parseFloat(l.substring(30,38).trim()));B.push(parseFloat(l.substring(38,46).trim()));B.push(parseFloat(l.substring(46,54).trim()));B.push(l.substring(54,60).trim());B.push(l.substring(60,66).trim());B.push(r);79<=l.length&&B.push(toString(l.charAt(79))+toString(l.charAt(78)));
x.push(B)}break;case "HEADER":59<l.length?(this.ia.ci(l.substring(10,50).trim()),this.ia.qc(l.substring(62,66).trim())):(this.ia.ci(l.substring(10).trim()),this.ia.qc(file.getName().replaceAll("\\..*$","").toUpperCase()));this.ia.setDate(l.substring(50,59));break;case "TITLE":this.title=null===this.title?l.substring(10):this.title+(" "+l.substring(10));this.ia.ei(this.title);break;case "SOURCE":this.source+=l.substring(10);break;case "KEYWDS":this.keywords+=l.substring(10);break;case "AUTHOR":this.gh+=
l.substring(10);break;case "REMARK":l.substring(7,10).trim();if(~l.indexOf("RESOLUTION."))try{l.substring(l.indexOf("RESOLUTION.")+12).trim()}catch(C){console.warn("Error : ",C)}break;case "DBREF":k=new Mk;k.sf=l.charAt(12);k.ai=l.substring(14,18).trim();k.Ah=" "!==l.charAt(18)?l.charAt(18):"\x00";k.bi=l.substring(20,24).trim();k.Ch=" "!=l.charAt(24)?l.charAt(24):"\x00";k.Xf=l.substring(26,32).trim();k.mh=l.substring(33,41).trim();k.nh=l.substring(42,54).trim();k.oh=l.substring(55,60).trim();k.dj=
" "!=l.charAt(60)?l.charAt(60):"\x00";k.ph=l.substring(62,67<=l.length?67:l.length).trim();k.ej=68<=l.length?l.charAt(67):"\x00";this.ia.Pi(k.sf,k);break;case "DBREF1":k=new Mk;k.sf=l.charAt(12);k.ai=l.substring(14,18).trim();k.Ah=" "!=l.charAt(18)?l.charAt(18):"\x00";k.bi=l.substring(20,24).trim();k.Ch=" "!=l.charAt(24)?l.charAt(24):"\x00";k.Xf=l.substring(26,32).trim();k.nh=l.substring(47,67<=l.length?67:l.length).trim();this.ia.Pi(k.sf,k);break;case "DBREF2":k.mh=l.substring(18,40).trim();k.oh=
l.substring(45,55).trim();k.ph=l.substring(57,67<=l.length?67:l.length).trim();break;case "MODRES":r=new Qk;r.name=l.substring(12,15).trim();t=l.charAt(16);q=l.substring(18,22).trim();w=" "!=l.charAt(22)?l.charAt(22):"\x00";r.Eg=l.substring(24,27).trim();r.description=30<=l.length?l.substring(29).trim():null;this.ia.xd.set(new Rk(t,q,w),r);break;case "HET":t=l.substring(7,10).trim();for(h in this.ge)if(h[0]===t){r=h[1];break}null===r&&(r=new Sk,r.id=t,r.description=31<=l.length?l.substring(30):null,
this.ge[t]=r);t=l.charAt(12);q=l.substring(13,17).trim();w=" "!=l.charAt(17)?l.charAt(17):"\x00";this.ia.ud.set(new Rk(t,q,w),r);break;case "HETNAM":t=l.substring(11,14).trim();r=this.ge[t];r.name=null===r.name?l.substring(15):r.name+l.substring(15);break;case "HETSYN":t=l.substring(11,14).trim();this.Ve[t]=void 0===this.Ve[t]?l.substring(15):this.Ve[t]+l.substring(15);break;case "FORMUL":t=l.substring(12,15).trim();r=this.ge[t];r.vf=null===r.vf?l.substring(19):r.vf+l.substring(19);break;case "HELIX":t=
l.charAt(19);r=parseInt(l.substring(21,25));q=l.charAt(25);" "===q&&(q="\x00");h=parseInt(l.substring(33,37));r=parseInt(r);w=parseInt(h);for(h=r;h<=w;h++)this.ia.wc.set(new Rk(t,h,q),H.u);break;case "SHEET":for(t=l.charAt(21),r=parseInt(l.substring(22,26)),q=l.charAt(26)," "===q&&(q="\x00"),h=parseInt(l.substring(33,37)),l=-1===parseInt(l.substring(38,40))?H.ea:H.v,r=parseInt(r),w=parseInt(h),h=r;h<=w;h++)this.ia.wc.set(new Rk(t,h,q),l)}}this.finish();this.ready=!0}};
Nk.prototype.finish=function(){this.ia.Pl(this.ia.Gi.concat(null));this.gh=this.keywords=this.source=null;for(var e in this.Ve){var f=this.ge[e];f.Mj=f.Mj.concat(this.Ve[e].split("\\s*;\\s*"))}this.Ve=this.ge=null;null==this.ia._id&&(this.ia.qc("Unknown_"+Pk),Pk++);Tj(this.ia.wc);Tj(this.ia.ud);Tj(this.ia.xd);this.Fi.apply(this,[this.ia,this.Dc])};function Qk(){this.description=this.Eg=this.name=null}
function Tk(e){this.ia=null;this.Dc=[];this.xh=!1;this.rf=null;this.Qa=[];this.Gh=!1;this.Bj=!0;this.Oj=[];this.pe=[];this.zg=new Fa;null==e&&(e=!1);this.Lf=e}Tk.prototype.parse=function(e,f){this.ia=new ed;this.pe[Ok.id]=Ok;var g=loadCIF(e,1);this.parseJSON(g);Tj(this.ia.xd);Tj(this.ia.wc);Tj(this.ia.ud);f.apply(this,[this.ia,this.Dc])};function Uk(e,f,g){if(!e.xh){var h=f.split(".",2);null!==e.rf&&e.rf!==h[0]&&Vk(e);e.rf=h[0]}e.Qa[f]=g}function Vk(e){null!==e.rf&&(Wk(e),e.Qa=[],e.rf=null)}
function Xk(e,f){var g=parseInt(e.Qa[f]);isNaN(g)&&(g=0);return g}Tk.prototype.getFloatValue=function(e){e=parseFloat(this.Qa[e]);isNaN(e)&&(e=0);return e};Tk.prototype.getStringValue=function(e,f){var g=this.Qa[e];null==g&&null!=f&&(g=this.Qa[f]);if("."===g||"?"===g)return"\x00";void 0!==g&&(g=g.replace('"',""));return g};
function Wk(e){if(void 0!==e.Qa["_atom_site.id"]){var f=parseInt(e.Qa["_atom_site.pdbx_PDB_model_num"]);if(!(e.Bj&&1<f)){var g=e.Dc[f-1];void 0===g&&(g=[],e.Dc[f-1]=g);if(!e.Lf||"CA"===e.getStringValue("_atom_site.label_atom_id")){var f=[],h=e.getStringValue("_atom_site.type_symbol");null!==h&"H"===h&&!e.Gh||(f.push(e.getStringValue("_atom_site.group_PDB")),f.push(Xk(e,"_atom_site.id")),f.push(e.getStringValue("_atom_site.auth_atom_id","_atom_site.label_atom_id").replace(/"/g,"")),f.push(e.getStringValue("_atom_site.label_alt_id").replace(/"/g,
"")),f.push(e.getStringValue("_atom_site.auth_comp_id","_atom_site.label_comp_id")),f.push(e.getStringValue("_atom_site.auth_asym_id","_atom_site.label_asym_id")),f.push(Xk(e,"_atom_site.auth_seq_id")),f.push(e.getStringValue("_atom_site.pdbx_PDB_ins_code")),f.push(e.getFloatValue("_atom_site.Cartn_x")),f.push(e.getFloatValue("_atom_site.Cartn_y")),f.push(e.getFloatValue("_atom_site.Cartn_z")),f.push(e.getFloatValue("_atom_site.occupancy")),f.push(e.getFloatValue("_atom_site.B_iso_or_equiv")),f.push(e.getStringValue("_atom_site.type_symbol")),
f.push(Xk(e,"_atom_site.pdbx_formal_charge")),g.push(f))}}}else if(void 0!==e.Qa["_struct_keywords.entry_id"])e.ia.ci(e.getStringValue("_struct_keywords.pdbx_keywords")),null!==e.getStringValue("_struct_keywords.text")&&e.getStringValue("_struct_keywords.text");else if(void 0!==e.Qa["_audit_author.name"])e.ia.Ci.push(e.getStringValue("_audit_author.name"));else if(void 0!==e.Qa["_database_PDB_rev.num"])g=e.getStringValue("_database_PDB_rev.date_original"),null!==g&&e.ia.setDate(g);else if(void 0!==
e.Qa["_struct.entry_id"])e.ia.ei(e.getStringValue("_struct.title"));else if(void 0!==e.Qa["_refine.entry_id"])e.ia.Rl(e.getFloatValue("_refine.ls_d_res_high",NaN));else if(void 0!==e.Qa["_entity.id"])"polymer"===e.Qa["_entity.type"]&&(g=Xk(e,"_entity.id"));else if(void 0===e.Qa["_entity_poly.entity_id"]&&void 0===e.Qa["_entity_name_com.entity_id"])if(void 0!==e.Qa["_struct_ref.id"])g=Xk(e,"_struct_ref.id"),f=new Mk,e.Oj[g]=f,f.Xf=e.getStringValue("_struct_ref.db_name"),f.nh=e.getStringValue("_struct_ref.db_code"),
f.mh=e.getStringValue("_struct_ref.pdbx_db_accession");else if(void 0!==e.Qa["_struct_ref_seq.align_id"])g=Xk(e,"_struct_ref_seq.ref_id"),f=e.Oj[g],f.sf=e.getStringValue("_struct_ref_seq.pdbx_strand_id"),f.ai=Xk(e,"_struct_ref_seq.seq_align_beg"),f.Ah=e.getStringValue("_struct_ref_seq.pdbx_seq_align_beg_ins_code"),f.bi=Xk(e,"_struct_ref_seq.seq_align_end"),f.Ch=e.getStringValue("_struct_ref_seq.pdbx_seq_align_end_ins_code"),f.oh=Xk(e,"_struct_ref_seq.db_align_beg"),f.dj=e.getStringValue("_struct_ref_seq.pdbx_db_align_beg_ins_code"),
f.ph=Xk(e,"_struct_ref_seq.db_align_end"),f.ej=e.getStringValue("_struct_ref_seq.pdbx_db_align_end_ins_code");else if(void 0!==e.Qa["_pdbx_struct_mod_residue.id"]){f=new Qk;f.name=e.getStringValue("_pdbx_struct_mod_residue.auth_comp_id");f.Eg=e.getStringValue("_pdbx_struct_mod_residue.parent_comp_id");f.description=e.getStringValue("_pdbx_struct_mod_residue.details");var g=e.getStringValue("_pdbx_struct_mod_residue.auth_asym_id"),h=Xk(e,"_pdbx_struct_mod_residue.auth_seq_id"),k=e.getStringValue("_pdbx_struct_mod_residue.PDB_ins_code");
e.ia.xd.set(new Rk(g,h,k),f)}else if(void 0!==e.Qa["_pdbx_nonpoly_scheme.asym_id"])g=e.getStringValue("_pdbx_nonpoly_scheme.mon_id"),f=e.pe[g],void 0===f&&(f=new Sk,f.id=g,e.pe[g]=f),g=e.getStringValue("_pdbx_nonpoly_scheme.pdb_strand_id"),h=Xk(e,"_pdbx_nonpoly_scheme.pdb_seq_num"),k=e.getStringValue("_pdbx_nonpoly_scheme.pdb_ins_code"),e.ia.ud.set(new Rk(g,h,k),f);else if(void 0!==e.Qa["_chem_comp.id"])g=e.getStringValue("_chem_comp.id"),f=e.pe[g],void 0!==f&&(f.name=e.getStringValue("_chem_comp.name"),
null!=e.getStringValue("_chem_comp.pdbx_synonyms")&&e.getStringValue("_chem_comp.pdbx_synonyms"),f.vf=e.getStringValue("_chem_comp.formula"));else if(void 0===e.Qa["_struct_conn.id"])if(void 0!==e.Qa["_struct_conf.id"]){e.getStringValue("_struct_conf.conf_type_id");var g=e.getStringValue("_struct_conf.beg_auth_asym_id"),m=Xk(e,"_struct_conf.beg_auth_seq_id"),f=e.getStringValue("_struct_conf.pdbx_beg_PDB_ins_code");e.getStringValue("_struct_conf.end_auth_asym_id");k=Xk(e,"_struct_conf.end_auth_seq_id");
e.getStringValue("_struct_conf.pdbx_end_PDB_ins_code");for(var l=parseInt(m),k=parseInt(k);l<=k;l++)e.ia.wc.set(new Rk(g,l,f),H.u)}else if(void 0!==e.Qa["_struct_sheet_range.id"])for(h=H.v,g=e.getStringValue("_struct_sheet_range.beg_auth_asym_id"),m=Xk(e,"_struct_sheet_range.beg_auth_seq_id"),f=e.getStringValue("_struct_sheet_range.pdbx_beg_PDB_ins_code"),e.getStringValue("_struct_sheet_range.end_auth_asym_id"),k=Xk(e,"_struct_sheet_range.end_auth_seq_id"),e.getStringValue("_struct_sheet_range.pdbx_end_PDB_ins_code"),
l=e.getStringValue("_struct_sheet_range.id"),l=e.zg.get(new Rk(g,l,"0")),"anti-parallel"===l&&(h=H.ea),l=parseInt(m),k=parseInt(k);l<=k;l++)e.ia.wc.set(new Rk(g,l,f),h);else void 0!==e.Qa["_struct_sheet_order.sheet_id"]&&(g=e.getStringValue("_struct_sheet_order.sheet_id"),e.getStringValue("_struct_sheet_order.range_id_1"),f=e.getStringValue("_struct_sheet_order.range_id_2"),l=e.getStringValue("_struct_sheet_order.sense"),e.zg.set(new Rk(g,f,"\x00"),l))}
Tk.prototype.parseJSON=function(e){for(var f in e){var g=e[f];this.ia.qc(g.entry.id[0]);var h=g,k=h.struct_keywords;Z(k.pdbx_keywords[0]);for(var m=0,l=k.text.length;m<l;m++)k=Z(k.text[m]).split("\\s*,\\s*");k=h.audit_author;m=0;for(l=k.name.length;m<l;m++)this.ia.Ci.push(Z(k.name[m]));k=h.database_PDB_rev;m=0;for(l=k.num.length;m<l;m++){var q=Z(k.date_original[m]);null!==q&&this.ia.setDate(q)}this.ia.ei(Z(h.struct.title[0]));h=h.entity;m=k=0;for(l=h.formula_weight.length;m<l;m++)k+=Yk(h.formula_weight[m]);
this.ia.Ul(k);m=g.atom_site;l=0;for(h=m.id.length;l<h;l++){q=parseInt(m.pdbx_PDB_model_num[l]);if(this.Bj&&1<q)break;k=this.Dc[q-1];void 0===k&&(k=[],this.Dc[q-1]=k);if(this.Lf&&"CA"!==m.label_atom_id[l])break;var q=[],r=m.type_symbol[l];null!==r&"H"===r&&!this.Gh||(q.push(Z(m.group_PDB[l])),q.push(Zk(m.id[l])),q.push(Z(m.auth_atom_id[l],m.label_atom_id[l]).replace(/"/g,"")),q.push(Z(m.label_alt_id[l].replace(/"/g,""))),q.push(Z(m.auth_comp_id[l],m.label_comp_id[l])),q.push(Z(m.auth_asym_id[l],m.label_asym_id[l])),
q.push(Zk(m.auth_seq_id[l])),q.push(Z(m.pdbx_PDB_ins_code[l])),q.push(Yk(m.Cartn_x[l])),q.push(Yk(m.Cartn_y[l])),q.push(Yk(m.Cartn_z[l])),q.push(Yk(m.occupancy[l])),q.push(Yk(m.B_iso_or_equiv[l])),q.push(Z(m.type_symbol[l])),q.push(Zk(m.pdbx_formal_charge[l])),k.push(q))}m=g.pdbx_struct_mod_residue;if(null!=m)for(l=0,h=m.id.length;l<h;l++){k=new Qk;k.name=Z(m.auth_comp_id[l]);k.Eg=Z(m.parent_comp_id[l]);k.description=Z(m.details[l]);var q=Z(m.auth_asym_id[l]),r=Zk(m.auth_seq_id[l]),t=Z(m.PDB_ins_code[l]);
this.ia.xd.set(new Rk(q,r,t),k)}m=g.pdbx_nonpoly_scheme;if(null!=m)for(l=0,h=m.asym_id.length;l<h;l++)q=Z(m.mon_id[l]),k=this.pe[q],void 0===k&&(k=new Sk,k.id=q,this.pe[q]=k),q=Z(m.pdb_strand_id[l]),r=Zk(m.pdb_seq_num[l]),t=Z(m.pdb_ins_code[l]),this.ia.ud.set(new Rk(q,r,t),k);m=g.chem_comp;if(null!=m)for(l=0,h=m.id.length;l<h;l++)k=Z(m.id[l]),k=this.pe[k],void 0!==k&&(k.name=Z(m.name[l]),null!=Z(m.pdbx_synonyms[l])&&Z(m.pdbx_synonyms[l]),k.vf=Z(m.formula[l]));m=g.struct_conf;if(null!=m)for(l=0,h=
m.id.length;l<h;l++)for(Z(m.conf_type_id[l]),k=Z(m.beg_auth_asym_id[l]),r=Zk(m.beg_auth_seq_id[l]),q=Z(m.pdbx_beg_PDB_ins_code[l]),Z(m.end_auth_asym_id[l]),t=Zk(m.end_auth_seq_id[l]),Z(m.pdbx_end_PDB_ins_code[l]),t=parseInt(t),r=parseInt(r);r<=t;r++)this.ia.wc.set(new Rk(k,r,q),H.u);m=g.struct_sheet_order;if(null!=m)for(l=0,h=m.sheet_id.length;l<h;l++)k=Z(m.sheet_id[l]),Z(m.range_id_1[l]),q=Z(m.range_id_2[l]),r=Z(m.sense[l]),this.zg.set(new Rk(k,q,"\x00"),r);g=g.struct_sheet_range;if(null!=g)for(m=
0,l=g.id.length;m<l;m++){h=H.v;k=Z(g.beg_auth_asym_id[m]);r=Zk(g.beg_auth_seq_id[m]);q=Z(g.pdbx_beg_PDB_ins_code[m]);Z(g.end_auth_asym_id[m]);t=Zk(g.end_auth_seq_id[m]);Z(g.pdbx_end_PDB_ins_code[m]);var w=Z(g.id[m]);"anti-parallel"===this.zg.get(new Rk(k,w,"0"))&&(h=H.ea);t=parseInt(t);for(r=parseInt(r);r<=t;r++)this.ia.wc.set(new Rk(k,r,q),h)}}};function Zk(e){e=parseInt(e);isNaN(e)&&(e=0);return e}function Yk(e){e=parseFloat(e);isNaN(e)&&(e=0);return e}
function Z(e,f){var g=e;null==g&&null!=defaultTag&&(g=f);if("."===g||"?"===g)return"\x00";void 0!==g&&(g=g.replace('"',""));return g}function Rk(e,f,g){null===e&&console.warn("chainId null in Residue.Id");this.Xb=e;this.zb=f;this.ac=g;this.toString=function(){return"\x00"!==this.ac.charCodeAt(0)?this.Xb+":"+this.zb+":"+this.ac:this.Xb+":"+this.zb};this.Fb=function(){return"\x00"!==this.ac.charCodeAt(0)?this.Xb+":"+this.zb+":"+this.ac:this.Xb+":"+this.zb}}
onmessage=function(e){function f(e,f){postMessage(JSON.stringify(e));postMessage(JSON.stringify(f))}var g=e.data[0],h=e.data[2],k;k=e.data[1]?new Tk:new Nk;if(h)k.parse(g,f);else{var m=new XMLHttpRequest;m.open("GET",g,!0);m.onreadystatechange=function(){var e=m.status;if(4==m.readyState)if(200==e)postMessage(new Blob([m.responseText],{type:"text/plain"})),k.parse(m.responseText,f);else{var h={type:"error",msg:""};switch(e){case 404:h.msg="File not found, "+g;break;case 500:h.msg="Server error";break;
case 0:h.msg="Request aborted";break;default:h.msg="Unknown error "+e}postMessage(JSON.stringify(h))}};m.send(null)}};function Sk(){this.name=this.id=null;this.Mj=[];this.description=this.vf=null}var Ok=new Sk;Ok.id="HOH";Ok.name="WATER";H=function(e,f){this.name=e;this.code=f};H.ca=new H("Coil"," ");H.ka=new H("Turn","T");H.u=new H("Helix","H");H.v=new H("Strand","x");H.ea=new H("Strand","X");qc={G:H.u,H:H.u,I:H.u,B:H.v,E:H.v,T:H.ka,S:H.ca,C:H.ca,X:H.ca};H.prototype.toString=function(){return name};
(function(){function e(f,g,h,k){this.message=f;this.location=k;this.name="SyntaxError";"function"===typeof Error.captureStackTrace&&Error.captureStackTrace(this,e)}(function(e,g){function h(){this.constructor=e}h.prototype=g.prototype;e.prototype=new h})(e,Error);return{SyntaxError:e,parse:function(f,g){function h(e){var g=vb[e],h,k;if(g)return g;for(h=e-1;!vb[h];)h--;g=vb[h];for(g={line:g.line,sb:g.sb,ic:g.ic};h<e;)k=f.charAt(h),"\n"===k?(g.ic||g.line++,g.sb=1,g.ic=!1):"\r"===k||"\u2028"===k||"\u2029"===
k?(g.line++,g.sb=1,g.ic=!0):(g.sb++,g.ic=!1),h++;return vb[e]=g}function k(e,f){var g=h(e),k=h(f);return{start:{offset:e,line:g.line,sb:g.sb},end:{offset:f,line:k.line,sb:k.sb}}}function m(e){A<ja||(A>ja&&(ja=A,Zb=[]),Zb.push(e))}function l(){var e,g,h,k,m,l,n;e=O();if(e===y&&(e=N(),e===y))if(e=A,g=q(),g!==y){h=A;k=[];m=A;l=N();l!==y?(n=q(),n!==y?m=l=[l,n]:(A=m,m=y)):(A=m,m=y);for(;m!==y;)k.push(m),m=A,l=N(),l!==y?(n=q(),n!==y?m=l=[l,n]:(A=m,m=y)):(A=m,m=y);h=k!==y?f.substring(h,A):k;if(h!==y){k=
[];for(m=N();m!==y;)k.push(m),m=N();k!==y?e=g=[g,h,k]:(A=e,e=y)}else A=e,e=y}else A=e,e=y;return e}function q(){var e,g,h,k,l,n;k=h=g=e=A;var q,w,x,B,D;n=l=A;Lc.test(f.charAt(A))?(q=f.charAt(A),A++):(q=y,0===L&&m(lc));q===y&&(Cb.test(f.charAt(A))?(q=f.charAt(A),A++):(q=y,0===L&&m(mc)));q!==y?(Ma.test(f.charAt(A))?(w=f.charAt(A),A++):(w=y,0===L&&m(Wa)),w===y&&(fb.test(f.charAt(A))?(w=f.charAt(A),A++):(w=y,0===L&&m(ea))),w!==y?(qa.test(f.charAt(A))?(x=f.charAt(A),A++):(x=y,0===L&&m(ma)),x===y&&(Da.test(f.charAt(A))?
(x=f.charAt(A),A++):(x=y,0===L&&m(Db))),x!==y?(Ma.test(f.charAt(A))?(B=f.charAt(A),A++):(B=y,0===L&&m(Wa)),B===y&&(fb.test(f.charAt(A))?(B=f.charAt(A),A++):(B=y,0===L&&m(ea))),B!==y?(qb.test(f.charAt(A))?(D=f.charAt(A),A++):(D=y,0===L&&m(sa)),D!==y?n=q=[q,w,x,B,D]:(A=n,n=y)):(A=n,n=y)):(A=n,n=y)):(A=n,n=y)):(A=n,n=y);l=n!==y?f.substring(l,A):n;k=l!==y?f.substring(k,A):l;if(k!==y){l=A;k=[];n=C();if(n!==y)for(;n!==y;)k.push(n),n=C();else k=y;l=k!==y?f.substring(l,A):k;l!==y?(Y.te.ia.qc(l),h=void 0):
(A=h,h=y)}else A=h,h=y;g=h!==y?f.substring(g,A):h;if(g!==y){h=[];k=A;l=N();l!==y?(n=t(),n===y&&(n=r()),n!==y?k=l=[l,n]:(A=k,k=y)):(A=k,k=y);for(;k!==y;)h.push(k),k=A,l=N(),l!==y?(n=t(),n===y&&(n=r()),n!==y?k=l=[l,n]:(A=k,k=y)):(A=k,k=y);h!==y?e=g=[g,h]:(A=e,e=y)}else A=e,e=y;return e}function r(){var e,g,h,k,m,l;g=e=A;h=Sb();h!==y?(k=A,m=C(),k=m!==y?f.substring(k,A):m,k!==y?g=h=[h,k]:(A=g,g=y)):(A=g,g=y);if(g!==y){h=[];k=A;m=N();m!==y?(l=t(),l!==y?k=m=[m,l]:(A=k,k=y)):(A=k,k=y);if(k!==y)for(;k!==
y;)h.push(k),k=A,m=N(),m!==y?(l=t(),l!==y?k=m=[m,l]:(A=k,k=y)):(A=k,k=y);else h=y;h!==y?(k=N(),k!==y?(m=Sb(),m!==y?e=g=[g,h,k,m]:(A=e,e=y)):(A=e,e=y)):(A=e,e=y)}else A=e,e=y;return e}function t(){var e,g,h,k;e=A;g=Gb();g!==y&&(g=Y.te,Vk(g),g.xh=!0,Y.Kh=[],Y.i=0,g=void 0);if(g!==y){h=[];g=w();if(g!==y)for(;g!==y;)h.push(g),g=w();else h=y;if(h!==y){g=[];for(h=x();h!==y;)g.push(h),h=x();g!==y?(e=Y.te,e.xh=!1,e.Qa=[],e=void 0):(A=e,e=y)}else A=e,e=y}else A=e,e=y;e===y&&(g=e=A,h=aa(),g=h!==y?f.substring(g,
A):h,g!==y?(h=N(),h!==y?(h=A,k=pa(),h=k!==y?f.substring(h,A):k,h!==y?(Uk(Y.te,g,h),e=void 0):(A=e,e=y)):(A=e,e=y)):(A=e,e=y));return e}function w(){var e,f;e=A;f=N();f!==y?(f=aa(),f!==y?(Y.Kh.push(f),e=void 0):(A=e,e=y)):(A=e,e=y);return e}function x(){var e,f,g;e=A;f=N();f!==y?(g=A,L++,f=Gb(),L--,f===y?g=void 0:(A=g,g=y),g!==y?(f=pa(),f!==y?(e=Y.Kh.length,Uk(Y.te,Y.Kh[Y.i%e],f),Y.i++,0===Y.i%e&&Wk(Y.te),e=void 0):(A=e,e=y)):(A=e,e=y)):(A=e,e=y);return e}function B(){var e;zb.test(f.charAt(A))?(e=
f.charAt(A),A++):(e=y,0===L&&m(wc));return e}function C(){var e;e=B();e===y&&(e=I(),e===y&&(bb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===L&&m(ua)),e===y&&(e=D(),e===y&&(Ab.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===L&&m(gd)),e===y&&(91===f.charCodeAt(A)?(e=Ub,A++):(e=y,0===L&&m(cb)),e===y&&(93===f.charCodeAt(A)?(e=pb,A++):(e=y,0===L&&m(db))))))));return e}function G(){var e;e=B();e===y&&(e=I(),e===y&&(bb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===L&&m(ua)),e===y&&(e=D(),e===y&&(qb.test(f.charAt(A))?
(e=f.charAt(A),A++):(e=y,0===L&&m(sa)),e===y&&(e=ga(),e===y&&(e=ca(),e===y&&(91===f.charCodeAt(A)?(e=Ub,A++):(e=y,0===L&&m(cb)),e===y&&(93===f.charCodeAt(A)?(e=pb,A++):(e=y,0===L&&m(db))))))))));return e}function I(){var e;34===f.charCodeAt(A)?(e=eb,A++):(e=y,0===L&&m(Qa));return e}function D(){var e;39===f.charCodeAt(A)?(e=rb,A++):(e=y,0===L&&m(Bb));return e}function J(){var e;e=B();e===y&&(bb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===L&&m(ua)),e===y&&(95===f.charCodeAt(A)?(e=Ra,A++):(e=y,0===
L&&m(ra)),e===y&&(e=ga(),e===y&&(e=ca(),e===y&&(91===f.charCodeAt(A)?(e=Ub,A++):(e=y,0===L&&m(cb)),e===y&&(59===f.charCodeAt(A)?(e=Q,A++):(e=y,0===L&&m(S)),e===y&&(93===f.charCodeAt(A)?(e=pb,A++):(e=y,0===L&&m(db)),e===y&&(e=D(),e===y&&(e=I())))))))));return e}function F(){var e;e=B();e===y&&(bb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===L&&m(ua)),e===y&&(95===f.charCodeAt(A)?(e=Ra,A++):(e=y,0===L&&m(ra)),e===y&&(e=ga(),e===y&&(e=ca(),e===y&&(91===f.charCodeAt(A)?(e=Ub,A++):(e=y,0===L&&m(cb)),
e===y&&(59===f.charCodeAt(A)?(e=Q,A++):(e=y,0===L&&m(S)),e===y&&(93===f.charCodeAt(A)?(e=pb,A++):(e=y,0===L&&m(db)),e===y&&(e=I()))))))));return e}function K(){var e;e=B();e===y&&(bb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===L&&m(ua)),e===y&&(95===f.charCodeAt(A)?(e=Ra,A++):(e=y,0===L&&m(ra)),e===y&&(e=ga(),e===y&&(e=ca(),e===y&&(91===f.charCodeAt(A)?(e=Ub,A++):(e=y,0===L&&m(cb)),e===y&&(59===f.charCodeAt(A)?(e=Q,A++):(e=y,0===L&&m(S)),e===y&&(93===f.charCodeAt(A)?(e=pb,A++):(e=y,0===L&&m(db)),
e===y&&(e=D()))))))));return e}function N(){var e,g,h;e=A;g=[];h=U();h===y&&(h=ga(),h===y&&(h=ca(),h===y&&(h=xa())));if(h!==y)for(;h!==y;)g.push(h),h=U(),h===y&&(h=ga(),h===y&&(h=ca(),h===y&&(h=xa())));else g=y;return e=g!==y?f.substring(e,A):g}function O(){var e,g,h,k,l,n;e=A;g=[];h=A;35===f.charCodeAt(A)?(k=sb,A++):(k=y,0===L&&m(La));if(k!==y){l=[];for(n=J();n!==y;)l.push(n),n=J();l!==y?(n=xa(),n===y&&(n=Hb()),n!==y?h=k=[k,l,n]:(A=h,h=y)):(A=h,h=y)}else A=h,h=y;if(h!==y)for(;h!==y;)if(g.push(h),
h=A,35===f.charCodeAt(A)?(k=sb,A++):(k=y,0===L&&m(La)),k!==y){l=[];for(n=J();n!==y;)l.push(n),n=J();l!==y?(n=xa(),n===y&&(n=Hb()),n!==y?h=k=[k,l,n]:(A=h,h=y)):(A=h,h=y)}else A=h,h=y;else g=y;return e=g!==y?f.substring(e,A):g}function U(){var e,f,g;e=A;f=[];g=ga();g===y&&(g=ca(),g===y&&(g=xa()));if(g!==y)for(;g!==y;)f.push(g),g=ga(),g===y&&(g=ca(),g===y&&(g=xa()));else f=y;f!==y?(g=O(),g!==y?e=f=[f,g]:(A=e,e=y)):(A=e,e=y);return e}function aa(){var e,g,h,k,l;g=e=A;95===f.charCodeAt(A)?(h=Ra,A++):(h=
y,0===L&&m(ra));if(h!==y){k=[];l=C();if(l!==y)for(;l!==y;)k.push(l),l=C();else k=y;k!==y?g=h=[h,k]:(A=g,g=y)}else A=g,g=y;return e=g!==y?f.substring(e,A):g}function pa(){var e,g;e=A;var h,k,l,n,q,r,t,w,x;g=A;59===f.charCodeAt(A)?(h=Q,A++):(h=y,0===L&&m(S));if(h!==y){k=[];for(l=J();l!==y;)k.push(l),l=J();if(k!==y)if(l=xa(),l!==y){n=[];r=q=A;t=G();if(t!==y){w=[];for(x=J();x!==y;)w.push(x),x=J();w!==y?r=t=[t,w]:(A=r,r=y)}else A=r,r=y;r===y&&(r=null);r!==y?(t=xa(),t!==y?q=r=[r,t]:(A=q,q=y)):(A=q,q=y);
for(;q!==y;){n.push(q);r=q=A;t=G();if(t!==y){w=[];for(x=J();x!==y;)w.push(x),x=J();w!==y?r=t=[t,w]:(A=r,r=y)}else A=r,r=y;r===y&&(r=null);r!==y?(t=xa(),t!==y?q=r=[r,t]:(A=q,q=y)):(A=q,q=y)}n!==y?(59===f.charCodeAt(A)?(q=Q,A++):(q=y,0===L&&m(S)),q!==y?g=h=[h,k,l,n,q]:(A=g,g=y)):(A=g,g=y)}else A=g,g=y;else A=g,g=y}else A=g,g=y;e=g!==y?f.substring(e,A):g;if(e===y){h=g=e=A;k=I();if(k!==y){l=[];for(n=K();n!==y;)l.push(n),n=K();l!==y?(n=I(),n!==y?h=k=[k,l,n]:(A=h,h=y)):(A=h,h=y)}else A=h,h=y;g=h!==y?f.substring(g,
A):h;if(g===y){g=A;h=D();if(h!==y){k=[];l=F();l===y&&(l=A,n=D(),n!==y?(q=A,L++,r=N(),L--,r===y?q=void 0:(A=q,q=y),q!==y?l=n=[n,q]:(A=l,l=y)):(A=l,l=y));for(;l!==y;)k.push(l),l=F(),l===y&&(l=A,n=D(),n!==y?(q=A,L++,r=N(),L--,r===y?q=void 0:(A=q,q=y),q!==y?l=n=[n,q]:(A=l,l=y)):(A=l,l=y));k!==y?(l=D(),l!==y?g=h=[h,k,l]:(A=g,g=y)):(A=g,g=y)}else A=g,g=y;if(g===y)if(g=A,h=B(),h!==y){k=A;l=[];for(n=C();n!==y;)l.push(n),n=C();k=l!==y?f.substring(k,A):l;k!==y?g=h=[h,k]:(A=g,g=y)}else A=g,g=y}e=g!==y?f.substring(e,
A):g;e===y&&(e=A,Vb.test(f.charAt(A))?(g=f.charAt(A),A++):(g=y,0===L&&m(Kc)),e=g!==y?f.substring(e,A):g,e===y&&(e=A,kc.test(f.charAt(A))?(g=f.charAt(A),A++):(g=y,0===L&&m(Wb)),e=g!==y?f.substring(e,A):g))}return e}function Gb(){var e,g,h,k,l,n,q;g=e=A;tb.test(f.charAt(A))?(h=f.charAt(A),A++):(h=y,0===L&&m(ub));h===y&&(Na.test(f.charAt(A))?(h=f.charAt(A),A++):(h=y,0===L&&m(Eb)));h!==y?(ta.test(f.charAt(A))?(k=f.charAt(A),A++):(k=y,0===L&&m(Sa)),k===y&&(na.test(f.charAt(A))?(k=f.charAt(A),A++):(k=y,
0===L&&m(Xa))),k!==y?(ta.test(f.charAt(A))?(l=f.charAt(A),A++):(l=y,0===L&&m(Sa)),l===y&&(na.test(f.charAt(A))?(l=f.charAt(A),A++):(l=y,0===L&&m(Xa))),l!==y?(va.test(f.charAt(A))?(n=f.charAt(A),A++):(n=y,0===L&&m(gb)),n===y&&(xc.test(f.charAt(A))?(n=f.charAt(A),A++):(n=y,0===L&&m(yc))),n!==y?(qb.test(f.charAt(A))?(q=f.charAt(A),A++):(q=y,0===L&&m(sa)),q!==y?g=h=[h,k,l,n,q]:(A=g,g=y)):(A=g,g=y)):(A=g,g=y)):(A=g,g=y)):(A=g,g=y);return e=g!==y?f.substring(e,A):g}function Sb(){var e,g,h,k,l,n,q;g=e=A;
Xb.test(f.charAt(A))?(h=f.charAt(A),A++):(h=y,0===L&&m(ya));h===y&&(oa.test(f.charAt(A))?(h=f.charAt(A),A++):(h=y,0===L&&m(za)));h!==y?(Ma.test(f.charAt(A))?(k=f.charAt(A),A++):(k=y,0===L&&m(Wa)),k===y&&(fb.test(f.charAt(A))?(k=f.charAt(A),A++):(k=y,0===L&&m(ea))),k!==y?(Mc.test(f.charAt(A))?(l=f.charAt(A),A++):(l=y,0===L&&m(Ea)),l===y&&(Jb.test(f.charAt(A))?(l=f.charAt(A),A++):(l=y,0===L&&m(Nc))),l!==y?(Oc.test(f.charAt(A))?(n=f.charAt(A),A++):(n=y,0===L&&m(Yb)),n===y&&(Ta.test(f.charAt(A))?(n=f.charAt(A),
A++):(n=y,0===L&&m(Oa))),n!==y?(qb.test(f.charAt(A))?(q=f.charAt(A),A++):(q=y,0===L&&m(sa)),q!==y?g=h=[h,k,l,n,q]:(A=g,g=y)):(A=g,g=y)):(A=g,g=y)):(A=g,g=y)):(A=g,g=y);return e=g!==y?f.substring(e,A):g}function ga(){var e;32===f.charCodeAt(A)?(e=nc,A++):(e=y,0===L&&m(zc));return e}function ca(){var e;9===f.charCodeAt(A)?(e=oc,A++):(e=y,0===L&&m(hb));return e}function xa(){var e;10===f.charCodeAt(A)?(e=Kb,A++):(e=y,0===L&&m(Ya));e===y&&(13===f.charCodeAt(A)?(e=Lb,A++):(e=y,0===L&&m(pc)),e===y&&(f.substr(A,
2)===Fb?(e=Fb,A+=2):(e=y,0===L&&m(wa))));return e}function Hb(){var e,g;e=A;L++;f.length>A?(g=f.charAt(A),A++):(g=y,0===L&&m(Ua));L--;g===y?e=void 0:(A=e,e=y);return e}this.te=g;var Y=this,n=1<arguments.length?arguments[1]:{},y={},Ib={start:l},da=l,zb=/^[a-zA-Z0-9!%&*()+,-.\/:<=>?@\^`{|}~\\]/,wc={type:"class",value:"[a-zA-Z0-9!%&*()+,-\\./:<=>?@\\^`{|}~\\\\]",description:"[a-zA-Z0-9!%&*()+,-\\./:<=>?@\\^`{|}~\\\\]"},bb=/^[#$]/,ua={type:"class",value:"[#$]",description:"[#$]"},Ab=/^[_;']/,gd={type:"class",
value:"[_;']",description:"[_;']"},Ub="[",cb={type:"literal",value:"[",description:'"["'},pb="]",db={type:"literal",value:"]",description:'"]"'},qb=/^[_]/,sa={type:"class",value:"[_]",description:"[_]"},eb='"',Qa={type:"literal",value:'"',description:'"\\""'},rb="'",Bb={type:"literal",value:"'",description:'"\'"'},Ra="_",ra={type:"literal",value:"_",description:'"_"'},Q=";",S={type:"literal",value:";",description:'";"'},sb="#",La={type:"literal",value:"#",description:'"#"'},Vb=/^[.]/,Kc={type:"class",
value:"[.]",description:"[.]"},kc=/^[?]/,Wb={type:"class",value:"[?]",description:"[?]"},Lc=/^[D]/,lc={type:"class",value:"[D]",description:"[D]"},Cb=/^[d]/,mc={type:"class",value:"[d]",description:"[d]"},Ma=/^[A]/,Wa={type:"class",value:"[A]",description:"[A]"},fb=/^[a]/,ea={type:"class",value:"[a]",description:"[a]"},qa=/^[T]/,ma={type:"class",value:"[T]",description:"[T]"},Da=/^[t]/,Db={type:"class",value:"[t]",description:"[t]"},tb=/^[L]/,ub={type:"class",value:"[L]",description:"[L]"},Na=/^[l]/,
Eb={type:"class",value:"[l]",description:"[l]"},ta=/^[O]/,Sa={type:"class",value:"[O]",description:"[O]"},na=/^[o]/,Xa={type:"class",value:"[o]",description:"[o]"},va=/^[P]/,gb={type:"class",value:"[P]",description:"[P]"},xc=/^[p]/,yc={type:"class",value:"[p]",description:"[p]"},Xb=/^[S]/,ya={type:"class",value:"[S]",description:"[S]"},oa=/^[s]/,za={type:"class",value:"[s]",description:"[s]"},Mc=/^[V]/,Ea={type:"class",value:"[V]",description:"[V]"},Jb=/^[v]/,Nc={type:"class",value:"[v]",description:"[v]"},
Oc=/^[E]/,Yb={type:"class",value:"[E]",description:"[E]"},Ta=/^[e]/,Oa={type:"class",value:"[e]",description:"[e]"},nc=" ",zc={type:"literal",value:" ",description:'" "'},oc="\t",hb={type:"literal",value:"\t",description:'"\\t"'},Kb="\n",Ya={type:"literal",value:"\n",description:'"\\n"'},Lb="\r",pc={type:"literal",value:"\r",description:'"\\r"'},Fb="\r\n",wa={type:"literal",value:"\r\n",description:'"\\r\\n"'},Ua={type:"any",description:"any character"},A=0,vb=[{line:1,sb:1,ic:!1}],ja=0,Zb=[],L=0,
Aa;if("startRule"in n){if(!(n.Bf in Ib))throw Error("Can't start parsing from rule \""+n.Bf+'".');da=Ib[n.Bf]}Aa=da();if(Aa!==y&&A===f.length)return Aa;Aa!==y&&A<f.length&&m({type:"end",description:"end of input"});throw function(f,g,h,k){function l(e){var f=1;for(e.sort(function(e,f){return e.description<f.description?-1:e.description>f.description?1:0});f<e.length;)e[f-1]===e[f]?e.splice(f,1):f++}function m(e,f){function g(e){function f(e){return e.charCodeAt(0).toString(16).toUpperCase()}return e.replace(/\\/g,
"\\\\").replace(/"/g,'\\"').replace(/\x08/g,"\\b").replace(/\t/g,"\\t").replace(/\n/g,"\\n").replace(/\f/g,"\\f").replace(/\r/g,"\\r").replace(/[\x00-\x07\x0B\x0E\x0F]/g,function(e){return"\\x0"+f(e)}).replace(/[\x10-\x1F\x80-\xFF]/g,function(e){return"\\x"+f(e)}).replace(/[\u0100-\u0FFF]/g,function(e){return"\\u0"+f(e)}).replace(/[\u1000-\uFFFF]/g,function(e){return"\\u"+f(e)})}var h=Array(e.length),k;for(k=0;k<e.length;k++)h[k]=e[k].description;h=1<e.length?h.slice(0,-1).join(", ")+" or "+h[e.length-
1]:h[0];k=f?'"'+g(f)+'"':"end of input";return"Expected "+h+" but "+k+" found."}null!==g&&l(g);return new e(null!==f?f:m(g,h),0,0,k)}(null,Zb,ja<f.length?f.charAt(ja):null,ja<f.length?k(ja,ja+1):k(ja,ja));}}})();
}(biovizWorkerNamespace));