var biovizWorkerNamespace = {};
(function(ns) {
var z,ea=[];function ga(e){return function(){return ea[e].apply(this,arguments)}}function ha(){if(this.constructor===ha)throw Error("Can't instanciate abstract class BiovizMap");}z=ha.prototype;z.set=function(){throw Error("Trying to call an abstract method");};z.get=function(){throw Error("Trying to call an abstract method");};z.remove=function(){throw Error("Trying to call an abstract method");};z.Gc=function(){throw Error("Trying to call an abstract method");};
z.keys=function(){throw Error("Trying to call an abstract method");};z.values=function(){throw Error("Trying to call an abstract method");};z.clear=function(){throw Error("Trying to call an abstract method");};z.rd=ga(2);function ja(){ha.call(this);this.ia=Object.create(null);this.Ff=Object.create(null);this.Ze={}.hasOwnProperty}ja.prototype=Object.create(ha.prototype);z=ja.prototype;z.constructor=ja;z.set=function(e,f){var g=Da(e);this.Gc(g);this.ia[g]=f;this.Ff[g]=e};
z.get=function(e){e=Da(e);return this.Gc(e)?this.ia[e]:null};z.remove=function(e){e=Da(e);if(this.Gc(e)){var f=this.ia[e];delete this.ia[e];delete this.Ff[e];return f}return null};z.Gc=function(e){e=Da(e);return this.Ze.call(this.ia,e)};z.keys=function(){var e=[],f;for(f in this.ia)e.push(f);return e};z.values=function(){var e=[],f;for(f in this.ia)e.push(this.ia[f]);return e};z.clear=function(){this.ia=Object.create(null);this.Ff=Object.create(null)};z.rd=ga(1);
function Da(e){if(e instanceof Array){e=[];for(var f=e.length,g=0;g<f;g++)e.push(e[g].wb());return e.join("")}return e instanceof Object?e.wb():e}function La(){ha.call(this);this.ia=[]}function Ta(e,f){this.key=e;this.value=f}La.prototype=Object.create(ha.prototype);z=La.prototype;z.constructor=La;
z.set=function(e,f){if(void 0===e)throw"ERROR: key cannot be undefined";var g;a:if(void 0!==e.nf)g=this.ia[e.nf];else{for(g in this.ia)if(this.ia[g].key===e){g=this.ia[g];break a}g=void 0}void 0===g?"object"===typeof e&&(e.nf=this.ia.push(new Ta(e,f))-1):g.value=f};z.get=function(e){if(void 0!==e.nf)return this.ia[e.nf].value;for(var f in this.ia)if(this.ia[f].key===e)return this.ia[f].value};z.keys=function(){var e=[],f;for(f in this.ia)e.push(this.ia[f].key);return e};
z.Gc=function(e){return-1!==this.keys().indexOf(e)};z.values=function(){var e=[],f;for(f in this.ia)e.push(this.ia[f].value);return e};z.remove=function(e){var f=-1,g;for(g in this.ia)if(this.ia[g].key===e){f=g;break}return 0<=f?this.ia.splice(f,1)[0].value:null};z.clear=function(){this.ia=[]};z.rd=ga(0);

function Ua(){this.pos=new THREE.Vector3;this.aa=this.Fa=this.Xb=this.v=this.u=this.kc=this.da=this.symbol=this.sa=this.fa=this.md=this.name=this.id=this.type=null}z=Ua.prototype;z.qa=function(){return this.id};z.pb=function(){return this.Fa};function Za(e,f){e.v!==f&&(e.v=f,null!==e.Fa&&e.Fa.Oc(f))}z.Ma=function(){return this.pos};z.nc=function(){if(null===this.aa){var e=parseFloat($a.Jc(this.symbol)[7]),f=new THREE.Vector3(-e,-e,-e),e=new THREE.Vector3(e,e,e);this.aa=new ab(f,e)}return this.aa};
z.radius=function(){return parseFloat($a.Jc(this.symbol)[7])};z.ob=function(){return this.Xb};function ib(e,f){if(e.Xb!==f&&(e.Xb=f,null!=e.Fa)){var g=e.Fa,h=e.Xb;if(g.Xb!=h){g.Xb=h;for(var k=g.u.length,n=0;n<k;n++)ib(g.u[n],h)}}}z.Wc=function(){return this.kc};z.Le=function(e){this.kc!=e&&(this.kc=e,null!==this.Fa&&this.Fa.Le(e))};z.we=function(){return this.u};z.ae=function(e){this.u!==e&&(this.u=e,null!==this.Fa&&this.Fa.ae(e))};z.toString=function(){return this.symbol+":"+this.id};
z.Ic=function(){return this.Fa.Ic()+":"+this.toString()};z.wb=function(){return this.symbol+":"+this.id+":"+this.u};z.distanceTo=function(e){return e instanceof Ua?Math.sqrt((this.pos.x-e.pos.x)*(this.pos.x-e.pos.x)+(this.pos.y-e.pos.y)*(this.pos.y-e.pos.y)+(this.pos.z-e.pos.z)*(this.pos.z-e.pos.z)):Math.sqrt((this.pos.x-e.x)*(this.pos.x-e.x)+(this.pos.y-e.y)*(this.pos.y-e.y)+(this.pos.z-e.z)*(this.pos.z-e.z))};
z.sub=function(e){return e instanceof Ua?new THREE.Vector3(this.pos.x-e.pos.x,this.pos.y-e.pos.y,this.pos.z-e.pos.z):new THREE.Vector3(this.pos.x-e.x,this.pos.y-e.y,this.pos.z-e.z)};z.add=function(e){return e instanceof Ua?new THREE.Vector3(this.pos.x+e.pos.x,this.pos.y+e.pos.y,this.pos.z+e.pos.z):new THREE.Vector3(this.pos.x+e.x,this.pos.y+e.y,this.pos.z+e.z)};z.clone=function(){return new THREE.Vector3(this.pos.x,this.pos.y,this.pos.z)};
function nb(){this.fa=null;this.u=new vb;this.aa=[];this.sa=this.v=this.da=null}z=nb.prototype;z.qc=function(){return this.fa};z.Me=function(e){this.fa=e;e=this.aa.length;for(var f=0;f<e;f++)f.Me(this.fa)};z.add=function(e){if(e instanceof Ua)return e=this.u.Gf(e),wb(this),e;e instanceof Fb?((null!==e.Zb&&e.Zb!==this||e.Zb===this)&&console.warn("ERROR: ",e,"already belongs to",e.Zb),null===e.Zb&&(this.aa.push(e),e.Me(this.fa),e.Zb=this,wb(this))):console.warn("ERROR : a is not an atom or a molecule")};
z.remove=function(e){e instanceof Ua?(e=this.u.findNode(atom),-1<e&&(delete this.u[e],wb(this))):e instanceof Fb&&(null===molecule&&console.warn("molecule null in function remove in model"),molecule.Zb===this&&(this.aa.splice(this.aa.Da(molecule),1),molecule.Me(null),molecule.Zb=null,wb(this)))};z.xa=function(){return this.u.values()};
z.dc=function(){if(!this.sa){this.u.Kj();this.v=this.nc();for(var e=new Mb(this.v.ye(),this.v.xe(),32),f=this.xa(),g=f.length,h=0;h<g;h++)e.add(new Nb(f[h]));e.optimize();g=f.length;for(h=0;h<g;h++)for(var k=f[h],n=k.symbol,n=n.charAt(0).toUpperCase()+n.slice(1).toLowerCase(),m=parseFloat($a.Jc(n)[6]),q=e.fh(k.pos,5),r=q.length,t=0;t<r;t++){var x=q[t].getPoint();if(x!==k){var n=x.symbol,n=n.charAt(0).toUpperCase()+n.slice(1).toLowerCase(),n=parseFloat($a.Jc(n)[6]),w=k.distanceTo(x);if(w>=m+n-.4&&
w<=m+n+.4){var n=k,w=this.u.findNode(n),E=this.u.findNode(x);void 0!==w&&void 0!==E||console.warn("Couldn't find atoms ",n," and/or ",x," in model ",this);w.Oi(E)||this.u.Lg(w,E).setAttribute("BondType","SIMPLE")}}}this.sa=!0}return this.u};function wb(e){e.da=null;e.v=null;e.sa=!1}z.Ma=function(){if(null===this.da){this.da=new THREE.Vector3;for(var e=this.xa(),f=0,g=0,h=0,k=e.length,n=0;n<k;n++)var m=e[n].pos,f=f+parseInt(m.x),g=g+parseInt(m.y),h=h+parseInt(m.z);this.da.set(f/k,g/k,h/k)}return this.da};
z.nc=function(){if(null===this.v){for(var e=new THREE.Vector3(Infinity,Infinity,Infinity),f=new THREE.Vector3(-Infinity,-Infinity,-Infinity),g=this.xa(),h=g.length,k=0;k<h;k++){var n=g[k].pos;e.x=Math.min(e.x,n.x);e.y=Math.min(e.y,n.y);e.z=Math.min(e.z,n.z);f.x=Math.max(f.x,n.x);f.y=Math.max(f.y,n.y);f.z=Math.max(f.z,n.z)}this.v=new ab(e,f)}return this.v};function Fb(e){this.id=e;this.Zb=this.da=this.type=null;this.ga=[];this.v=this.aa=this.u=null;this.Jg=!1}z=Fb.prototype;z.qa=function(){return this.id};
z.dc=function(){return this.Zb.dc()};z.Oc=function(e){if(this.id!==e){this.id=e;for(var f=0;f<this.ga.length;f++)this.ga[f].ae(e)}};z.qc=function(){return this.da};z.Me=function(e){this.da=e};z.add=function(e){null==e&&console.warn("residue is null in Molecule");null!==e.Ea&&e.Ea!==this&&console.warn(e," already belongs to ",e.Ea);null===e.Ea&&(this.ga.push(e),ec(e,this),fc(this))};
z.remove=function(e){null===e&&console.warn("residue is null in Molecule");e.Ea===this&&(this.ga.remove(e),ec(e,null),fc(this))};z.pb=function(e){for(var f=0;f<this.ga.length;f++){var g=this.ga[f];if(g.qa()==e)return g}return null};z.xa=function(){for(var e=[],f=this.ga.length,g=0;g<f;g++)e=e.concat(this.ga[g].xa());return e};z.size=function(){return this.ga.length};z.isEmpty=function(){return 0===this.size};function fc(e){e.u=null;e.aa=null;null!==e.Zb&&wb(e.Zb)}
z.Ma=function(){if(null===this.u){this.u=new THREE.Vector3;for(var e=this.xa(),f=e.length,g=0;g<f;g++){var h=e[g].pos;this.u.x+=h.x;this.u.y+=h.y;this.u.z+=h.z}this.u.x/=f;this.u.y/=f;this.u.z/=f}return this.u};
z.nc=function(){if(null===this.aa){for(var e=new THREE.Vector3(Infinity,Infinity,Infinity),f=new THREE.Vector3(-Infinity,-Infinity,-Infinity),g=this.xa(),h=g.length,k=0;k<h;k++){var n=g[k].pos;e.x=Math.min(e.x,n.x);e.y=Math.min(e.y,n.y);e.z=Math.min(e.z,n.z);f.x=Math.max(f.x,n.x);f.y=Math.max(f.y,n.y);f.z=Math.max(f.z,n.z)}this.aa=new ab(e,f)}return this.aa};z.toString=function(){return this.type+":"+this.id};z.wb=function(){return this.toString()};z.Ic=function(){return this.da.Ic()+":"+this.toString()};
z.ri=function(){if(null!==this.type&&"Protein"===this.type&&!this.Jg){if(null===this.v){var e=this.ga,f=e.length;this.v=new vb;for(var g=1;g<f;g++){var h=e[g-1],k=e[g],n=this.v.findNode(k);null==n&&(n=this.v.Ng(k.toString(),k));var m=k.gc("CA"),q=k.gc("N"),r=k.gc("H");if(h.qa()+h.ob().charCodeAt(0)===k.qa()+k.ob().charCodeAt(0)-1&&"PRO"!==h.aa){r=h.gc("C");h=h.gc("O");if(null==r||null==h)continue;r=r.sub(h);r=r.normalize();h=q.add(r);r=new Ua;r.name="H";r.symbol="H";r.pos.x=h.x;r.pos.y=h.y;r.pos.z=
h.z}if(null!=r)for(h=0;h<f;h++)if(h!=g&&h!=g-1){var t=e[h],k=this.v.findNode(t);null==k&&(k=this.v.Ng(t.toString(),t));var x=t.gc("CA"),w=t.gc("C"),E=t.gc("O");if(null!=x&&null!=w&&null!=E&&!(9<x.distanceTo(m))){var x=r.distanceTo(E),t=r.distanceTo(w),E=q.distanceTo(E),F=q.distanceTo(w),w=-9.9;.5>x||.5>t||.5>E||.5>F||(w=27.888/E,w+=27.888/t,w-=27.888/x,w-=27.888/F,-9.9>w&&(w=-9.9));if(-.5>w){var x=n.gk(k),G;null!=x?G=x.getAttribute("eH"):G=0;w<G&&(this.v.Lg(n,k,!0).setAttribute("eH",w),null!=x&&this.v.al(x))}}}}}e=
this.ga.length;for(f=0;f<e;f++)this.ga[f].rb=null;f=1;for(m=4;f+m<e;f++)if(gc(this,this.ga[f-1],this.ga[f-1+m])&&gc(this,this.ga[f],this.ga[f+m]))for(g=f;g<f+m;g++)this.ga[g].rb=D.u;for(f=1;f+1<e;f++)for(g=f+3;g+1<e;g++)if(n=this.ga[f],m=this.ga[g],null===n.rb&&null===m.rb)if(gc(this,this.ga[f-1],m)&&gc(this,m,this.ga[f+1])||gc(this,this.ga[g-1],n)&&gc(this,n,this.ga[g+1]))n.rb=D.aa,m.rb=D.aa;else if(gc(this,n,m)&&gc(this,m,n)||gc(this,this.ga[f-1],this.ga[g+1])&&gc(this,this.ga[g-1],this.ga[f+1]))n.rb=
D.v,m.rb=D.v;f=1;for(m=3;f+m<e;f++)if(gc(this,this.ga[f-1],this.ga[f-1+m])&&gc(this,this.ga[f],this.ga[f+m])){n=!0;for(g=f;g<f+m;g++)if(null!=this.ga[g]){n=!1;break}for(g=f;g<f+m;g++)this.ga[g].rb=n?D.u:D.da}f=1;for(m=5;f+m<e;f++)if(gc(this,this.ga[f-1],this.ga[f-1+m])&&gc(this,this.ga[f],this.ga[f+m])){n=!0;for(g=f;g<f+m;g++)if(null!=this.ga[g]){n=!1;break}for(g=f;g<f+m;g++)this.ga[g].rb=n?D.u:D.da}for(m=3;5>=m;m++)for(f=0;f+m<e;f++)if(gc(this,this.ga[f],this.ga[f+m]))for(g=f+1;g<f+m;g++)n=this.ga[g].rb,
null==n&&(this.ga[g].rb=D.da);for(f=0;f<e;f++)n=this.ga[f].rb,null==n&&(this.ga[f].rb=D.fa);this.Jg=!0}};function gc(e,f,g){f=e.v.findNode(f);return null==f?!1:f.nk(e.v.findNode(g))}z.Sd=function(e){void 0===e&&(e=!0);for(var f="",g=this.ga,h=0,k="\x00",n=this.vd()?"X":this.Ae()?"N":"-",m=g.length,q=0;q<m;q++){var r=g[q];if(e&&0!=q)for(h=r.qa()-h+r.ob().charCodeAt(0)-k.charCodeAt(0);1<h--;)f+=n;f+=r.Mi();h=r.qa();k=r.ob()}return f};z.Ae=function(){return"DNA"==this.type||"RNA"==this.type};
z.vd=function(){return"Protein"==this.type||"Peptide"==this.type||"Small Peptide"==this.type};z.$i=function(){return this.Ae()||this.vd()};z.Zi=function(){return"Ligand"===this.type};z.yj=function(e){var f=new qc,g=[];g.push(new rc(this.toString(),this.Sd(!1)));g.push(new rc("ExternalSequence",e));f=f.da(g);e=f.Sd("ExternalSequence");f=f.Sd(this.toString());console.log(e,f);this.fa=f;console.log(f.fa())};
function sc(e){for(var f=[],g=0,h=e.ga,k=0,n=0;n<h.length;n++){var m=h[n];if(null===m.type)k++;else{var q=f[m.type];void 0===q&&(q=0,f[m.type]=q,g++);f[m.type]++}}if(0!==g){var g=Infinity,r;for(q in f)h=f[q],0!==h&&h<g?(g=h,r=q):h===g&&q<r&&(r=q);g>=k&&("Protein"==r?(f=e.size(),e.type=20>f?"Small Peptide":60>f?"Peptide":"Protein"):e.type=r)}}function tc(){this._id=this.da=this.kc=this.Ea=this.rb=this.type=this.aa=null;this.Xb="\x00";this.u=[];this.sa=new ja;this.ya=this.fa=this.v=null}
function yc(e,f){e.da=f.Jb;e._id=f.tb;e.Xb=f.Lb}z=tc.prototype;z.dc=function(){return this.Ea.dc()};function ec(e,f){e.Ea=f;null!==f&&void 0!==f&&e.ae(f.qa())}z.qa=function(){return this._id};z.Oc=function(e){if(this._id!=e){this._id=e;for(var f=0;f<this.u.length;f++)Za(this.u[f],e)}};z.ob=function(){return this.Xb};z.Wc=function(){return this.kc};z.Le=function(e){if(this.kc!=e){this.kc=e;for(var f=this.u.length,g=0;g<f;g++)g.Le(e)}};z.we=function(){return this.da};
z.ae=function(e){if(this.da!=e){this.da=e;null!==this.Ea&&this.Ea.Oc(e);for(var f=this.u.length,g=0;g<f;g++)g.ae(e)}};z.add=function(e){null===e&&console.warn("atom = null in Residue");null!==e.pb()&&e.pb()!==this&&console.warn(e," already belongs to ",e.pb());if(null===e.pb()){this.u.push(e);var f=new Fc(e.name,e.md);this.sa.Gc(f)||this.sa.set(f,e);e.Fa=this;null!==this&&(Za(e,e.Fa.qa()),ib(e,e.Fa.ob()),e.Le(e.Fa.Wc()),e.ae(e.Fa.we()))}};
z.remove=function(e){null===e&&console.warn("atom = null in Residue");if(e.pb()===this){this.u.remove(e);var f=new this.yb(e.name,e.md);this.sa.remove(f,e)}};z.xa=function(){return this.u};z.ck=function(e){for(var f=0;f<this.u.length;f++){var g=this.u[f];if(g.qa()==e)return g}return null};z.gc=function(e){var f=void 0;void 0===f&&(f="\x00");e=this.sa.get(new Fc(e,f));if(null!==e)return e};
z.Ma=function(){if(null==this.v){this.v=new THREE.Vector3;for(var e=this.u.length,f=0;f<e;f++){var g=this.u[f].pos;this.v.x+=g.x;this.v.y+=g.y;this.v.z+=g.z}this.v.x/=e;this.v.y/=e;this.v.z/=e}return this.v};
z.hh=function(){if(null==this.fa)for(var e=this.u.length,f=0;f<e;f++){var g=this.u[f];if("CA"===g.name){this.fa=g.pos.clone();break}}if(null==this.fa){for(var h=this.Ma(),k=this.u[0],n=h.distanceTo(k.pos),e=this.u.length,f=0;f<e;f++){var g=this.u[f],m=h.distanceTo(g.pos);m<n&&(k=g,n=m)}this.fa=k.clone()}return this.fa};
z.nc=function(){if(null===this.ya){for(var e=new THREE.Vector3(Infinity,Infinity,Infinity),f=new THREE.Vector3(-Infinity,-Infinity,-Infinity),g=this.u.length,h=0;h<g;h++){var k=this.u[h];e.x=Math.min(e.x,k.pos.x);e.y=Math.min(e.y,k.pos.y);e.z=Math.min(e.z,k.pos.z);f.x=Math.max(f.x,k.pos.x);f.y=Math.max(f.y,k.pos.y);f.z=Math.max(f.z,k.pos.z)}this.ya=new ab(e,f)}return this.ya};z.Ae=function(){return"DNA"==this.type||"RNA"==this.type};
z.vd=function(){return"Protein"==this.type||"Peptide"==this.type||"Small Peptide"==this.type};
z.Mi=function(){switch(null!==this.aa?this.aa:this.kc){case "GLY":return"G";case "ALA":return"A";case "VAL":return"V";case "LEU":return"L";case "ILE":return"I";case "PRO":return"P";case "PHE":return"F";case "MET":return"M";case "TRP":return"W";case "SER":return"S";case "THR":return"T";case "ASN":return"N";case "GLN":return"Q";case "ASP":return"D";case "GLU":return"E";case "CYS":return"C";case "TYR":return"Y";case "HIS":return"H";case "LYS":return"K";case "ARG":return"R";case "ASX":return"B";case "GLX":return"Z";
case "A":case "DA":case "+A":return"A";case "C":case "DC":case "+C":return"C";case "G":case "DG":case "+G":return"G";case "T":case "DT":case "+T":return"T";case "U":case "DU":case "+U":return"U";case "I":case "DI":case "+I":return"I"}return null!=this.Ea.type&&"Protein"===this.Ea.type?"X":null==this.Ea.type||"RNA"!==this.Ea.type&&"DNA"!==this.Ea.type?"?":"N"};z.toString=function(){return this.kc+":"+this._id};z.wb=function(){return this.kc+":"+this._id+":"+this.da};
z.Ic=function(){return this.Ea.Ic()+":"+this.toString()};function Fc(e,f){this.name=e;this.md=f}Fc.prototype.toString=function(){return this.name+":"+this.md};Fc.prototype.wb=function(){return this.name+":"+this.md};
function Gc(e,f){null===e.aa&&console.warn("Error : stdResName must be set before guessing residue type");if(-1!==Hc.indexOf(e.aa))e.type="DNA";else if(-1!==Ic.indexOf(e.aa))e.type="RNA";else if(-1!==Oc.indexOf(e.aa))e.type="Protein";else if(-1!==Pc.indexOf(e.Wc()))e.type="Solvent";else if(-1!==Tc.indexOf(e.Wc()))e.type=null;else{var g=f.get(e.qa());null!=g&&g.name.endsWith(" ION")&&(e.type="Ion");e.type="Ligand"}}
var Oc="GLY ALA VAL LEU ILE PRO PHE MET TRP SER THR ASN GLN ASP GLU CYS TYR HIS LYS ARG".split(" "),Ic=["A","C","G","U","I"],Hc="DA DC DG DT DI DU +A +C +G +T +I +U T".split(" "),Tc="UNK ASX GLX N DN UNL UNX".split(" "),Pc=["HOH","DOD","GOL","EDO"];
function Uc(e,f,g){null===e&&console.warn("chainId null in Residue.Id");this.Jb=e;this.tb=f;this.Lb=g;this.toString=function(){return"\x00"!==this.Lb.charCodeAt(0)?this.Jb+":"+this.tb+":"+this.Lb:this.Jb+":"+this.tb};this.wb=function(){return"\x00"!==this.Lb.charCodeAt(0)?this.Jb+":"+this.tb+":"+this.Lb:this.Jb+":"+this.tb}}function D(e,f){this.name=e;this.code=f}D.fa=new D("Coil"," ");D.da=new D("Turn","T");D.u=new D("Helix","H");D.aa=new D("Strand","x");D.v=new D("Strand","X");
D.prototype.toString=function(){return name};function Vc(){this.Lk=!0;this.ii=this._id=this.Ig=null;this.aa=[];this.ci=[];this.cf=new ja;this.$e=new ja;this.Jd=new ja;this.zj=[];this.v=[];this.da=new ja;this.u=null}z=Vc.prototype;z.Ma=function(){if(null===this.u){this.u=new THREE.Vector3;for(var e=this.v[0].aa,f=0;f<e.length;f++){var g=e[f].Ma();this.u.x+=g.x;this.u.y+=g.y;this.u.z+=g.z}this.u.x/=e.length;this.u.y/=e.length;this.u.z/=e.length}return this.u};z.dc=function(){return this.v[0].dc()};
z.qa=function(){return this._id};z.Oc=function(e){null==this._id&&(this.Ig=e);this._id=e};z.Ph=function(){};z.setDate=function(){};z.lj=function(e){this.ii=e};z.ll=function(){};z.li=function(e,f){null==(null==e?this.aa:this.aa[e])&&(this.aa[e]=f)};z.il=function(e){this.ci=e};z.add=function(e){null===e&&console.warn("Error on adding model to structure : model = NULL");null!=e.qc()&&e.qc()!=this&&console.warn(e," already belongs to ",e.qc());null==e.qc()&&(this.v.push(e),e.Me(this))};
z.remove=function(e){null===e&&console.warn("Error on removing structure");e.qc()==this&&(this.v.remove(e),e.Me(null))};z.Qf=function(){return this.v[0]};z.toString=function(){return this._id};z.wb=function(){return this.toString()};z.Ic=function(){return this.toString()};
z.Sj=function(e){this.cf.__proto__=ja.prototype;this.cf.Ze={}.hasOwnProperty;this.Jd.__proto__=ja.prototype;this.Jd.Ze={}.hasOwnProperty;this.$e.__proto__=ja.prototype;this.$e.Ze={}.hasOwnProperty;this.da.__proto__=ja.prototype;this.da.Ze={}.hasOwnProperty;for(var f=e.length,g=0;g<f;g++){var h=new nb;this.add(h);for(var k=e[g],n=k.length,m=0;m<n;m++){var q=new Ua;q.type=k[m][0];q.id=k[m][1];q.name=k[m][2];q.md=k[m][3];q.Le(k[m][4]);q.ae(k[m][5]);Za(q,k[m][6]);ib(q,k[m][7]);q.pos.x=k[m][8];q.pos.y=
k[m][9];q.pos.z=k[m][10];q.fa=k[m][11];q.sa=k[m][12];q.symbol=k[m][13];q.da=k[m][14];h.add(q)}}Wc(this)};
function Wc(e){var f=e.cf,g=e.$e,h=e.Jd,k=e.v,n=!1,m,q=k.length;for(m=0;m<q;m++){for(var r=k[m],t=[],x=r.xa(),w=x.length,E=0;E<w;E++){for(var F=x[E],G=void 0,I=void 0,I=0;I<t.length;I++){var C=t[I][0];if(C.qa()===F.v&&C.we()===F.we()&&C.ob().charCodeAt(0)===F.ob().charCodeAt(0)){G=C;break}}void 0===G&&(I=new Uc(F.we(),F.v,F.ob()),G=new tc,yc(G,I),G.Le(F.Wc()),C=f.get(I),G.aa=C?C.Wh:G.Wc(),Gc(G,g),C=h.get(I),null!=C?(n||(n=!0),G.rb=C):G.rb=D.fa,t.push([G,I]));G.add(F)}C=void 0;for(G=0;G<t.length;G++){x=
t[G][0];w=t[G][1];G=x;for(E=[];void 0!==G&&null!==G&&-1===E.indexOf(w)&&!G.vd()&&!G.Ae();)if(E.push(w),I=e.da.get(w),null!=I){for(var C=I.Da.Jb===w.Jb&&I.Da.tb===w.tb&&I.Da.Lb===w.Lb?I.rc:I.Da,K,I=0;I<t.length;I++)G=t[I],C.Jb===G.Jb&&C.tb===G.tb&&C.Lb===G.Lb&&(K=I);G=t[K][0]}void 0!==G&&G.type!==x.type&&(x.type=G.type)}G=[];for(I=0;I<t.length;I++){var C=t[I][0],x=C.we(),w=C.type+" "+x,H=G[w];void 0===H&&(H=new Fb(x),r.add(H),G[w]=H);H.add(C);H.Jg=n}for(H in G)r=G[H],r.ga.sort(function(e,f){return e.Eg<
f.Eg?-1:e.Eg>f.Eg?1:e._id<f._id?-1:e._id>f._id?1:e.Xb<f.Xb?-1:e.Xb>f.Xb?1:0}),sc(r)}};

function Hk(){this.Ai=this.bh=this.zi=this.ah=this.$g=this.Zg=this.Kf=this.qh=this.Oh=this.ph=this.Nh=this.gf=null}function Ik(e){this.la=this.file=null;this.Yc=[];this.source=this.Rg=this.uh=this.title=null;this.ready=!1;this.Ud=[];this.Ud[Jk.id]=Jk;this.ze=[];this.resolution=null;null==e&&(e=!1);this.Dg=e;this.bi=null}var Kk=1;
Ik.prototype.parse=function(e,f){this.bi=f;this.la=new Vc;a:{var g=e.split("\n"),h,k=null,n;for(n in g){var m=g[n];if(m===this.Ol||m===this.Ll)break a;if(m===this.Ml){this.Yc.push([]);break a}var q=m.substring(0,6).trim(),r=null,t="";switch(q){case "ATOM":case "HETATM":var r=m.substring(76,78).trim(),x=m.substring(12,16).trim();""===r&&(r=x[0]);var w=this.Yc[this.Yc.length-1];void 0===w&&(w=[],this.Yc.push(w));if(this.Dg&&"CA"!==x)break;if(!(null!==r&"H"===r)||this.aj){var E=[],t=m.charAt(21);E.push(q);
E.push(m.substring(6,11).trim());E.push(x);E.push(" "!=m.charAt(16)?m.charAt(16):"\x00");E.push(m.substring(17,20).trim());E.push(t);E.push(parseFloat(m.substring(22,26).trim()));E.push(" "!=m.charAt(26)?m.charAt(26):"\x00");E.push(parseFloat(m.substring(30,38).trim()));E.push(parseFloat(m.substring(38,46).trim()));E.push(parseFloat(m.substring(46,54).trim()));E.push(m.substring(54,60).trim());E.push(m.substring(60,66).trim());E.push(r);79<=m.length&&E.push(toString(m.charAt(79))+toString(m.charAt(78)));
w.push(E)}break;case "HEADER":59<m.length?(this.la.Ph(m.substring(10,50).trim()),this.la.Oc(m.substring(62,66).trim())):(this.la.Ph(m.substring(10).trim()),this.la.Oc(file.getName().replaceAll("\\..*$","").toUpperCase()));this.la.setDate(m.substring(50,59));break;case "TITLE":this.title=null===this.title?m.substring(10):this.title+(" "+m.substring(10));this.la.lj(this.title);break;case "SOURCE":this.source+=m.substring(10);break;case "KEYWDS":this.uh+=m.substring(10);break;case "AUTHOR":this.Rg+=
m.substring(10);break;case "REMARK":m.substring(7,10).trim();if(~m.indexOf("RESOLUTION."))try{m.substring(m.indexOf("RESOLUTION.")+12).trim()}catch(F){console.warn("Error : ",F)}break;case "DBREF":k=new Hk;k.gf=m.charAt(12);k.Nh=m.substring(14,18).trim();k.ph=" "!==m.charAt(18)?m.charAt(18):"\x00";k.Oh=m.substring(20,24).trim();k.qh=" "!=m.charAt(24)?m.charAt(24):"\x00";k.Kf=m.substring(26,32).trim();k.Zg=m.substring(33,41).trim();k.$g=m.substring(42,54).trim();k.ah=m.substring(55,60).trim();k.zi=
" "!=m.charAt(60)?m.charAt(60):"\x00";k.bh=m.substring(62,67<=m.length?67:m.length).trim();k.Ai=68<=m.length?m.charAt(67):"\x00";this.la.li(k.gf,k);break;case "DBREF1":k=new Hk;k.gf=m.charAt(12);k.Nh=m.substring(14,18).trim();k.ph=" "!=m.charAt(18)?m.charAt(18):"\x00";k.Oh=m.substring(20,24).trim();k.qh=" "!=m.charAt(24)?m.charAt(24):"\x00";k.Kf=m.substring(26,32).trim();k.$g=m.substring(47,67<=m.length?67:m.length).trim();this.la.li(k.gf,k);break;case "DBREF2":k.Zg=m.substring(18,40).trim();k.ah=
m.substring(45,55).trim();k.bh=m.substring(57,67<=m.length?67:m.length).trim();break;case "MODRES":r=new Lk;r.name=m.substring(12,15).trim();t=m.charAt(16);q=m.substring(18,22).trim();x=" "!=m.charAt(22)?m.charAt(22):"\x00";r.Wh=m.substring(24,27).trim();r.description=30<=m.length?m.substring(29).trim():null;this.la.cf.set(new Mk(t,q,x),r);break;case "HET":t=m.substring(7,10).trim();for(h in this.Ud)if(h[0]===t){r=h[1];break}null===r&&(r=new Nk,r.id=t,r.description=31<=m.length?m.substring(30):null,
this.Ud[t]=r);t=m.charAt(12);q=m.substring(13,17).trim();x=" "!=m.charAt(17)?m.charAt(17):"\x00";this.la.$e.set(new Mk(t,q,x),r);break;case "HETNAM":t=m.substring(11,14).trim();r=this.Ud[t];r.name=null===r.name?m.substring(15):r.name+m.substring(15);break;case "HETSYN":t=m.substring(11,14).trim();this.ze[t]=void 0===this.ze[t]?m.substring(15):this.ze[t]+m.substring(15);break;case "FORMUL":t=m.substring(12,15).trim();r=this.Ud[t];r.Nf=null===r.Nf?m.substring(19):r.Nf+m.substring(19);break;case "HELIX":t=
m.charAt(19);r=parseInt(m.substring(21,25));q=m.charAt(25);" "===q&&(q="\x00");h=parseInt(m.substring(33,37));r=parseInt(r);x=parseInt(h);for(h=r;h<=x;h++)this.la.Jd.set(new Mk(t,h,q),D.u);break;case "SHEET":for(t=m.charAt(21),r=parseInt(m.substring(22,26)),q=m.charAt(26)," "===q&&(q="\x00"),h=parseInt(m.substring(33,37)),m=-1===parseInt(m.substring(38,40))?D.v:D.aa,r=parseInt(r),x=parseInt(h),h=r;h<=x;h++)this.la.Jd.set(new Mk(t,h,q),m)}}this.finish();this.ready=!0}};
Ik.prototype.finish=function(){this.la.il(this.la.ci.concat(null));this.Rg=this.uh=this.source=null;for(var e in this.ze){var f=this.Ud[e];f.oj=f.oj.concat(this.ze[e].split("\\s*;\\s*"))}this.ze=this.Ud=null;null==this.la._id&&(this.la.Oc("Unknown_"+Kk),Kk++);this.bi.apply(this,[this.la,this.Yc])};function Lk(){this.description=this.Wh=this.name=null}
function Ok(e){this.la=null;this.Yc=[];this.mh=!1;this.ff=null;this.Ha=[];this.aj=!1;this.Xk=!0;this.qj=[];this.og=[];this.mj=new ja;null==e&&(e=!1);this.Dg=e}Ok.prototype.parse=function(e,f){this.la=new Vc;this.og[Jk.id]=Jk;Pk.parse(e,this);f.apply(this,[this.la,this.Yc])};function Qk(e,f,g){if(!e.mh){var h=f.split(".",2);null!==e.ff&&e.ff!==h[0]&&Rk(e);e.ff=h[0]}e.Ha[f]=g}function Rk(e){null!==e.ff&&(Sk(e),e.Ha=[],e.ff=null)}function Tk(e,f){var g=parseInt(e.Ha[f]);isNaN(g)&&(g=0);return g}
Ok.prototype.getFloatValue=function(e){e=parseFloat(this.Ha[e]);isNaN(e)&&(e=0);return e};Ok.prototype.getStringValue=function(e,f){var g=this.Ha[e];null==g&&null!=f&&(g=this.Ha[f]);if("."===g||"?"===g)return"\x00";void 0!==g&&(g=g.replace('"',""));return g};
function Sk(e){if(void 0!==e.Ha["_atom_site.id"]){var f=parseInt(e.Ha["_atom_site.pdbx_PDB_model_num"]);if(!(e.Xk&&1<f)){var g=e.Yc[f-1];void 0===g&&(g=[],e.Yc[f-1]=g);if(!e.Dg||"CA"===e.getStringValue("_atom_site.label_atom_id")){var f=[],h=e.getStringValue("_atom_site.type_symbol");null!==h&"H"===h&&!e.aj||(f.push(e.getStringValue("_atom_site.group_PDB")),f.push(Tk(e,"_atom_site.id")),f.push(e.getStringValue("_atom_site.auth_atom_id","_atom_site.label_atom_id").replace(/"/g,"")),f.push(e.getStringValue("_atom_site.label_alt_id").replace(/"/g,
"")),f.push(e.getStringValue("_atom_site.auth_comp_id","_atom_site.label_comp_id")),f.push(e.getStringValue("_atom_site.auth_asym_id","_atom_site.label_asym_id")),f.push(Tk(e,"_atom_site.auth_seq_id")),f.push(e.getStringValue("_atom_site.pdbx_PDB_ins_code")),f.push(e.getFloatValue("_atom_site.Cartn_x")),f.push(e.getFloatValue("_atom_site.Cartn_y")),f.push(e.getFloatValue("_atom_site.Cartn_z")),f.push(e.getFloatValue("_atom_site.occupancy")),f.push(e.getFloatValue("_atom_site.B_iso_or_equiv")),f.push(e.getStringValue("_atom_site.type_symbol")),
f.push(Tk(e,"_atom_site.pdbx_formal_charge")),g.push(f))}}}else if(void 0!==e.Ha["_struct_keywords.entry_id"])e.la.Ph(e.getStringValue("_struct_keywords.pdbx_keywords")),null!==e.getStringValue("_struct_keywords.text")&&e.getStringValue("_struct_keywords.text");else if(void 0!==e.Ha["_audit_author.name"])e.la.zj.push(e.getStringValue("_audit_author.name"));else if(void 0!==e.Ha["_database_PDB_rev.num"])g=e.getStringValue("_database_PDB_rev.date_original"),null!==g&&e.la.setDate(g);else if(void 0!==
e.Ha["_struct.entry_id"])e.la.lj(e.getStringValue("_struct.title"));else if(void 0!==e.Ha["_refine.entry_id"])e.la.ll(e.getFloatValue("_refine.ls_d_res_high",NaN));else if(void 0!==e.Ha["_entity.id"])"polymer"===e.Ha["_entity.type"]&&(g=Tk(e,"_entity.id"));else if(void 0===e.Ha["_entity_poly.entity_id"]&&void 0===e.Ha["_entity_name_com.entity_id"])if(void 0!==e.Ha["_struct_ref.id"])g=Tk(e,"_struct_ref.id"),f=new Hk,e.qj[g]=f,f.Kf=e.getStringValue("_struct_ref.db_name"),f.$g=e.getStringValue("_struct_ref.db_code"),
f.Zg=e.getStringValue("_struct_ref.pdbx_db_accession");else if(void 0!==e.Ha["_struct_ref_seq.align_id"])g=Tk(e,"_struct_ref_seq.ref_id"),f=e.qj[g],f.gf=e.getStringValue("_struct_ref_seq.pdbx_strand_id"),f.Nh=Tk(e,"_struct_ref_seq.seq_align_beg"),f.ph=e.getStringValue("_struct_ref_seq.pdbx_seq_align_beg_ins_code"),f.Oh=Tk(e,"_struct_ref_seq.seq_align_end"),f.qh=e.getStringValue("_struct_ref_seq.pdbx_seq_align_end_ins_code"),f.ah=Tk(e,"_struct_ref_seq.db_align_beg"),f.zi=e.getStringValue("_struct_ref_seq.pdbx_db_align_beg_ins_code"),
f.bh=Tk(e,"_struct_ref_seq.db_align_end"),f.Ai=e.getStringValue("_struct_ref_seq.pdbx_db_align_end_ins_code");else if(void 0!==e.Ha["_pdbx_struct_mod_residue.id"]){f=new Lk;f.name=e.getStringValue("_pdbx_struct_mod_residue.auth_comp_id");f.Wh=e.getStringValue("_pdbx_struct_mod_residue.parent_comp_id");f.description=e.getStringValue("_pdbx_struct_mod_residue.details");var g=e.getStringValue("_pdbx_struct_mod_residue.auth_asym_id"),h=Tk(e,"_pdbx_struct_mod_residue.auth_seq_id"),k=e.getStringValue("_pdbx_struct_mod_residue.PDB_ins_code");
e.la.cf.set(new Mk(g,h,k),f)}else if(void 0!==e.Ha["_pdbx_nonpoly_scheme.asym_id"])g=e.getStringValue("_pdbx_nonpoly_scheme.mon_id"),f=e.og[g],void 0===f&&(f=new Nk,f.id=g,e.og[g]=f),g=e.getStringValue("_pdbx_nonpoly_scheme.pdb_strand_id"),h=Tk(e,"_pdbx_nonpoly_scheme.pdb_seq_num"),k=e.getStringValue("_pdbx_nonpoly_scheme.pdb_ins_code"),e.la.$e.set(new Mk(g,h,k),f);else if(void 0!==e.Ha["_chem_comp.id"])g=e.getStringValue("_chem_comp.id"),f=e.og[g],void 0!==f&&(f.name=e.getStringValue("_chem_comp.name"),
null!=e.getStringValue("_chem_comp.pdbx_synonyms")&&e.getStringValue("_chem_comp.pdbx_synonyms"),f.Nf=e.getStringValue("_chem_comp.formula"));else if(void 0===e.Ha["_struct_conn.id"])if(void 0!==e.Ha["_struct_conf.id"]){e.getStringValue("_struct_conf.conf_type_id");var g=e.getStringValue("_struct_conf.beg_auth_asym_id"),n=Tk(e,"_struct_conf.beg_auth_seq_id"),f=e.getStringValue("_struct_conf.pdbx_beg_PDB_ins_code");e.getStringValue("_struct_conf.end_auth_asym_id");k=Tk(e,"_struct_conf.end_auth_seq_id");
e.getStringValue("_struct_conf.pdbx_end_PDB_ins_code");for(var m=parseInt(n),k=parseInt(k);m<=k;m++)e.la.Jd.set(new Mk(g,m,f),D.u)}else if(void 0!==e.Ha["_struct_sheet_range.id"])for(h=D.aa,g=e.getStringValue("_struct_sheet_range.beg_auth_asym_id"),n=Tk(e,"_struct_sheet_range.beg_auth_seq_id"),f=e.getStringValue("_struct_sheet_range.pdbx_beg_PDB_ins_code"),e.getStringValue("_struct_sheet_range.end_auth_asym_id"),k=Tk(e,"_struct_sheet_range.end_auth_seq_id"),e.getStringValue("_struct_sheet_range.pdbx_end_PDB_ins_code"),
m=e.getStringValue("_struct_sheet_range.id"),m=e.mj.get(new Mk(g,m,"0")),"anti-parallel"===m&&(h=D.v),m=parseInt(n),k=parseInt(k);m<=k;m++)e.la.Jd.set(new Mk(g,m,f),h);else void 0!==e.Ha["_struct_sheet_order.sheet_id"]&&(g=e.getStringValue("_struct_sheet_order.sheet_id"),e.getStringValue("_struct_sheet_order.range_id_1"),f=e.getStringValue("_struct_sheet_order.range_id_2"),m=e.getStringValue("_struct_sheet_order.sense"),e.mj.set(new Mk(g,f,"\x00"),m))}
function Mk(e,f,g){null===e&&console.warn("chainId null in Residue.Id");this.Jb=e;this.tb=f;this.Lb=g;this.toString=function(){return"\x00"!==this.Lb.charCodeAt(0)?this.Jb+":"+this.tb+":"+this.Lb:this.Jb+":"+this.tb};this.wb=function(){return"\x00"!==this.Lb.charCodeAt(0)?this.Jb+":"+this.tb+":"+this.Lb:this.Jb+":"+this.tb}}
onmessage=function(e){function f(e,f){postMessage(JSON.stringify(e));postMessage(JSON.stringify(f))}var g=e.data[0],h=e.data[2],k;k=e.data[1]?new Ok:new Ik;if(h)k.parse(g,f);else{var n=new XMLHttpRequest;n.open("GET",g,!0);n.onreadystatechange=function(){var e=n.status;if(4==n.readyState)if(200==e)postMessage(new Blob([n.responseText],{type:"text/plain"})),k.parse(n.responseText,f);else{var h={type:"error",msg:""};switch(e){case 404:h.msg="File not found, "+g;break;case 500:h.msg="Server error";break;
case 0:h.msg="Request aborted";break;default:h.msg="Unknown error "+e}postMessage(JSON.stringify(h))}};n.send(null)}};function Nk(){this.name=this.id=null;this.oj=[];this.description=this.Nf=null}var Jk=new Nk;Jk.id="HOH";Jk.name="WATER";D=function(e,f){this.name=e;this.code=f};D.fa=new D("Coil"," ");D.da=new D("Turn","T");D.u=new D("Helix","H");D.aa=new D("Strand","x");D.v=new D("Strand","X");D.prototype.toString=function(){return name};
var Pk=function(){function e(f,g,h,k){this.message=f;this.location=k;this.name="SyntaxError";"function"===typeof Error.captureStackTrace&&Error.captureStackTrace(this,e)}(function(e,g){function h(){this.constructor=e}h.prototype=g.prototype;e.prototype=new h})(e,Error);return{SyntaxError:e,parse:function(f,g){function h(e){var g=ub[e],h,k;if(g)return g;for(h=e-1;!ub[h];)h--;g=ub[h];for(g={line:g.line,mb:g.mb,bc:g.bc};h<e;)k=f.charAt(h),"\n"===k?(g.bc||g.line++,g.mb=1,g.bc=!1):"\r"===k||"\u2028"===
k||"\u2029"===k?(g.line++,g.mb=1,g.bc=!0):(g.mb++,g.bc=!1),h++;return ub[e]=g}function k(e,f){var g=h(e),k=h(f);return{start:{offset:e,line:g.line,mb:g.mb},end:{offset:f,line:k.line,mb:k.mb}}}function n(e){A<fa||(A>fa&&(fa=A,Yb=[]),Yb.push(e))}function m(){var e,g,h,k,l,n,m;e=U();if(e===y&&(e=P(),e===y))if(e=A,g=q(),g!==y){h=A;k=[];l=A;n=P();n!==y?(m=q(),m!==y?l=n=[n,m]:(A=l,l=y)):(A=l,l=y);for(;l!==y;)k.push(l),l=A,n=P(),n!==y?(m=q(),m!==y?l=n=[n,m]:(A=l,l=y)):(A=l,l=y);h=k!==y?f.substring(h,A):
k;if(h!==y){k=[];for(l=P();l!==y;)k.push(l),l=P();k!==y?e=g=[g,h,k]:(A=e,e=y)}else A=e,e=y}else A=e,e=y;return e}function q(){var e,g,h,k,l,m;k=h=g=e=A;var q,w,x,C,E;m=l=A;Kc.test(f.charAt(A))?(q=f.charAt(A),A++):(q=y,0===J&&n(ic));q===y&&(Ab.test(f.charAt(A))?(q=f.charAt(A),A++):(q=y,0===J&&n(jc)));q!==y?(Ia.test(f.charAt(A))?(w=f.charAt(A),A++):(w=y,0===J&&n(Va)),w===y&&(fb.test(f.charAt(A))?(w=f.charAt(A),A++):(w=y,0===J&&n(ia))),w!==y?(ba.test(f.charAt(A))?(x=f.charAt(A),A++):(x=y,0===J&&n(da)),
x===y&&(Ba.test(f.charAt(A))?(x=f.charAt(A),A++):(x=y,0===J&&n(Bb))),x!==y?(Ia.test(f.charAt(A))?(C=f.charAt(A),A++):(C=y,0===J&&n(Va)),C===y&&(fb.test(f.charAt(A))?(C=f.charAt(A),A++):(C=y,0===J&&n(ia))),C!==y?(pb.test(f.charAt(A))?(E=f.charAt(A),A++):(E=y,0===J&&n(qa)),E!==y?m=q=[q,w,x,C,E]:(A=m,m=y)):(A=m,m=y)):(A=m,m=y)):(A=m,m=y)):(A=m,m=y);l=m!==y?f.substring(l,A):m;k=l!==y?f.substring(k,A):l;if(k!==y){l=A;k=[];m=F();if(m!==y)for(;m!==y;)k.push(m),m=F();else k=y;l=k!==y?f.substring(l,A):k;l!==
y?(W.fe.la.Oc(l),h=void 0):(A=h,h=y)}else A=h,h=y;g=h!==y?f.substring(g,A):h;if(g!==y){h=[];k=A;l=P();l!==y?(m=t(),m===y&&(m=r()),m!==y?k=l=[l,m]:(A=k,k=y)):(A=k,k=y);for(;k!==y;)h.push(k),k=A,l=P(),l!==y?(m=t(),m===y&&(m=r()),m!==y?k=l=[l,m]:(A=k,k=y)):(A=k,k=y);h!==y?e=g=[g,h]:(A=e,e=y)}else A=e,e=y;return e}function r(){var e,g,h,k,l,m;g=e=A;h=Sb();h!==y?(k=A,l=F(),k=l!==y?f.substring(k,A):l,k!==y?g=h=[h,k]:(A=g,g=y)):(A=g,g=y);if(g!==y){h=[];k=A;l=P();l!==y?(m=t(),m!==y?k=l=[l,m]:(A=k,k=y)):(A=
k,k=y);if(k!==y)for(;k!==y;)h.push(k),k=A,l=P(),l!==y?(m=t(),m!==y?k=l=[l,m]:(A=k,k=y)):(A=k,k=y);else h=y;h!==y?(k=P(),k!==y?(l=Sb(),l!==y?e=g=[g,h,k,l]:(A=e,e=y)):(A=e,e=y)):(A=e,e=y)}else A=e,e=y;return e}function t(){var e,g,h,k;e=A;g=Gb();g!==y&&(g=W.fe,Rk(g),g.mh=!0,W.yh=[],W.i=0,g=void 0);if(g!==y){h=[];g=x();if(g!==y)for(;g!==y;)h.push(g),g=x();else h=y;if(h!==y){g=[];for(h=w();h!==y;)g.push(h),h=w();g!==y?(e=W.fe,e.mh=!1,e.Ha=[],e=void 0):(A=e,e=y)}else A=e,e=y}else A=e,e=y;e===y&&(g=e=A,
h=oa(),g=h!==y?f.substring(g,A):h,g!==y?(h=P(),h!==y?(h=A,k=ma(),h=k!==y?f.substring(h,A):k,h!==y?(Qk(W.fe,g,h),e=void 0):(A=e,e=y)):(A=e,e=y)):(A=e,e=y));return e}function x(){var e,f;e=A;f=P();f!==y?(f=oa(),f!==y?(W.yh.push(f),e=void 0):(A=e,e=y)):(A=e,e=y);return e}function w(){var e,f,g;e=A;f=P();f!==y?(g=A,J++,f=Gb(),J--,f===y?g=void 0:(A=g,g=y),g!==y?(f=ma(),f!==y?(e=W.yh.length,Qk(W.fe,W.yh[W.i%e],f),W.i++,0===W.i%e&&Sk(W.fe),e=void 0):(A=e,e=y)):(A=e,e=y)):(A=e,e=y);return e}function E(){var e;
xb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&n(uc));return e}function F(){var e;e=E();e===y&&(e=I(),e===y&&(bb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&n(sa)),e===y&&(e=C(),e===y&&(yb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&n(gd)),e===y&&(91===f.charCodeAt(A)?(e=Tb,A++):(e=y,0===J&&n(cb)),e===y&&(93===f.charCodeAt(A)?(e=ob,A++):(e=y,0===J&&n(db))))))));return e}function G(){var e;e=E();e===y&&(e=I(),e===y&&(bb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&n(sa)),e===
y&&(e=C(),e===y&&(pb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&n(qa)),e===y&&(e=ca(),e===y&&(e=aa(),e===y&&(91===f.charCodeAt(A)?(e=Tb,A++):(e=y,0===J&&n(cb)),e===y&&(93===f.charCodeAt(A)?(e=ob,A++):(e=y,0===J&&n(db))))))))));return e}function I(){var e;34===f.charCodeAt(A)?(e=eb,A++):(e=y,0===J&&n(Ma));return e}function C(){var e;39===f.charCodeAt(A)?(e=qb,A++):(e=y,0===J&&n(zb));return e}function K(){var e;e=E();e===y&&(bb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&n(sa)),e===y&&
(95===f.charCodeAt(A)?(e=Na,A++):(e=y,0===J&&n(pa)),e===y&&(e=ca(),e===y&&(e=aa(),e===y&&(91===f.charCodeAt(A)?(e=Tb,A++):(e=y,0===J&&n(cb)),e===y&&(59===f.charCodeAt(A)?(e=N,A++):(e=y,0===J&&n(R)),e===y&&(93===f.charCodeAt(A)?(e=ob,A++):(e=y,0===J&&n(db)),e===y&&(e=C(),e===y&&(e=I())))))))));return e}function H(){var e;e=E();e===y&&(bb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&n(sa)),e===y&&(95===f.charCodeAt(A)?(e=Na,A++):(e=y,0===J&&n(pa)),e===y&&(e=ca(),e===y&&(e=aa(),e===y&&(91===f.charCodeAt(A)?
(e=Tb,A++):(e=y,0===J&&n(cb)),e===y&&(59===f.charCodeAt(A)?(e=N,A++):(e=y,0===J&&n(R)),e===y&&(93===f.charCodeAt(A)?(e=ob,A++):(e=y,0===J&&n(db)),e===y&&(e=I()))))))));return e}function L(){var e;e=E();e===y&&(bb.test(f.charAt(A))?(e=f.charAt(A),A++):(e=y,0===J&&n(sa)),e===y&&(95===f.charCodeAt(A)?(e=Na,A++):(e=y,0===J&&n(pa)),e===y&&(e=ca(),e===y&&(e=aa(),e===y&&(91===f.charCodeAt(A)?(e=Tb,A++):(e=y,0===J&&n(cb)),e===y&&(59===f.charCodeAt(A)?(e=N,A++):(e=y,0===J&&n(R)),e===y&&(93===f.charCodeAt(A)?
(e=ob,A++):(e=y,0===J&&n(db)),e===y&&(e=C()))))))));return e}function P(){var e,g,h;e=A;g=[];h=X();h===y&&(h=ca(),h===y&&(h=aa(),h===y&&(h=va())));if(h!==y)for(;h!==y;)g.push(h),h=X(),h===y&&(h=ca(),h===y&&(h=aa(),h===y&&(h=va())));else g=y;return e=g!==y?f.substring(e,A):g}function U(){var e,g,h,k,l,m;e=A;g=[];h=A;35===f.charCodeAt(A)?(k=rb,A++):(k=y,0===J&&n(Ha));if(k!==y){l=[];for(m=K();m!==y;)l.push(m),m=K();l!==y?(m=va(),m===y&&(m=Hb()),m!==y?h=k=[k,l,m]:(A=h,h=y)):(A=h,h=y)}else A=h,h=y;if(h!==
y)for(;h!==y;)if(g.push(h),h=A,35===f.charCodeAt(A)?(k=rb,A++):(k=y,0===J&&n(Ha)),k!==y){l=[];for(m=K();m!==y;)l.push(m),m=K();l!==y?(m=va(),m===y&&(m=Hb()),m!==y?h=k=[k,l,m]:(A=h,h=y)):(A=h,h=y)}else A=h,h=y;else g=y;return e=g!==y?f.substring(e,A):g}function X(){var e,f,g;e=A;f=[];g=ca();g===y&&(g=aa(),g===y&&(g=va()));if(g!==y)for(;g!==y;)f.push(g),g=ca(),g===y&&(g=aa(),g===y&&(g=va()));else f=y;f!==y?(g=U(),g!==y?e=f=[f,g]:(A=e,e=y)):(A=e,e=y);return e}function oa(){var e,g,h,k,l;g=e=A;95===f.charCodeAt(A)?
(h=Na,A++):(h=y,0===J&&n(pa));if(h!==y){k=[];l=F();if(l!==y)for(;l!==y;)k.push(l),l=F();else k=y;k!==y?g=h=[h,k]:(A=g,g=y)}else A=g,g=y;return e=g!==y?f.substring(e,A):g}function ma(){var e,g;e=A;var h,k,l,m,q,r,t,w,x;g=A;59===f.charCodeAt(A)?(h=N,A++):(h=y,0===J&&n(R));if(h!==y){k=[];for(l=K();l!==y;)k.push(l),l=K();if(k!==y)if(l=va(),l!==y){m=[];r=q=A;t=G();if(t!==y){w=[];for(x=K();x!==y;)w.push(x),x=K();w!==y?r=t=[t,w]:(A=r,r=y)}else A=r,r=y;r===y&&(r=null);r!==y?(t=va(),t!==y?q=r=[r,t]:(A=q,q=
y)):(A=q,q=y);for(;q!==y;){m.push(q);r=q=A;t=G();if(t!==y){w=[];for(x=K();x!==y;)w.push(x),x=K();w!==y?r=t=[t,w]:(A=r,r=y)}else A=r,r=y;r===y&&(r=null);r!==y?(t=va(),t!==y?q=r=[r,t]:(A=q,q=y)):(A=q,q=y)}m!==y?(59===f.charCodeAt(A)?(q=N,A++):(q=y,0===J&&n(R)),q!==y?g=h=[h,k,l,m,q]:(A=g,g=y)):(A=g,g=y)}else A=g,g=y;else A=g,g=y}else A=g,g=y;e=g!==y?f.substring(e,A):g;if(e===y){h=g=e=A;k=I();if(k!==y){l=[];for(m=L();m!==y;)l.push(m),m=L();l!==y?(m=I(),m!==y?h=k=[k,l,m]:(A=h,h=y)):(A=h,h=y)}else A=h,
h=y;g=h!==y?f.substring(g,A):h;if(g===y){g=A;h=C();if(h!==y){k=[];l=H();l===y&&(l=A,m=C(),m!==y?(q=A,J++,r=P(),J--,r===y?q=void 0:(A=q,q=y),q!==y?l=m=[m,q]:(A=l,l=y)):(A=l,l=y));for(;l!==y;)k.push(l),l=H(),l===y&&(l=A,m=C(),m!==y?(q=A,J++,r=P(),J--,r===y?q=void 0:(A=q,q=y),q!==y?l=m=[m,q]:(A=l,l=y)):(A=l,l=y));k!==y?(l=C(),l!==y?g=h=[h,k,l]:(A=g,g=y)):(A=g,g=y)}else A=g,g=y;if(g===y)if(g=A,h=E(),h!==y){k=A;l=[];for(m=F();m!==y;)l.push(m),m=F();k=l!==y?f.substring(k,A):l;k!==y?g=h=[h,k]:(A=g,g=y)}else A=
g,g=y}e=g!==y?f.substring(e,A):g;e===y&&(e=A,Ub.test(f.charAt(A))?(g=f.charAt(A),A++):(g=y,0===J&&n(Jc)),e=g!==y?f.substring(e,A):g,e===y&&(e=A,hc.test(f.charAt(A))?(g=f.charAt(A),A++):(g=y,0===J&&n(Vb)),e=g!==y?f.substring(e,A):g))}return e}function Gb(){var e,g,h,k,l,m,q;g=e=A;sb.test(f.charAt(A))?(h=f.charAt(A),A++):(h=y,0===J&&n(tb));h===y&&(Ja.test(f.charAt(A))?(h=f.charAt(A),A++):(h=y,0===J&&n(Cb)));h!==y?(ra.test(f.charAt(A))?(k=f.charAt(A),A++):(k=y,0===J&&n(Oa)),k===y&&(ka.test(f.charAt(A))?
(k=f.charAt(A),A++):(k=y,0===J&&n(Wa))),k!==y?(ra.test(f.charAt(A))?(l=f.charAt(A),A++):(l=y,0===J&&n(Oa)),l===y&&(ka.test(f.charAt(A))?(l=f.charAt(A),A++):(l=y,0===J&&n(Wa))),l!==y?(ta.test(f.charAt(A))?(m=f.charAt(A),A++):(m=y,0===J&&n(gb)),m===y&&(vc.test(f.charAt(A))?(m=f.charAt(A),A++):(m=y,0===J&&n(wc))),m!==y?(pb.test(f.charAt(A))?(q=f.charAt(A),A++):(q=y,0===J&&n(qa)),q!==y?g=h=[h,k,l,m,q]:(A=g,g=y)):(A=g,g=y)):(A=g,g=y)):(A=g,g=y)):(A=g,g=y);return e=g!==y?f.substring(e,A):g}function Sb(){var e,
g,h,k,l,m,q;g=e=A;Wb.test(f.charAt(A))?(h=f.charAt(A),A++):(h=y,0===J&&n(wa));h===y&&(la.test(f.charAt(A))?(h=f.charAt(A),A++):(h=y,0===J&&n(xa)));h!==y?(Ia.test(f.charAt(A))?(k=f.charAt(A),A++):(k=y,0===J&&n(Va)),k===y&&(fb.test(f.charAt(A))?(k=f.charAt(A),A++):(k=y,0===J&&n(ia))),k!==y?(Lc.test(f.charAt(A))?(l=f.charAt(A),A++):(l=y,0===J&&n(Ca)),l===y&&(Jb.test(f.charAt(A))?(l=f.charAt(A),A++):(l=y,0===J&&n(Mc))),l!==y?(Nc.test(f.charAt(A))?(m=f.charAt(A),A++):(m=y,0===J&&n(Xb)),m===y&&(Pa.test(f.charAt(A))?
(m=f.charAt(A),A++):(m=y,0===J&&n(Ka))),m!==y?(pb.test(f.charAt(A))?(q=f.charAt(A),A++):(q=y,0===J&&n(qa)),q!==y?g=h=[h,k,l,m,q]:(A=g,g=y)):(A=g,g=y)):(A=g,g=y)):(A=g,g=y)):(A=g,g=y);return e=g!==y?f.substring(e,A):g}function ca(){var e;32===f.charCodeAt(A)?(e=kc,A++):(e=y,0===J&&n(xc));return e}function aa(){var e;9===f.charCodeAt(A)?(e=lc,A++):(e=y,0===J&&n(hb));return e}function va(){var e;10===f.charCodeAt(A)?(e=Kb,A++):(e=y,0===J&&n(Xa));e===y&&(13===f.charCodeAt(A)?(e=Lb,A++):(e=y,0===J&&n(mc)),
e===y&&(f.substr(A,2)===Db?(e=Db,A+=2):(e=y,0===J&&n(ua))));return e}function Hb(){var e,g;e=A;J++;f.length>A?(g=f.charAt(A),A++):(g=y,0===J&&n(Qa));J--;g===y?e=void 0:(A=e,e=y);return e}this.fe=g;var W=this,l=1<arguments.length?arguments[1]:{},y={},Ib={start:m},na=m,xb=/^[a-zA-Z0-9!%&*()+,-.\/:<=>?@\^`{|}~\\]/,uc={type:"class",value:"[a-zA-Z0-9!%&*()+,-\\./:<=>?@\\^`{|}~\\\\]",description:"[a-zA-Z0-9!%&*()+,-\\./:<=>?@\\^`{|}~\\\\]"},bb=/^[#$]/,sa={type:"class",value:"[#$]",description:"[#$]"},yb=
/^[_;']/,gd={type:"class",value:"[_;']",description:"[_;']"},Tb="[",cb={type:"literal",value:"[",description:'"["'},ob="]",db={type:"literal",value:"]",description:'"]"'},pb=/^[_]/,qa={type:"class",value:"[_]",description:"[_]"},eb='"',Ma={type:"literal",value:'"',description:'"\\""'},qb="'",zb={type:"literal",value:"'",description:'"\'"'},Na="_",pa={type:"literal",value:"_",description:'"_"'},N=";",R={type:"literal",value:";",description:'";"'},rb="#",Ha={type:"literal",value:"#",description:'"#"'},
Ub=/^[.]/,Jc={type:"class",value:"[.]",description:"[.]"},hc=/^[?]/,Vb={type:"class",value:"[?]",description:"[?]"},Kc=/^[D]/,ic={type:"class",value:"[D]",description:"[D]"},Ab=/^[d]/,jc={type:"class",value:"[d]",description:"[d]"},Ia=/^[A]/,Va={type:"class",value:"[A]",description:"[A]"},fb=/^[a]/,ia={type:"class",value:"[a]",description:"[a]"},ba=/^[T]/,da={type:"class",value:"[T]",description:"[T]"},Ba=/^[t]/,Bb={type:"class",value:"[t]",description:"[t]"},sb=/^[L]/,tb={type:"class",value:"[L]",
description:"[L]"},Ja=/^[l]/,Cb={type:"class",value:"[l]",description:"[l]"},ra=/^[O]/,Oa={type:"class",value:"[O]",description:"[O]"},ka=/^[o]/,Wa={type:"class",value:"[o]",description:"[o]"},ta=/^[P]/,gb={type:"class",value:"[P]",description:"[P]"},vc=/^[p]/,wc={type:"class",value:"[p]",description:"[p]"},Wb=/^[S]/,wa={type:"class",value:"[S]",description:"[S]"},la=/^[s]/,xa={type:"class",value:"[s]",description:"[s]"},Lc=/^[V]/,Ca={type:"class",value:"[V]",description:"[V]"},Jb=/^[v]/,Mc={type:"class",
value:"[v]",description:"[v]"},Nc=/^[E]/,Xb={type:"class",value:"[E]",description:"[E]"},Pa=/^[e]/,Ka={type:"class",value:"[e]",description:"[e]"},kc=" ",xc={type:"literal",value:" ",description:'" "'},lc="\t",hb={type:"literal",value:"\t",description:'"\\t"'},Kb="\n",Xa={type:"literal",value:"\n",description:'"\\n"'},Lb="\r",mc={type:"literal",value:"\r",description:'"\\r"'},Db="\r\n",ua={type:"literal",value:"\r\n",description:'"\\r\\n"'},Qa={type:"any",description:"any character"},A=0,ub=[{line:1,
mb:1,bc:!1}],fa=0,Yb=[],J=0,ya;if("startRule"in l){if(!(l.qf in Ib))throw Error("Can't start parsing from rule \""+l.qf+'".');na=Ib[l.qf]}ya=na();if(ya!==y&&A===f.length)return ya;ya!==y&&A<f.length&&n({type:"end",description:"end of input"});throw function(f,g,h,k){function l(e){var f=1;for(e.sort(function(e,f){return e.description<f.description?-1:e.description>f.description?1:0});f<e.length;)e[f-1]===e[f]?e.splice(f,1):f++}function m(e,f){function g(e){function f(e){return e.charCodeAt(0).toString(16).toUpperCase()}
return e.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\x08/g,"\\b").replace(/\t/g,"\\t").replace(/\n/g,"\\n").replace(/\f/g,"\\f").replace(/\r/g,"\\r").replace(/[\x00-\x07\x0B\x0E\x0F]/g,function(e){return"\\x0"+f(e)}).replace(/[\x10-\x1F\x80-\xFF]/g,function(e){return"\\x"+f(e)}).replace(/[\u0100-\u0FFF]/g,function(e){return"\\u0"+f(e)}).replace(/[\u1000-\uFFFF]/g,function(e){return"\\u"+f(e)})}var h=Array(e.length),k;for(k=0;k<e.length;k++)h[k]=e[k].description;h=1<e.length?h.slice(0,-1).join(", ")+
" or "+h[e.length-1]:h[0];k=f?'"'+g(f)+'"':"end of input";return"Expected "+h+" but "+k+" found."}null!==g&&l(g);return new e(null!==f?f:m(g,h),0,0,k)}(null,Yb,fa<f.length?f.charAt(fa):null,fa<f.length?k(fa,fa+1):k(fa,fa));}}}();
}(biovizWorkerNamespace));